
# Discussion and conclusions {background-color="#491106ff"}


## Discussion and conclusions

### On network diversity

* Consistent with H1, individual change decreases the degree of agreement of people in Chile that income should govern access to social services - **supporting the market skepticism hypothesis.** Those who increase their
network diversity tend to become **more critical towards** the market mechanism as a legitimate way of allocating social welfare 

* According to theorization, evidence here shows that network change attitudes. It could be through the (non-exclusive) channels of :(i) **_socialization_**: overtime, individuals **normatively adapt** to their new social milieus which is reflected in attitudes [(Ares, 2020; Helgason & Rehm, 2024; Otero & Mendoza, 2023)]{style="color: blue; font-weight: bold;"}. 

* Alternatively, could be that (ii) **_information_** plays a role itself as **non-redundant environments** motivate attitudinal changes in line with the inferential/social learning approach [(Druckman & Lupia; Mijs, 2018)]{style="color: blue; font-weight: bold;"}.

