---
title: "Análisis de datos"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
editor_options: 
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
options(scipen=9999) # desactivar notacion cientifica
```

```{r dfreg}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
rm(list=ls())
# load(here::here("input/data/proc/study2.RData"))
load(here::here("input/data/proc/study2.RData")); elsoc_long<- elsoc_long
pacman::p_load(correlation,lme4,plm,panelr,texreg,dplyr,estimatr,marginaleffects,ggplot2,sjmisc,MLMusingR,ordinal)  
dfreg <-
elsoc_long %>%
  group_by(idencuesta) %>%
  mutate(just_educ = if_else(ola == 5 & is.na(just_educ), last(just_educ[ola == 6]), just_educ),
         just_salud = if_else(ola == 5 & is.na(just_salud), last(just_salud[ola == 6]), just_salud),
         just_pension = if_else(ola == 5 & is.na(just_pension), last(just_pension[ola == 6]), just_pension)
         ) %>%
  ungroup() 

dfreg$market<- rowMeans(dfreg[,c("just_educ","just_salud","just_pension")],na.rm = T)
dfreg$market <- ((dfreg$market-min(dfreg$market,na.rm = T))/(max(dfreg$market,na.rm = T)-min(dfreg$market,na.rm = T)))*100
sjlabelled::set_label(dfreg$market) <- "Market-based distribution of social services (3 items)"

dfreg$just_educ <- ((dfreg$just_educ-min(dfreg$just_educ,na.rm = T))/(max(dfreg$just_educ,na.rm = T)-min(dfreg$just_educ,na.rm = T)))*100
dfreg$just_salud <- ((dfreg$just_salud-min(dfreg$just_salud,na.rm = T))/(max(dfreg$just_salud,na.rm = T)-min(dfreg$just_salud,na.rm = T)))*100
dfreg$just_pension <- ((dfreg$just_pension-min(dfreg$just_pension,na.rm = T))/(max(dfreg$just_pension,na.rm = T)-min(dfreg$just_pension,na.rm = T)))*100

dfreg$egp6_hh <- car::recode(
  dfreg$egp11_hh_label,
  recodes = "
'I Higher Controllers'='Service class (I-higher grade)';
'II Lower Controllers'='Service class (II-lower grade)';
c('IIIa Routine Nonmanual','IIIb Lower Sales-Service')='Routine nonmanuals (IIIa.b)';
c('IVa Self-employed with employees','IVb Self-employed with no employees','IVc Self-employed Farmer')='Self-employed (IVa.b.c)';
c('V Manual Supervisors','VI Skilled Worker')='Skilled manual workers and supv. (V+VI)';
c('VIIa Unskilled Worker','VIIb Farm Labor')='Non-skilled manual workers (VIIa.b)';NA='No information'",
levels = c(
  "Service class (I-higher grade)",
  "Service class (II-lower grade)",
  "Routine nonmanuals (IIIa.b)",
  "Self-employed (IVa.b.c)",
  "Skilled manual workers and supv. (V+VI)",
  "Non-skilled manual workers (VIIa.b)",
  'No information'
)
);frq(dfreg$egp6_hh)

dfreg$N_high<- (dfreg$num_high*(dfreg$num_high-1))/(dfreg$n_total*(dfreg$n_total-1));summary(dfreg$N_high)
dfreg$N_middle<- (dfreg$num_middle*(dfreg$num_middle-1))/(dfreg$n_total*(dfreg$n_total-1));summary(dfreg$N_middle)
dfreg$N_low<- (dfreg$num_low*(dfreg$num_low-1))/(dfreg$n_total*(dfreg$n_total-1));summary(dfreg$N_low)
dfreg$blau_b <- 1-rowSums(dfreg[,c("N_high","N_middle","N_low")],na.rm = T);summary(dfreg$blau_b)
dfreg$blau_b <- ifelse(dfreg$num_high==0 & dfreg$num_middle==0 & dfreg$num_low==0,yes = NA,no = dfreg$blau_b)
dfreg$blau_b <- ifelse(dfreg$n_total==1,yes = 0,no = dfreg$blau_b)

dfreg$quintil <- as.numeric(dfreg$quintil_fx)
dfreg$oesch5_r_fx <- factor(dfreg$oesch5_r_fx,ordered = F)
# dfreg$isei08res_ter_fx <- as.factor(ntile(dfreg$isei08res_fx,3));frq(dfreg$isei08res_ter_fx)

# Deflator
# For 2021: CPI = 100 (base year)
# For 2019: IPC = 3.0%
# For 2018: IPC = 2.6%
# For 2017: IPC = 2,3#
# For 2016: IPC = 2.7%

# The CPI values relative to 2021 are:
# 2019 CPI: 97.09
# 2018 CPI: 97.47
# 2017 CPI: 97.75
# 2016 CPI: 97.37

dfreg$cpi <- dfreg$ola
dfreg$cpi <- car::recode(dfreg$cpi,"1=97.37;2=97.75;3=97.47;4=97.09;5=100")
dfreg$real_income <- as.numeric((dfreg$ing_pc/dfreg$cpi)* 100)
dfreg$real_income_eq <- as.numeric((dfreg$ing_pc_eq/dfreg$cpi)* 100)
summary(dfreg$real_income)
summary(dfreg$real_income_eq)

dfreg$ing_pc_100 <- (dfreg$real_income_eq) # each unit is 100.000 CLP
dfreg$decile <- ntile(dfreg$ing_pc_100,10)

df1 <-  
dfreg %>%
  filter(muestra==1) %>%
  filter(ola %in% c(1,3,5)) %>%
  # filter(m0_edad %in% c(15:64)) %>%
  filter(ing_pc>0) %>%
  select(id="idencuesta",ola,
         diversityclass=iqvclass,know_total,
         crossclass,isei_sd,
         strong_tie_t1,
         empst,
         just_educ,
         just_salud,
         just_pension,
         market,
         income=ing_pc_100,
         educ=educyear,
         # class=isei08res_ter_fx,
         age=m0_edad,
         sex=sexo_fx,
         weights1=ponderador_long_total,
         ponderador01,ponderador02
         ) %>%
  mutate(income=log(income)) %>%
  arrange(ola)
table(df1$ola)

df1 <-   na.omit(df1)

# fix to complete cases
idfreq<- frq(df1$id) %>% data.frame() %>% select(val,frq);filter<- idfreq %>% filter(frq>=1);df1 <- df1 %>% filter(id %in% filter$val)

dim(df1)

df1$time <- as.numeric(df1$ola)
table(df1$time)
# Model w/o isei range
model_wo_range <- 'diversitycfa_norange =~ diversityclass+crossclass + isei_sd+know_total'
fit_range<- lavaan::cfa(model = model_wo_range,data = df1,cluster = "id",
                        sampling.weights = "weights1"
                        )
lavaan::summary(fit_range,standardized=T,fit.measures=T)
# Model using blau, sd, extensivity and number of different "social classes" known (cross-class) is the best

factorscores<- lavaan::lavPredict(fit_range,newdata = df1)
idx <- lavaan::lavInspect(fit_range, "case.idx")
fscores <- lavaan::lavPredict(fit_range)
## loop over factors
for (fs in colnames(fscores)) {
  df1[idx, fs] <- fscores[ , fs]
}

df1 <- df1 %>% rename(diversitycfa=diversitycfa_norange);df1$diversityclass <- df1$diversitycfa 
paneldata <- panelr::panel_data(df1, id = id, wave = time)
```

```{r mean-center}
df1 <-
df1 %>% 
  mutate(
    diversity_gc=MLMusingR::group_center(x = as.numeric(diversityclass),grp = id),
    diversity_gm=MLMusingR::group_mean(x = as.numeric(diversityclass),grp = id),
    age_gc=MLMusingR::group_center(x = as.numeric(age),grp = id),
    age_gm=MLMusingR::group_mean(x = as.numeric(age),grp = id),
    income_gm=MLMusingR::group_mean(x = as.numeric(income),grp = id),
    income_gc=MLMusingR::group_center(x = as.numeric(income),grp = id),
    educ_gm=MLMusingR::group_mean(x = as.numeric(educ),grp = id),
    educ_gc=MLMusingR::group_center(x = as.numeric(educ),grp = id),
    empst_gm=MLMusingR::group_mean(x = as.numeric(empst),grp = id),
    empst_gc=MLMusingR::group_center(x = as.numeric(empst),grp = id)
    )
```

# Multinivel

```{r}
# Hypothesis___________________________________________________________________
divtimeF <-"factor(time)"
divtimeL <-"time"
divgm    <-"time+diversity_gm+income_gm+educ_gm+age_gm+empst_gm+sex"
divcwc   <-"time+diversity_gc+income_gc+educ_gc+age_gc+empst_gc+sex"
divwbfull<-paste0(divgm,"+",divcwc)
divwbb_int1<-paste0(divwbfull,"+","income_gm*diversity_gc+income_gc*diversity_gc")
divwbb_int2<-paste0(divwbfull,"+","educ_gm*diversity_gc+educ_gc*diversity_gc")
divwbb_int3<-paste0(divwbfull,"+","class*diversity_gc")

hipotesis <- c(divtimeF,divtimeL,divgm,divcwc,divwbfull,
               divwbb_int1,divwbb_int2
               # divwbb_int3
               )
# Set the independent variables (IVs)
ivs<- as.data.frame(df1) %>% select(just_educ,just_salud,just_pension) %>%  names()

# Create the object for each model
models <- list()
for (i in ivs) {
models[[i]] <- paste0(i,"~",hipotesis,"+(1|id)")  
}

# Estimate the multilevel models
fits <- list()
for (i in ivs) {
  for (z in models[[i]][1:length(hipotesis)]) {
    fits[[z]] <- lme4::lmer(formula = z, data = df1,weights = weights1)
  }
}
# change model names within list
names(fits) <- paste0(rep(ivs,each=length(hipotesis)),1:length(hipotesis))

# Tables_______________________________________________________________________
omit <- "(empst_gm)|(empst_gc)|(sex)|(age_gm)|(age_gc)|(Intercept)"
coef_names <- c("Wave 2018 ","Wave 2021", "Wave",
                "Diversity (BE)","Income (BE)","Education (BE)",
                "Diversity (WE)","Income (WE)","Education (WE)",
                "Diversity (WE) x Income (BE)","Diversity (WE) x Income (WE)",
                "Diversity (WE) x Education (BE)","Diversity (WE) x Education (WE)"
                # "Diversity (WE) x ISEI (Medium)","Diversity (WE) x ISEI (High)"
                )
var_groups  <- list(
    "Wave (ref: Wave 2016)" = 1:2,
    "Between-person estimates" = 4:6,
    "Within-person estimates" = 7:9,
    "Interactions" = 10:13
  )

screenreg(l = fits[names(fits)[grepl("just_educ", names(fits),"\n")]],single.row = F,
        omit.coef = omit,
        groups = var_groups,
        custom.coef.names = coef_names,
        caption = "Longitudinal multilevel models for market justice in education, network diversity and socioeconomic status",
        caption.above = T,
        # file = "output/tables/justeduc_mixed.html",
          )
screenreg(l = fits[names(fits)[grepl("just_salud", names(fits),"\n")]],single.row = F,
          omit.coef = omit,
          groups = var_groups,
          custom.coef.names = coef_names,
        caption = "Longitudinal multilevel models for market justice in health, network diversity and socioeconomic status",
        caption.above = T,
        # file = "output/tables/justsalud_mixed.html",          
          )
screenreg(l = fits[names(fits)[grepl("just_pension", names(fits),"\n")]],single.row = F,
          omit.coef = omit,
          # groups = var_groups,
          # custom.coef.names = coef_names,
        caption = "Longitudinal multilevel models for market justice in pensions, network diversity and socioeconomic status",
        caption.above = T,
        # file = "output/tables/justpensions_mixed.html",          
          )

screenreg(l = fits[c("just_educ5","just_educ6","just_educ7",
                     "just_salud5","just_salud6","just_salud7",
                     "just_pension5","just_pension6","just_pension7")])



plot_predictions(mixeduc_wb[["divwbb_int1"]],condition = list("diversity_gc", "income_gc"="threenum")) +
  scale_fill_discrete(name = "Income (CWC)",labels=c("-1SD","Mean","+1SD")) +
  scale_color_discrete(name = "Income (CWC)",labels=c("-1SD","Mean","+1SD")) +
  labs(x="Diversity (CWC)",y="Justice Education (0 - 100)") + theme(legend.position = "right")
```


```{r}
library(gridExtra)
library(grid)
library(sjPlot)
# main models 
# custom_coef = list(diversityclass="Diversity",
#                    income="Income")


custom_coef =  c("age_gc","age_gm","sex","educ","class","income_gm","educ_gm","sex", "diversity_gm","class2","class3")
# "Servicio-alto (Ref)\nServicio\nbajo","Pequeños\npropietarios","Trabajadores\n calificados","Trabajadores\n calificados"
# coef_labs <- c("Diversidad","Decil\nIngreso","Educación","Sexo\n(Ref.=Mujer)","Edad")
# coef_labs <- c("Ingreso (GM)","Diversidad (GM)","Ingreso (CWC)","Diversidad (CWC)","Ola (tiempo)")

coef_labs <- c("Education (within)","Income (within)","Diversity (within)","Time (wave)")

main_educ <- plot_model(mixeduc_wb[["divwbfull"]], vline.color = "red",rm.terms =  custom_coef,show.values = T,show.p = T,title = "Education") +scale_x_discrete(label=coef_labs) +scale_y_continuous(limits = c(-30,20))
main_salu <- plot_model(mixsalud_wb[["divwbfull"]], vline.color = "red",rm.terms =  custom_coef,show.values = T,show.p = T,title = "Health")+ scale_x_discrete(label=coef_labs)+scale_y_continuous(limits = c(-30,20))
main_pens <- plot_model(mixpension_wb[["divwbfull"]], vline.color = "red",rm.terms =  custom_coef,show.values = T,show.p = T,title = "Pensions")+ scale_x_discrete(label=coef_labs)+scale_y_continuous(limits = c(-30,20))
grid.arrange(main_educ,main_salu,main_pens, nrow = 1,top = textGrob(
    "It fair that people with higher incomes should have better:",
    gp = gpar(fontface = 1, fontsize = 15,fontfamily='serif')))

# interactions
pred_educ<- plot_predictions(mixpension_wb[["divwbb_int1"]],condition = list("diversity_gc", "income_gc"="threenum")) +
  scale_y_continuous(limits = c(0,60))+
  scale_fill_discrete(name = "Income (WE)",labels=c("-1SD","Mean","+1SD")) +
  scale_color_discrete(name = "Income (WE)",labels=c("-1SD","Mean","+1SD")) +
  labs(x="Diversity (WE)",y="Education (0 - 100)",title = "Education") + theme(legend.position = "bottom") 

pred_salu <- plot_predictions(mixsalud_wb[["divwbb_int1"]],condition = list("diversity_gc", "income_gc"="threenum")) +
  scale_y_continuous(limits = c(0,60))+
  scale_fill_discrete(name = "Income (WE)",labels=c("-1SD","Mean","+1SD")) +
  scale_color_discrete(name = "Income (WE)",labels=c("-1SD","Mean","+1SD")) +
  labs(x="Diversity (WE)",y="Health (0 - 100)",title = "Health") + theme(legend.position = "bottom") 

pred_pens <- plot_predictions(mixpension_wb[["divwbb_int1"]],condition = list("diversity_gc", "income_gc"="threenum")) +
  scale_y_continuous(limits = c(0,60))+
  scale_fill_discrete(name = "Income (WE)",labels=c("-1SD","Mean","+1SD")) +
  scale_color_discrete(name = "Income (WE)",labels=c("-1SD","Mean","+1SD")) +
  labs(x="Diversity (WE)",y="Pensions (0 - 100)",title = "Pensions",) + theme(legend.position = "bottom") 

grid.arrange(pred_educ,pred_salu,pred_pens, nrow = 1)
```


```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
RColorBrewer::display.brewer.all()
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)

estimations <- bind_rows(
mixeduc[["divdemo"]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term==c("diversityclass")) %>% mutate(DV="1.Education"),
mixsalud[["divdemo"]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="diversityclass") %>% mutate(DV="2. Health"),
mixpension[["divdemo"]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="diversityclass") %>% mutate(DV="3. Pensions")
# mixmarket2[[6]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="diversityclass") %>% mutate(DV="4. Market (1+2)"),
# mixmarket[["divdemo"]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="diversityclass") %>% mutate(DV="5. Market (1+2+3)")
)
nobs<- nobs(mixpension[["divdemo"]]) 
ngrps<-  lme4::ngrps(mixpension[["divdemo"]])

ggplot(estimations,aes(x=term,y=estimate,group=DV,color=DV,ymin = conf.low, ymax = conf.high)) +  
  geom_point(size=5,position=position_dodge(width=2)) +
  geom_errorbar(size=2,width = 0,position = position_dodge(width = 2)) +
  labs(y="Estimation",x=NULL,title = "Network diversity on market preferences for social services",
       caption = paste0("Obs.= ",nobs, ". Ind. = ",ngrps, ". Multilevel longitudinal models")) +
  geom_hline(yintercept = 0,color="red",linetype=2)+
  coord_flip()+
  scale_x_discrete(labels=c("Network\ndiversity"))+
  # scale_y_continuous(limits = c(-0.8,0.6)) +
  theme(legend.title = element_blank(),legend.position = "bottom",
        axis.title = element_text(size = 18))


nclust<-  lme4::ngrps(mixmarket[[7]])[[2]]

estimations_seg <- bind_rows(
mixeduc[[7]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term==c("segr")) %>% mutate(DV="1. Education"),
mixsalud[[7]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="segr") %>% mutate(DV="2. Health"),
mixpension[[7]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="segr") %>% mutate(DV="3. Pensions"),
# mixmarket2[[6]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="diversityclass") %>% mutate(DV="4. Market (1+2)"),
mixmarket[[7]] %>% broom.mixed::tidy(conf.int = TRUE) %>% filter(term=="segr") %>% mutate(DV="5. Market (1+2+3)")
)

ggplot(estimations_seg,aes(x=term,y=estimate,group=DV,color=DV,ymin = conf.low, ymax = conf.high)) +  
  geom_point(size=5,position=position_dodge(width=2)) +
  geom_errorbar(size=2,width = 0.5,position = position_dodge(width = 2)) +
  labs(y="Estimation",x=NULL,title = "Spatial segregation on market preferences for social services",
       caption = paste0("Obs.=",nobs, ". Ind.=",ngrps, ". Clus.=",nclust,". Multilevel longitudinal models")) +
  geom_hline(yintercept = 0,color="red",linetype=2)+
  coord_flip()+
  scale_x_discrete(labels=c("Spatial\nsegregation"))+
  # scale_y_continuous(limits = c(-0.8,0.6)) +
  theme(legend.title = element_blank(),legend.position = "bottom",
        axis.title = element_text(size = 15))


sjPlot::plot_model(mixmarket[[7]],type = "pred",terms = "segr",colors = "#984EA3",line.size = 2) +
  labs(x="Segregation",y=NULL,title = "Predicted values for Market (1+2+3)") +
  scale_y_continuous(limits = c(1,5),labels = stringr::str_wrap(sjlabelled::get_labels(elsoc_long$just_educ),10))

sjPlot::plot_model(mixeduc[[7]],type = "pred",terms = "segr",colors = "red",line.size = 2) +
  labs(x="Segregation",y=NULL,title = "Predicted values for Education ") +
  scale_y_continuous(limits = c(1,5),labels = stringr::str_wrap(sjlabelled::get_labels(elsoc_long$just_educ),10))


sjPlot::plot_model(mixsalud[[7]],type = "pred",terms = "segr",colors = "blue",line.size = 2) +
  labs(x="Segregation",y=NULL,title = "Predicted values for Heatlh ") +
  scale_y_continuous(limits = c(1,5),labels = stringr::str_wrap(sjlabelled::get_labels(elsoc_long$just_educ),10))

sjPlot::plot_model(mixpension[[7]],type = "pred",terms = "segr",colors = "darkgreen",line.size = 2) +
  labs(x="Segregation",y=NULL,title = "Predicted values for Pension") +
  scale_y_continuous(limits = c(1,5),labels = stringr::str_wrap(sjlabelled::get_labels(elsoc_long$just_educ),10))
```


# Fixed effects regression

```{r}
library(plm) 
library(panelr)
# paneldata <- panelr::panel_data(df1, id = id, wave = time)
paneldata <- paneldata %>% filter(time %in% c(1,3,5))

#test tge haussman indica que es mejor usar FE con two-way 
mkt_educ <- plm(just_educ ~ time+diversityclass+age+income+educ+sex,data=paneldata,weights = weights1,model = "within")
mkt_educ2 <- plm(just_educ ~ time+diversityclass*income+age+income+educ+sex,data=paneldata,weights = weights1,model = "within")
mkt_educ3 <- plm(just_educ ~ time+diversityclass*educ+age+income+educ+sex,data=paneldata,weights = weights1,model = "within")


mkt_salu <- plm(just_salud ~ time+diversityclass+age+income+educ+sex ,data=paneldata,weights = weights1, model="within")
mkt_salu2 <- plm(just_salud ~ time+diversityclass*income+age+income+educ+sex ,data=paneldata,weights = weights1, model="within")
mkt_salu3 <- plm(just_salud ~ time+diversityclass*educ+age+income+educ+sex ,data=paneldata,weights = weights1, model="within")

mkt_pens <- plm(just_pension ~ time+diversityclass+age +income +educ+sex ,data=paneldata,weights = weights1, model="within")
mkt_pens2 <- plm(just_pension ~ time+diversityclass*income+age+income+educ+sex ,data=paneldata,weights = weights1, model="within")
mkt_pens3 <- plm(just_pension ~ time+diversityclass*educ+age+income+educ+sex ,data=paneldata,weights = weights1, model="within")


market_models_fe <- list(mkt_educ,mkt_educ2,mkt_educ3,
                         mkt_salu,mkt_salu2,mkt_salu3,
                         mkt_pens,mkt_pens2,mkt_pens3) 


screenreg(market_models_fe,stars = c(0.001,0.01,0.05,0.1))
```

# Descriptive by wave
```{r}
m_low <- lm(porc_low/100~factor(time),df1,weights = ponderador02,subset = time %in% c(1,3,5))
plot_predictions(m_low, condition = "time")

m_mid<- lm(porc_middle/100~factor(time),df1,weights = ponderador02 ,subset = time %in% c(1,3,5))
plot_predictions(m_mid, condition = "time")

m_high<- lm(porc_high/100~factor(time),df1,weights = ponderador02 ,subset = time %in% c(1,3,5))
plot_predictions(m_high, condition = "time")

m_div <- lm(diversityclass~factor(time),df1,weights = ponderador02 ,subset = time %in% c(1,3,5))
plot_predictions(m_div, condition = "time")


# psych::alpha(df1 %>% filter(time==1) %>%  select(just_educ,just_salud,just_pension)) #.82
# psych::alpha(df1 %>% filter(time==3) %>%  select(just_educ,just_salud,just_pension)) #.85
# psych::alpha(df1 %>% filter(time==5) %>%  select(just_educ,just_salud,just_pension)) #.79


#.82
#.85
#.79


labels<- sjlabelled::get_labels(elsoc_long[,c("just_pension","just_salud","just_educ")])

df1 %>% select("just_pension","just_salud","just_educ") %>% 
  sjlabelled::set_label(label = sjlabelled::get_label(elsoc_long[,c("just_pension","just_salud","just_educ")])) %>% 
  sjlabelled::set_labels(labels = labels) %>% 
  sjPlot::plot_stackfrq(show.total = F,wrap.legend.labels = 10,wrap.labels = 20,axis.labels = c("pensions than people with lower income"," health care than people with lower income.","education for their children than people with lower income")) + 
  labs(title = "It is fair that people with higher incomes have better:") +
  theme(legend.position = "bottom")
  

df_status<- 
bind_rows(
# plot_predictions(m_low, condition = "time",draw = F) %>% mutate(class="1. Lower status"),
# plot_predictions(m_mid, condition = "time",draw = F)%>% mutate(class="2. Medium status"),
# plot_predictions(m_high, condition = "time",draw = F)%>% mutate(class="3. Higher status")
plot_predictions(m_div, condition = "time",draw = F)%>% mutate(class="4. Diversity")
)

ggplot(df_status,aes(x=time,y=estimate,group=class,color=class,ymin = conf.low, ymax = conf.high)) +  
  geom_line(size=0.7) +
  geom_pointrange(size=0.5) +
  labs(y="Proportion of ties",x=NULL,title = "Network ties according to status groups by year") +
  scale_x_discrete(labels=c("2016","2018","2021"))+
  scale_y_continuous(limits = c(0.20,1)) +
  theme(legend.title = element_blank())

ggplot(df_status,aes(x=time,y=estimate,group=class,color=class,ymin = conf.low, ymax = conf.high)) +  
  geom_line(size=0.7) +
  geom_pointrange(size=0.5) +
  labs(y="Diversity",x=NULL,title = "Network diversity index according to status groups by year") +
  scale_x_discrete(labels=c("2016","2018","2021"))+
  scale_y_continuous(limits = c(0.2,1)) +
  theme(legend.title = element_blank())



m_educ <- lm(just_educ~factor(time),df1,weights = ponderador02 ,subset = time %in% c(1,3,5))
plot_predictions(m_educ, condition = "time")

m_salud <- lm(just_salud~factor(time),df1,weights = ponderador02 ,subset = time %in% c(1,3,5))
plot_predictions(m_salud, condition = "time")

m_pension <- lm(just_pension~factor(time),df1,weights = ponderador02 ,subset = time %in% c(1,3,5))
plot_predictions(m_pension, condition = "time")

m_market <- lm(market~factor(time),df1,weights = ponderador02,subset = time %in% c(1,3,5))
plot_predictions(m_market, condition = "time")

df_market<- 
bind_rows(
plot_predictions(m_educ, condition = "time",draw = F) %>% mutate(class="1. Education"),
plot_predictions(m_salud, condition = "time",draw = F)%>% mutate(class="2. Health"),
plot_predictions(m_pension, condition = "time",draw = F)%>% mutate(class="3. Pensions")
)

ggplot(df_market,aes(x=time,y=estimate,group=class,color=class,ymin = conf.low, ymax = conf.high)) +  
  geom_line(size=0.7) +
  geom_pointrange(size=0.5) +
  labs(y=NULL,x=NULL) +
  scale_x_discrete(labels=c("2016","2018","2021*"))+
  scale_y_continuous(limits = c(1,5),labels=stringr::str_wrap(labels[[1]],10)) +
  theme(legend.title = element_blank(),legend.position = c(0.7,0.7,1,1))
```


# Correlations by wave 
```{r}
df1 %>% 
  # filter(time==1) %>% 
  select(just_educ,just_salud,just_pension,
         porc_low,porc_middle,porc_high,
         diversityclass
         ) %>% 
  sjPlot::tab_corr(triangle = "upper",digits = 2,
           var.labels = c("Education","Health","Pensions",
                          "% Low","% Medium", "% High",
                          "Diversity"))


df1 %>% 
  # filter(time==1) %>% 
  select(just_educ,just_salud,just_pension,
         risk_avg,
         diversityclass
         ) %>% 
  sjPlot::tab_corr(triangle = "upper",digits = 2)


df1 %>% 
  select(just_educ,just_salud,just_pension,
         porc_low,porc_middle,porc_high,
         diversityclass
         ) %>% 
  mutate(just_educ=as.factor(just_educ),
         just_salud=as.factor(just_salud),
         just_pension=as.factor(just_pension))
```

# OLS 

- Ponderador02 funciona mejor

```{r justeduc}
models <- 
list(
lm(just_educ ~ time , data = df1,subset = time==1,weights = ponderador02),
lm(just_educ ~ time + diversityclass,data=df1,subset = time==1,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income,data=df1,subset = time==1,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ ,data=df1,subset = time==1,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==1,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==1,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==1,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==1,weights = ponderador02)

)
screenreg(models, use.ci = F)

models <- 
list(
lm(just_educ ~ time , data = df1,subset = time==3,weights = ponderador02),
lm(just_educ ~ time + diversityclass,data=df1,subset = time==3,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income,data=df1,subset = time==3,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ ,data=df1,subset = time==3,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==3,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==3,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==3,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==3,weights = ponderador02)
)
screenreg(models, use.ci = F)

models <- 
list(
lm(just_educ ~ time , data = df1,subset = time==5,weights = ponderador02),
lm(just_educ ~ time + diversityclass,data=df1,subset = time==5,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income,data=df1,subset = time==5,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ ,data=df1,subset = time==5,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==5,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==5,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==5,weights = ponderador02),
lm(just_educ ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==5,weights = ponderador02)
)
screenreg(models, use.ci = F)
```

```{r justsalud}
models <- 
list(
lm(just_salud ~ time , data = df1,subset = time==1,weights = ponderador02),
lm(just_salud ~ time + diversityclass,data=df1,subset = time==1,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income,data=df1,subset = time==1,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ ,data=df1,subset = time==1,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==1,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==1,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==1,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==1,weights = ponderador02)

)
screenreg(models, use.ci = F)

models <- 
list(
lm(just_salud ~ time , data = df1,subset = time==3,weights = ponderador02),
lm(just_salud ~ time + diversityclass,data=df1,subset = time==3,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income,data=df1,subset = time==3,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ ,data=df1,subset = time==3,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==3,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==3,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==3,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==3,weights = ponderador02)
)
screenreg(models, use.ci = F)

models <- 
list(
lm(just_salud ~ time , data = df1,subset = time==5,weights = ponderador02),
lm(just_salud ~ time + diversityclass,data=df1,subset = time==5,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income,data=df1,subset = time==5,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ ,data=df1,subset = time==5,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==5,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==5,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==5,weights = ponderador02),
lm(just_salud ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==5,weights = ponderador02)
)
screenreg(models, use.ci = F)
```

```{r justpension}
models <- 
list(
lm(just_pension ~ time , data = df1,subset = time==1,weights = ponderador02),
lm(just_pension ~ time + diversityclass,data=df1,subset = time==1,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income,data=df1,subset = time==1,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ ,data=df1,subset = time==1,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==1,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==1,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==1,weights = ponderador02)
)
screenreg(models, use.ci = F)

models <- 
list(
lm(just_pension ~ time , data = df1,subset = time==3,weights = ponderador02),
lm(just_pension ~ time + diversityclass,data=df1,subset = time==3,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income,data=df1,subset = time==3,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ ,data=df1,subset = time==3,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==3,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==3,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==3,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==3,weights = ponderador02)
)
screenreg(models, use.ci = F)

models <- 
list(
lm(just_pension ~ time , data = df1,subset = time==5,weights = ponderador02),
lm(just_pension ~ time + diversityclass,data=df1,subset = time==5,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income,data=df1,subset = time==5,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ ,data=df1,subset = time==5,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==5,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==5,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==5,weights = ponderador02),
lm(just_pension ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==5,weights = ponderador02)
)
screenreg(models, use.ci = F)
```

```{r market2}
models <- 
list(
lm(market2 ~ time , data = df1,subset = time==1,weights = ponderador02),
lm(market2 ~ time + diversityclass,data=df1,subset = time==1,weights = ponderador02),
lm(market2 ~ time + diversityclass+income,data=df1,subset = time==1,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ ,data=df1,subset = time==1,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==1,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==1,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==1,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==1,weights = ponderador02)

)
screenreg(models, use.ci = F)

models <- 
list(
lm(market2 ~ time , data = df1,subset = time==3,weights = ponderador02),
lm(market2 ~ time + diversityclass,data=df1,subset = time==3,weights = ponderador02),
lm(market2 ~ time + diversityclass+income,data=df1,subset = time==3,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ ,data=df1,subset = time==3,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==3,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==3,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==3,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==3,weights = ponderador02)
)
screenreg(models, use.ci = F)

models <-
list(
lm(market2 ~ time , data = df1,subset = time==5,weights = ponderador02),
lm(market2 ~ time + diversityclass,data=df1,subset = time==5,weights = ponderador02),
lm(market2 ~ time + diversityclass+income,data=df1,subset = time==5,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ ,data=df1,subset = time==5,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==5,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==5,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==5,weights = ponderador02),
lm(market2 ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==5,weights = ponderador02)
)
screenreg(models, use.ci = F)
```

```{r market}
models <- 
list(
lm(market ~ time , data = df1,subset = time==1,weights = ponderador02),
lm(market ~ time + diversityclass,data=df1,subset = time==1,weights = ponderador02),
lm(market ~ time + diversityclass+income,data=df1,subset = time==1,weights = ponderador02),
lm(market ~ time + diversityclass+income+educ ,data=df1,subset = time==1,weights = ponderador02),
lm(market ~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==1,weights = ponderador02),
lm(market ~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==1,weights = ponderador02),
lm(market ~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==1,weights = ponderador02),
lm(market ~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==1,weights = ponderador02)

)
screenreg(models, use.ci = F)

models <- 
list(
lm(market~ time , data = df1,subset = time==3,weights = ponderador02),
lm(market~ time + diversityclass,data=df1,subset = time==3,weights = ponderador02),
lm(market~ time + diversityclass+income,data=df1,subset = time==3,weights = ponderador02),
lm(market~ time + diversityclass+income+educ ,data=df1,subset = time==3,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==3,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==3,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==3,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==3,weights = ponderador02)
)
screenreg(models, use.ci = F)

models <-
list(
lm(market~ time , data = df1,subset = time==5,weights = ponderador02),
lm(market~ time + diversityclass,data=df1,subset = time==5,weights = ponderador02),
lm(market~ time + diversityclass+income,data=df1,subset = time==5,weights = ponderador02),
lm(market~ time + diversityclass+income+educ ,data=df1,subset = time==5,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex,data=df1,subset = time==5,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex+class+n_total,data=df1,subset = time==5,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex+class+diversityclass*n_total,data=df1,subset = time==5,weights = ponderador02),
lm(market~ time + diversityclass+income+educ+age+sex+class*diversityclass+n_total,data=df1,subset = time==5,weights = ponderador02)
)
screenreg(models, use.ci = F)
```



# inequality perception

```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
rm(list=ls())
# load(here::here("input/data/proc/study2.RData"))
load(here::here("input/data/proc/study2_context.RData")); elsoc_long<- elsoc_long_context
pacman::p_load(correlation,lme4,plm,panelr,texreg,dplyr,estimatr,marginaleffects,ggplot2,sjmisc,MLMusingR)  
dfreg <-
elsoc_long %>%
  group_by(idencuesta) %>%
  mutate(just_educ = if_else(ola == 5 & is.na(just_educ), last(just_educ[ola == 6]), just_educ),
         just_salud = if_else(ola == 5 & is.na(just_salud), last(just_salud[ola == 6]), just_salud),
         just_pension = if_else(ola == 5 & is.na(just_pension), last(just_pension[ola == 6]), just_pension),
         c05_06 = if_else(ola == 5 & is.na(c05_06), last(c05_06[ola == 6]), c05_06)) %>%
  ungroup()

dfreg$market<- rowMeans(dfreg[,c("just_educ","just_salud","just_pension")],na.rm = T)
# dfreg$market <- ((dfreg$market-min(dfreg$market,na.rm = T))/(max(dfreg$market,na.rm = T)-min(dfreg$market,na.rm = T)))*100
sjlabelled::set_label(dfreg$market) <- "Market-based distribution of social services (3 items)"
dfreg$market2<- rowMeans(dfreg[,c("just_educ","just_salud")],na.rm = T)
# dfreg$market2 <- ((dfreg$market2-min(dfreg$market2,na.rm = T))/(max(dfreg$market2,na.rm = T)-min(dfreg$market2,na.rm = T)))*100
sjlabelled::set_label(dfreg$market2) <- "Market-based distribution of social services (2 items)"

dfreg$N_high<- (dfreg$num_high*(dfreg$num_high-1))/(dfreg$n_total*(dfreg$n_total-1));summary(dfreg$N_high)
dfreg$N_middle<- (dfreg$num_middle*(dfreg$num_middle-1))/(dfreg$n_total*(dfreg$n_total-1));summary(dfreg$N_middle)
dfreg$N_low<- (dfreg$num_low*(dfreg$num_low-1))/(dfreg$n_total*(dfreg$n_total-1));summary(dfreg$N_low)

dfreg$blau_b <- 1-rowSums(dfreg[,c("N_high","N_middle","N_low")],na.rm = T);summary(dfreg$blau_b)
dfreg$blau_b <- ifelse(dfreg$num_high==0 & dfreg$num_middle==0 & dfreg$num_low==0,yes = NA,no = dfreg$blau_b)
dfreg$blau_b <- ifelse(dfreg$n_total==1,yes = 0,no = dfreg$blau_b)

df1 <-  
dfreg %>%
  filter(ola %in% c(1,3,5)) %>%
  filter(n_total>=2) %>% 
  select(id="idencuesta",ola,
         # diversityclass=diversity,
         # diversityclass=iqv,
         # diversityclass=crossclass,
         # diversityclass=homclass,
         # diversityclass=porc_low,
         # diversityclass=porc_middle,
         # diversity,
         # iqvclass,
         # iqv,
         # diversityclass,
         # diversityclass=diversitypca,
         diversityclass=diversitycfa,
         # diversityclass=blau_b,
         # diversityclass= homiseiratio,
         # diversitypca,
         # porc_low,
         # porc_middle,
         # porc_high,
         # diversitypca,
         # starts_with("ps_"),
         income=incomegrp,
         educ=educ,
         class=egp8_hh_label_na,
         # class=egp8_hh_label,
         # class=esec6_hh_label_na,
         age=m0_edad,
         sexo,
         perineq,
         # effort,talent,
         # marketrust=c05_06,
         # n_total,
         weights1=ponderador_long_total,
         ponderador01,ponderador02,
         # accs=accsciu,
         segr=segrciu,
         nse=pobreciu,
         gini=giniciu,
         cluster=ciudad
         ) %>% 
  arrange(ola) %>% 
  na.omit()
table(df1$ola);df1$time <- df1$ola;df1$ola <- NULL
dim(df1)
```


```{r}
models <- 
list(
lmer(perineq ~ time +(1| id), data = df1,weights = weights1),
lmer(perineq ~ time + diversityclass+ (1|id),data=df1,weights = weights1),
lmer(perineq ~ time + diversityclass+income+(1|id),data=df1,weights = weights1),
lmer(perineq ~ time + diversityclass+income+educ +(1|id),data=df1,weights = weights1),
lmer(perineq ~ time + diversityclass+income+educ+age+sexo+(1|id),data=df1,weights = weights1),
lmer(perineq ~ time + diversityclass+income+educ+age+sexo+class+(1|id),data=df1,weights = weights1)
)
screenreg(models, use.ci = F)
```


# just salary CEO

```{r}
models <- 
list(
lmer(justgerlog ~ time +(1| id), data = df1,weights = weights1),
lmer(justgerlog ~ time + diversityclass+ (1|id),data=df1,weights = weights1),
lmer(justgerlog ~ time + diversityclass+income+(1|id),data=df1,weights = weights1),
lmer(justgerlog ~ time + diversityclass+income+educ +(1|id),data=df1,weights = weights1),
lmer(justgerlog ~ time + diversityclass+income+educ+age+sexo+(1|id),data=df1,weights = weights1),
lmer(justgerlog ~ time + diversityclass+income+educ+age+sexo+class+(1|id),data=df1,weights = weights1),
lmer(justgerlog ~ time + diversityclass+income+educ+age+sexo+class+n_total+(1|id),data=df1,weights = weights1),
lmer(justgerlog ~ time + diversityclass+income+educ+age+sexo+class*diversityclass+(diversityclass|id),data=df1,weights = weights1)
)
screenreg(models, use.ci = F)
```

# just salary worker

```{r}
models <- 
list(
lmer(justobrlog ~ time +(1| id), data = df1,weights = weights1),
lmer(justobrlog ~ time + diversityclass+ (1|id),data=df1,weights = weights1),
lmer(justobrlog ~ time + diversityclass+income+(1|id),data=df1,weights = weights1),
lmer(justobrlog ~ time + diversityclass+income+educ +(1|id),data=df1,weights = weights1),
lmer(justobrlog ~ time + diversityclass+income+educ+age+sexo+(1|id),data=df1,weights = weights1),
lmer(justobrlog ~ time + diversityclass+income+educ+age+sexo+class+(1|id),data=df1,weights = weights1),
lmer(justobrlog ~ time + diversityclass+income+educ+age+sexo+class+n_total+(1|id),data=df1,weights = weights1),
lmer(justobrlog ~ time + diversityclass+income+educ+age+sexo+class*diversityclass+(diversityclass|id),data=df1,weights = weights1)
)
screenreg(models, use.ci = F)
```


# Pro-social behavior

```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
rm(list=ls())
# load(here::here("input/data/proc/study2.RData"))
load(here::here("input/data/proc/study2_context.RData")); elsoc_long<- elsoc_long_context
pacman::p_load(correlation,lme4,plm,panelr,texreg,dplyr,estimatr,marginaleffects,ggplot2,sjmisc,MLMusingR)  
dfreg <-
elsoc_long %>%
  group_by(idencuesta) %>%
  mutate(just_educ = if_else(ola == 5 & is.na(just_educ), last(just_educ[ola == 6]), just_educ),
         just_salud = if_else(ola == 5 & is.na(just_salud), last(just_salud[ola == 6]), just_salud),
         just_pension = if_else(ola == 5 & is.na(just_pension), last(just_pension[ola == 6]), just_pension),
         c05_06 = if_else(ola == 5 & is.na(c05_06), last(c05_06[ola == 6]), c05_06)) %>%
  ungroup()

dfreg$market<- rowMeans(dfreg[,c("just_educ","just_salud","just_pension")],na.rm = T)
# dfreg$market <- ((dfreg$market-min(dfreg$market,na.rm = T))/(max(dfreg$market,na.rm = T)-min(dfreg$market,na.rm = T)))*100
sjlabelled::set_label(dfreg$market) <- "Market-based distribution of social services (3 items)"
dfreg$market2<- rowMeans(dfreg[,c("just_educ","just_salud")],na.rm = T)
# dfreg$market2 <- ((dfreg$market2-min(dfreg$market2,na.rm = T))/(max(dfreg$market2,na.rm = T)-min(dfreg$market2,na.rm = T)))*100
sjlabelled::set_label(dfreg$market2) <- "Market-based distribution of social services (2 items)"


df1 <-  
dfreg %>%
  filter(ola %in% c(1,3,5)) %>%
  select(id="idencuesta",ola,
         # diversityclass=diversity,
         # diversityclass=iqv,
         # diversityclass=crossclass,
         # diversityclass=homclass,
         # diversityclass=porc_low,
         # diversityclass=porc_middle,
         # diversity,
         # iqvclass,
         # iqv,
         # diversityclass,
         # diversityclass=diversitypca,
         diversityclass=diversitycfa,
         # diversityclass= homiseiratio,
         # diversitypca,
         # porc_low,
         # porc_middle,
         # porc_high,
         # diversitypca,
         starts_with("ps_"),
         income=incomegrp,
         educ=educ,
         class=egp8_hh_label_na,
         # class=egp8_hh_label,
         # class=esec6_hh_label_na,
         age=m0_edad,
         sexo,
         # perineq,
         # effort,talent,
         # marketrust=c05_06,
         n_total,
         weights1=ponderador_long_total,
         ponderador01,ponderador02,
         # accs=accsciu,
         segr=segrciu,
         nse=pobreciu,
         gini=giniciu,
         cluster=ciudad
         ) %>% 
  arrange(ola) %>% 
  mutate(
    # n_total=scale(as.numeric(n_total)),
         # class=factor(ntile(class,3),levels=c(1,2,3),labels = c("isei_low","isei_medium","isei_high")),
         # class=ifelse(is.na(class),"isei_na",class)
          # accs=factor(ntile(accs,3)),
         ) %>%
  na.omit()
# df1$class<- forcats::fct_rev(df1$class)
table(df1$ola);df1$time <- df1$ola;df1$ola <- NULL
dim(df1)


# idfreq<- frq(df1$id) %>% data.frame() %>% select(val,frq)
# filter<- idfreq %>% filter(frq>=3)
# df1 <- df1 %>% filter(id %in% filter$val)
```

```{r}
pssocial <- 
df1 %>% 
  # filter(time==5) %>% 
  select(starts_with("ps_"))   

for (i in names(pssocial)) {
  pssocial[[i]] <- factor(x = pssocial[[i]])
}

cormat<- polycor::hetcor(pssocial,parallel = T)
corrplot::corrplot.mixed(cormat$correlations)


pssocial_1 <- 
df1 %>% 
  filter(time==1) %>%
  select(id,starts_with("ps_"))  

pssocial_3 <- 
df1 %>% 
  filter(time==3) %>%
  select(id,starts_with("ps_"))  

pssocial_5 <- 
df1 %>% 
  filter(time==5) %>%
  select(id,starts_with("ps_"))  


prosocial_wide <- left_join(pssocial_1,pssocial_3,by="id",suffix = c("_w1","_w3"))


prosocial_wide <- left_join(prosocial_wide,pssocial_5,by="id")


for (i in names(prosocial_wide)) {
  prosocial_wide[[i]] <- factor(x = prosocial_wide[[i]])
}

cormat <-
  prosocial_wide %>% select(starts_with("ps_mone"),starts_with("ps_dona"),starts_with("ps_volu")) %>%
  # na.omit() %>% 
  polycor::hetcor(parallel = T,use = "pairwise.complete.obs")
corrplot::corrplot.mixed(cormat$correlations)

df1$psocial<- rowMeans(df1[,c("ps_mone","ps_dona","ps_volu")],na.rm = T)
```


```{r ps_mone}
models <- 
list( 
lmer(ps_mone ~ time +(1| id), data = df1),
lmer(ps_mone ~ time + diversityclass+ (1|id),data=df1),
lmer(ps_mone ~ time + diversityclass+income+(1|id),data=df1),
lmer(ps_mone ~ time + diversityclass+income+educ +(1|id),data=df1),
lmer(ps_mone ~ time + diversityclass+income+educ+age+sexo+(1|id),data=df1),
lmer(ps_mone ~ time + diversityclass+income+educ+age+sexo+n_total+(1|id),data=df1),
lmer(ps_mone ~ time + diversityclass+income+educ+age+sexo+n_total+class+(1|id),data=df1)
)
screenreg(models)
```

```{r ps_dona}
models <- 
list( 
lmer(ps_dona ~ time +(1| id), data = df1),
lmer(ps_dona ~ time + diversityclass+ (1|id),data=df1),
lmer(ps_dona ~ time + diversityclass+income+(1|id),data=df1),
lmer(ps_dona ~ time + diversityclass+income+educ +(1|id),data=df1),
lmer(ps_dona ~ time + diversityclass+income+educ+age+sexo+(1|id),data=df1),
lmer(ps_dona ~ time + diversityclass+income+educ+age+sexo+n_total+(1|id),data=df1),
lmer(ps_dona ~ time + diversityclass+income+educ+age+sexo+n_total+class+(1|id),data=df1),

)
screenreg(models)
```

```{r ps_volu}
models <- 
list( 
lmer(ps_volu ~ time +(1| id), data = df1),
lmer(ps_volu ~ time + diversityclass+ (1|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+(1|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ +(1|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+(1|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+n_total+(1|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+n_total+class+(1|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+n_total+class+perineq+(1|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+n_total+class+perineq+(diversityclass|id),data=df1) 
,
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+n_total+perineq+income*time+(time|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+n_total+perineq+educ*time+(time|id),data=df1),
lmer(ps_volu ~ time + diversityclass+income+educ+age+sexo+n_total+perineq+class*time+(time|id),data=df1)
)
screenreg(models)
```

```{r pssocial}
models <- 
list( 
lmer(psocial ~ time +(1| id), data = df1),
lmer(psocial ~ time + diversityclass+ (1|id),data=df1),
lmer(psocial ~ time + diversityclass+income+(1|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ +(1|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+(1|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+n_total+(1|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+n_total+class+(1|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+n_total+class+perineq+(1|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+n_total+class+perineq+(diversityclass|id),data=df1) 
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+n_total+perineq+income*time+(time|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+n_total+perineq+educ*time+(time|id),data=df1),
lmer(psocial ~ time + diversityclass+income+educ+age+sexo+n_total+perineq+class*time+(time|id),data=df1)
)
screenreg(models)
```



```{descr-status}
elsoc_long$homiseiratio<- as.numeric(elsoc_long$isei08res/elsoc_long$isei_avg)

df_network_change <- 
elsoc_long %>% 
  filter(ola_w01==1) %>%
  group_by(esec8_hh_label_na,ola) %>% 
  summarise(
    # isei_avg.w=weighted.mean(isei_avg,na.rm = T,w=ponderador_long_total),
    # isei_avg=mean(isei_avg,na.rm = T),
    # diversity.w=weighted.mean(diversity,na.rm = T,w=ponderador_long_total),
    # diversity=mean(diversity,na.rm = T),
    # iqvclass.w=weighted.mean(iqvclass,na.rm = T,w=ponderador_long_total),
    # iqvclass=mean(iqvclass,na.rm = T),
    # diversitypca.w=weighted.mean(diversitypca,na.rm = T,w=ponderador_long_total),
    # homisei.w=weighted.mean(homisei,na.rm = T,w=ponderador_long_total),    
    # homiseiratio.w=weighted.mean(homiseiratio,na.rm = T,w=ponderador_long_total),
    homclass.w=weighted.mean(homclass,na.rm = T,w=ponderador_long_total)
    ) %>% 
  na.omit()

df_network_change$ola <- factor(df_network_change$ola,labels = c("2016","2018","2022"))

df_network_change %>% 
ggplot(aes(x = ola,y = isei_avg.w,shape=egp8_hh_label,color=egp8_hh_label,group=egp8_hh_label,
                 ))+
  geom_point(size=4, alpha=2) +
  geom_line(size=1)+
  scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network Prestige (ISEI)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())


df_network_change %>% 
ggplot(aes(x = ola,y = diversity.w,shape=egp8_hh_label,color=egp8_hh_label,group=egp8_hh_label,
                 ))+
  geom_point(size=3, alpha=2) +
  geom_line(size=1)+
  # scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network Diversity - occupations (Blau Index)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())


df_network_change %>% 
ggplot(aes(x = ola,y = iqvclass,shape=egp8_hh_label,color=egp8_hh_label,group=egp8_hh_label,
                 ))+
  geom_point(size=3, alpha=2) +
  geom_line(size=1)+
  # scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network Diversity - status groups (Blau Index)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())


df_network_change %>% 
ggplot(aes(x = ola,y = diversitypca.w,shape=egp8_hh_label,color=egp8_hh_label,group=egp8_hh_label,
                 ))+
  geom_point(size=3, alpha=2) +
  geom_line(size=1)+
  # scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network Diversity (Otero & Mendoza, 2023)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())



df_network_change %>% 
ggplot(aes(x = ola,y = homisei.w,shape=egp8_hh_label_na,color=egp8_hh_label,group=egp8_hh_label,
                 ))+
  geom_point(size=3, alpha=2) +
  geom_line(size=1)+
  # scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network homogeneisty abs(ISEI - ISEI network)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())

df_network_change %>% 
  filter(ola=="2016") %>% 
ggplot(aes(x = egp8_hh_label_na,y = homisei.w,group=egp8_hh_label_na,
                 ))+
  geom_point(size=3, alpha=2) +
  geom_line(size=1)+
  # scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network homogeneisty (ISEI - ISEI network)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())


df_network_change %>% 
  filter(ola=="2016") %>% 
ggplot(aes(x = esec8_hh_label_na,y = homiseiratio.w,group=esec8_hh_label_na,
                 ))+
  geom_point(size=3, alpha=2) +
  geom_line(size=1)+
  # scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network homogeneisty (ISEI/ISEI network)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())


df_network_change %>% 
  filter(ola=="2018") %>%
ggplot(aes(x = esec8_hh_label_na,y = homclass.w,group=esec8_hh_label_na))+
  geom_point(size=3, alpha=2) +
  geom_line(size=1)+
  # scale_shape_manual(values = c(15,16,17,18,19)) +
  labs(x="Year",y="Network homogeneity (Class-based)") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x=element_text(angle=45,hjust = 1,size=8),
        legend.title = element_blank())

```


```{r}
#https://data.oecd.org/healthres/health-spending.htm
library(ggplot2)

# Create the data frame
data <- data.frame(
  Country = c("Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", 
              "Costa Rica", "Czechia", "Denmark", "Estonia", "Finland", "France", 
              "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Israel", 
              "Italy", "Japan", "Korea", "Latvia", "Lithuania", "Luxembourg", 
              "Mexico", "Netherlands", "Norway", "Poland", "Portugal", 
              "Slovak Republic", "Slovenia", "Spain", "Sweden", "Switzerland", 
              "Türkiye", "United Kingdom", "United States"),
  Value = c(1.593, 1.791, 1.972, 1.66, 2.681, 1.233, 1.57, 1.208, 1.228, 1.534, 
            1.65, 1.098, 1.394, 3.057, 1.863, 1.28, 0.648, 1.565, 1.929, 1.256, 
            2.726, 2.441, 2.25, 0.481, 2.515, 0.998, 1.394, 1.201, 3.038, 1.504, 
            1.123, 2.255, 1.401, 2.628, 0.743, 1.578, 1.858)
)

# Order the Country factor by Value
data$Country <- factor(data$Country, levels = data$Country[order(data$Value)])

# Create the plot using ggplot2
ggplot(data, aes(x = Country, y = Value)) +
  geom_bar(stat = "identity", aes(fill = Country == "Chile")) +
  scale_fill_manual(values = c("TRUE" = "red", "FALSE" = "grey"),) +
  coord_flip() +
  labs(title = "Health spending: Out-of-pocket",
       subtitle = "borne directly by a patient where neither compulsory nor voluntary\ninsurance cover thefull cost of the health good or service",
       x = "",
       y = "% of GDP",
       caption = "Source: OECD, 2020 or latest available") +
  scale_y_continuous(labels = scales::percent_format(scale = 1,)) +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
#https://data.oecd.org/eduresource/private-spending-on-education.htm
# Load necessary packages
library(ggplot2)

# Create the data frame with the new data
data <- data.frame(
  Country = c("Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", 
              "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", 
              "Greece", "Hungary", "Iceland", "Ireland", "Israel", "Italy", 
              "Japan", "Korea", "Latvia", "Lithuania", "Luxembourg", "Mexico", 
              "Netherlands", "New Zealand", "Norway", "Poland", "Portugal", 
              "Slovak Republic", "Slovenia", "Spain", "Sweden", "Türkiye", 
              "United Kingdom", "United States"),
  Value = c(1.859, 0.312, 0.343, 1.425, 2.257, 2.045, 0.440, 0.417, 0.349, 
            0.090, 0.741, 0.559, 0.326, 0.629, 0.255, 0.479, 1.013, 0.516, 
            1.076, 1.069, 0.622, 0.453, 0.104, 0.828, 0.967, 1.052, 0.278, 
            0.590, 0.845, 0.497, 0.432, 0.903, 0.189, 1.214, 2.029, 1.852)
)
# Order the Country factor by Value
data$Country <- factor(data$Country, levels = data$Country[order(data$Value)])

# Create the plot using ggplot2
ggplot(data, aes(x = Country, y = Value)) +
  geom_bar(stat = "identity", aes(fill = Country == "Chile")) +
  scale_fill_manual(values = c("TRUE" = "red", "FALSE" = "grey")) +
  coord_flip() +
  labs(title = "Private spending on education: Primary to tertiary",
       x = "",
       y = "% of GDP",
       subtitle = "refers to expenditure funded by private sources which are\nhouseholds and other private entities",
       caption = "Source: OECD, 2020 or latest available") +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_y_continuous(labels = scales::percent_format(scale = 1))
```


```{r }
# Create the data frame
dataframe1 <- data.frame(
  Country = c("Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", 
              "Costa Rica", "Czechia", "Denmark", "Estonia", "Finland", "France", 
              "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Israel", 
              "Italy", "Japan", "Korea", "Latvia", "Lithuania", "Luxembourg", 
              "Mexico", "Netherlands", "New Zealand", "Norway", "Poland", 
              "Portugal", "Slovak Republic", "Slovenia", "Spain", "Sweden", 
              "Switzerland", "Türkiye", "United Kingdom", "United States"),
  Value = c(4.288, 12.998, 10.690, 5.271, 3.097, 5.618, 5.901, 7.892, 8.127, 
            6.567, 11.944, 14.486, 10.383, 15.651, 7.611, 2.860, 3.315, 4.587, 
            15.911, 9.666, 3.611, 6.837, 6.408, 8.655, 3.072, 4.962, 5.139, 
            7.092, 10.925, 12.428, 7.147, 10.012, 11.290, 6.983, 6.416, 7.545, 
            5.114, 7.494),
  source=c("Public")
)

# Create the data frame
dataframe2 <- data.frame(
  Country = c("Australia", "Austria", "Canada", "Chile", "Costa Rica", 
              "Czechia", "Denmark", "Estonia", "France", "Germany", 
              "Hungary", "Iceland", "Italy", "Korea", "Latvia", "Lithuania", 
              "Luxembourg", "Mexico", "Netherlands", "Norway", "Poland", 
              "Portugal", "Slovak Republic", "Slovenia", "Spain", 
              "Switzerland", "Türkiye", "United Kingdom", "United States"),
  Value = c(6.852, 0.274, 4.852, 2.521, 0.862, 0.457, 5.105, 0.064, 0.794, 
            0.252, 0.108, 7.400, 0.398, 3.877, 2.042, 0.074, 0.181, 0.480, 
            3.949, 1.439, 0.000, 1.787, 0.137, 0.193, 0.667, 5.672, 0.058, 
            3.058, 7.057),
  source=("Private")
)



# Print the data frame
dataframe1$Country <- factor(dataframe1$Country, levels = dataframe1$Country[order(dataframe1$Value)])



dfpensiones<- bind_rows(dataframe1,dataframe2)
dfpensiones$Country <- factor(dfpensiones$Country, levels = dfpensiones$Country[order(dataframe1$Country)])
dfpensiones$highlight <-  ifelse(dfpensiones$Country=="Chile",yes = TRUE,no = FALSE)

dfpensiones$a <- ifelse(dfpensiones$Country=="Chile","red","black")

a<- c(rep("black",2),"red",rep("black",35))
b<- c(rep("plain",2),"bold",rep("plain",35))
c<- c(rep(10,2),"14",rep(10,35))


ggplot(dfpensiones, aes(x=Country, y=Value, color=source,shape=source)) +
  geom_segment(aes(x=Country, xend=Country, y=0, yend=Value),
               alpha=ifelse(dfpensiones$highlight==TRUE,2,0.5),
               size=ifelse(dfpensiones$highlight==TRUE,1,0.5)) +
  geom_point(size=ifelse(dfpensiones$highlight==TRUE,3.5,2),
             alpha=ifelse(dfpensiones$highlight==TRUE,2,0.7)
             ) +
  scale_shape_manual(values=c(15,16))+
  theme_light() +
  coord_flip() +
  labs(title = "Pension spending: Public / Private % of GDP",
       x = "",
       y = "% of GDP",
       subtitle = "Pension spending is defined as all cash expenditures\n(including lump-sum payments) on old-age and survivors pensions",
       caption = "Source: OECD, 2021 or latest available") +
  theme(
    panel.grid.major.y = element_blank(),legend.position = "bottom",
    panel.border = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(angle = 0, colour = a,face = b,size = c))
```

