---
title: "Análisis de datos"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
rm(list=ls())
# load(here::here("input/data/proc/study2.RData"))
load(here::here("input/data/proc/study2.RData")); elsoc_long<- elsoc_long
pacman::p_load(correlation,lme4,plm,panelr,texreg,dplyr,estimatr,marginaleffects,ggplot2,sjmisc,MLMusingR,ordinal)  
dfreg <-
elsoc_long %>%
  group_by(idencuesta) %>%
  mutate(just_educ = if_else(ola == 5 & is.na(just_educ), last(just_educ[ola == 6]), just_educ),
         just_salud = if_else(ola == 5 & is.na(just_salud), last(just_salud[ola == 6]), just_salud),
         just_pension = if_else(ola == 5 & is.na(just_pension), last(just_pension[ola == 6]), just_pension)
         ) %>%
  ungroup()

dfreg$market<- rowMeans(dfreg[,c("just_educ","just_salud","just_pension")],na.rm = T)
dfreg$market <- ((dfreg$market-min(dfreg$market,na.rm = T))/(max(dfreg$market,na.rm = T)-min(dfreg$market,na.rm = T)))*100
sjlabelled::set_label(dfreg$market) <- "Market-based distribution of social services (3 items)"

dfreg$just_educ <- ((dfreg$just_educ-min(dfreg$just_educ,na.rm = T))/(max(dfreg$just_educ,na.rm = T)-min(dfreg$just_educ,na.rm = T)))*100
dfreg$just_salud <- ((dfreg$just_salud-min(dfreg$just_salud,na.rm = T))/(max(dfreg$just_salud,na.rm = T)-min(dfreg$just_salud,na.rm = T)))*100
dfreg$just_pension <- ((dfreg$just_pension-min(dfreg$just_pension,na.rm = T))/(max(dfreg$just_pension,na.rm = T)-min(dfreg$just_pension,na.rm = T)))*100

dfreg$cpi <- dfreg$ola
dfreg$cpi <- car::recode(dfreg$cpi,"1=97.37;2=97.75;3=97.47;4=97.09;5=100")
dfreg$real_income <- as.numeric((dfreg$ing_pc/dfreg$cpi)* 100)
dfreg$real_income_eq <- as.numeric((dfreg$ing_pc_eq/dfreg$cpi)* 100)
summary(dfreg$real_income)
summary(dfreg$real_income_eq)

dfreg$ing_pc_100 <- (dfreg$real_income_eq) # each unit is 100.000 CLP
dfreg$percentile <- ntile(dfreg$ing_pc_100,100)


# dfreg$ing_pc_100 <- (dfreg$real_income) # each unit is 100.000 CLP
# dfreg$ing_pc_100 <- (dfreg$ing_pc_eq/100000) # each unit is 100.000 CLP
dfreg$isei4res <- factor(ntile(dfreg$isei08res,4))
# dfreg$isei4res_imputed <- factor(ntile(dfreg$isei08res_imputed,4))
dfreg$isei3 <- factor(ntile(dfreg$isei08res,3))
# dfreg$isei3_imputed <- factor(ntile(dfreg$isei08res_imputed,3))
# dfreg$isei08res_imputed <- as.numeric(dfreg$isei08res_imputed)
dfreg$isei3res_na <- factor(ifelse(is.na(dfreg$isei3),yes = 99,no = dfreg$isei3))

frq(as.numeric(dfreg$educ))
dfreg$univ <- car::recode(as.numeric(dfreg$educ),"5=1;1:4=0")
dfreg$class8 <- car::recode(as.numeric(dfreg$egp8_r_label_na.x),"1:2='1Service Class';3:4='2Routine nonmanual';5='3Self-employed';6:9='4Working Class';10:11='5Unemployed and Retired'",as.factor = T)
dfreg$class8 <- relevel(x = dfreg$class8,ref = '4Working Class')

dfreg$isei_cv <- (dfreg$isei_sd/dfreg$isei_avg)*100

summary(dfreg$isei_cv)



dfreg$isei_avg_grp <- car::recode(dfreg$isei_avg,"16:34=1;34.01:54=2;54.01:88=3")
frq(dfreg$isei_avg_grp)

df1_long <-
dfreg %>%
# filter(muestra==1) %>%
select(idencuesta,ola,muestra,isei_avg,isei_avg_grp,porc_low,porc_middle,porc_high)


df1_long <- df1_long %>%
  mutate(category = case_when(
    porc_low > porc_middle & porc_low > porc_high ~ "1Low",
    porc_middle > porc_low & porc_middle > porc_high ~ "3Middle",
    porc_high > porc_low & porc_high > porc_middle ~ "5High",
    porc_low == porc_middle & porc_middle == porc_high ~ "6Equal",
    porc_low == porc_middle & porc_middle > porc_high ~ "2Middle_Low",
    porc_middle == porc_high & porc_middle > porc_low ~ "4Middle_High",
    porc_low == porc_high & porc_low > porc_middle ~ "3Middle"
  ))

df1_long <- df1_long %>%
  mutate(category2 = case_when(
    porc_low > porc_middle & porc_low > porc_high ~ "1Low",
    porc_middle > porc_low & porc_middle > porc_high ~ "2Middle",
    porc_high > porc_low & porc_high > porc_middle ~ "3High",
    porc_low == porc_middle & porc_middle == porc_high ~ "4Equal",
    porc_low == porc_middle & porc_middle > porc_high ~ "2Middle",
    porc_middle == porc_high & porc_middle > porc_low ~ "2Middle",
    porc_low == porc_high & porc_low > porc_middle ~ "2Middle"
  ))

frq(df1_long$category)
frq(df1_long$category2)

elsoc <- panel_data(df1_long, id = idencuesta, wave = ola)
elsoc_wide <- widen_panel(elsoc, separator = "_")
elsoc_wide
View(elsoc_wide)
table(elsoc_wide$category_1,elsoc_wide$category_7)


elsoc_wide$net_mob_grp <- paste0(elsoc_wide$category2_1,elsoc_wide$category2_7)
frq(elsoc_wide$net_mob_grp)

elsoc_wide <- 
elsoc_wide %>% 
 mutate(nw_mobility = case_when(
    grepl("1Low1Low|NA1Low|1LowNA", net_mob_grp) ~ "1Stable Low",
    grepl("2Middle2Middle|NA2Middle|2MiddleNA", net_mob_grp) ~ "2Stable Middle",
    grepl("3High3High|NA3High|3HighNA", net_mob_grp) ~ "3Stable High",
    grepl("1Low2Middle|1Low3High|2Middle3High", net_mob_grp) ~ "4Upward",
    grepl("3High2Middle|3High1Low|2Middle1Low", net_mob_grp) ~ "5Downward",
    grepl("4Equal4Equal|NA4Equal", net_mob_grp) ~ "2Stable Middle", # Assuming Equal is Middle
    TRUE ~ "99Unclassified" # Catch-all for unexpected cases
  ))

frq(elsoc_wide$nw_mobility)

table(elsoc_wide$net_mob_grp,elsoc_wide$nw_mobility)


df_wide<- elsoc_wide %>% select(idencuesta,net_mob_grp,nw_mobility)
df_wide$idencuesta <- as.numeric(as.character(df_wide$idencuesta))
dfreg$idencuesta

dfreg <- left_join(dfreg,y = df_wide,by="idencuesta")



market_mobility<- lmer(market~nw_mobility + (1|idencuesta),data = dfreg)

screenreg(market_mobility)

plot_predictions(market_mobility,condition = "nw_mobility")

```


```{r}
df1 <-  
dfreg %>%
  filter(ola %in% c(1,3,7)) %>%
  filter(muestra==1) %>%
  select(id="idencuesta",ola,muestra,tipo_atricion,
         nw_mobility,
         iqvclass,
         know_total,
         crossclass,
         isei_sd,
         isei_cv,
         isei_range,
         isei_avg,
         n_total,
         just_educ,
         just_salud,
         just_pension,
         market,
         income=real_income_eq,
         isei=isei3res_na,
         # isei=isei08res,
         educ=univ,
         age=m0_edad,
         sex=sexo_fx,
         weights1=ponderador_long_total,
         zona=,
         ) %>%
  mutate(income=log(income)) %>%
  arrange(ola) %>% 
  filter(!is.infinite(income))
table(df1$ola)

summary(df1)

# save(df1,file = here::here("input/data/proc/study2_to-impute.RData"))

# df1_atrition <- df1
df1 <-  df1 %>% filter(!is.infinite(income)) %>% na.omit(df1)
# # fix to complete cases
# idfreq<- frq(df1$id) %>% data.frame() %>% select(val,frq);filter<- idfreq %>% filter(frq>=1);df1 <- df1 %>% filter(id %in% filter$val)

dim(df1)

df1$time <- as.numeric(df1$ola)
table(df1$time)
# # Model w/o isei range
model_wo_range <- 'diversitycfa_norange =~ iqvclass+crossclass+isei_cv+know_total'
fit_range<- lavaan::cfa(model = model_wo_range,data = df1,
                        cluster = "id",
                        sampling.weights = "weights1"
                        )
lavaan::summary(fit_range,standardized=T,fit.measures=T)


# Model using blau, sd, extensivity and number of different "social classes" known (cross-class) is the best

factorscores<- lavaan::lavPredict(fit_range,newdata = df1)
idx <- lavaan::lavInspect(fit_range, "case.idx")
fscores <- lavaan::lavPredict(fit_range)
# loop over factors
for (fs in colnames(fscores)) {
  df1[idx, fs] <- fscores[ , fs]
}

df1 <- df1 %>% rename(diversitycfa=diversitycfa_norange);df1$diversityclass <- df1$diversitycfa
paneldata <- panelr::panel_data(df1, id = id, wave = time)
mean(df1$diversityclass);sd(df1$diversityclass)
summary(df1$diversityclass)

# Diversity index using PCA:
df_pca<- 
paneldata %>% 
  as.data.frame() %>% 
  select(diversityclass,isei_cv,know_total,crossclass)
pca_fit<- psych::pca(r = df_pca,nfactors = 1,rotate = "varimax",scores = T,weight = paneldata$weights1)
paneldata$diversityclass <- as.numeric(pca_fit$scores)
```


```{r}
library(plm) 
library(panelr)
library(estimatr)
library(ordinal)
paneldata137 <- paneldata %>% filter(time %in% c(1,3,7))
paneldata137$diversityclass <- as.numeric(scale(paneldata137$diversityclass))
summary(paneldata137$diversityclass)
paneldata137$market <- scale(paneldata137$market)
paneldata137$income <- scale(paneldata137$income) # "those above their historical average"
paneldata137$educ <- scale(paneldata137$educ) # "those above their historical average"
paneldata137$isei_avg <- scale(paneldata137$isei_avg) # "those above their historical average"
paneldata137$n_total <- scale(paneldata137$n_total) # "those above their historical average"
paneldata137$just_educ <- scale(paneldata137$just_educ)
paneldata137$just_salud <- scale(paneldata137$just_salud)
paneldata137$just_pension <- scale(paneldata137$just_pension)

#test tge haussman indica que es mejor usar FE con two-way 
mkt_educ <- plm(just_educ ~ diversityclass+age+isei+sex,data=paneldata137,weights = weights1,model = "within",effect = "twoway")
mkt_salu <- plm(just_salud ~ diversityclass+age+isei+sex,data=paneldata137,weights = weights1, model="within",effect = "twoway")
mkt_pens <- plm(just_pension ~ diversityclass+age+isei+sex,data=paneldata137,weights = weights1, model="within",effect = "twoway")
services_models_fe <- list(mkt_educ,mkt_salu,mkt_pens)
screenreg(services_models_fe,stars = c(0.001,0.01,0.05,0.1))

mkt_just1_ols <- lm_robust(market ~ diversityclass+age+isei+sex+income+educ+isei_avg+n_total,data=paneldata137,
                           fixed_effects = ~ id,
                          clusters = id,
                          se_type = "CR0",
                          weights = NULL)

# Witihin effects
mkt_just2   <- plm(market ~ isei+age,data=paneldata137,weights = weights1, model="within",effect = "twoways")
mkt_just2.1 <- plm(market ~ diversityclass+age,data=paneldata137,weights = weights1, model="within",effect = "twoways")
mkt_just2.2 <- plm(market ~ diversityclass+isei+age,data=paneldata137,weights = weights1, model="within",effect = "twoways")
mkt_just2.3 <- plm(market ~ diversityclass+isei+isei_avg+n_total+age,data=paneldata137,weights = weights1, model="within",effect = "twoways")
mkt_just2.4 <- plm(market ~ diversityclass+isei+income+educ+age,data=paneldata137,weights = weights1, model="within",effect = "twoways")
mkt_just2.5 <- plm(market ~ diversityclass+isei+income+educ+isei_avg+n_total+age,data=paneldata137,weights = weights1, model="within",effect = "twoways")


# The interaction between ISEI, Income and Education with diversity not significant
market_models_fe <- list(mkt_just2,mkt_just2.1,mkt_just2.2,mkt_just2.3,mkt_just2.4,mkt_just2.5)

custom.coef.map = list("isei2"="to Middle","isei3"="to High",
                       "isei99"="Missing",
                       "diversityclass" = "Network diversity",
                       "isei_avg"="Network status","n_total"="Network size",
                       "income" = "HH Income","educ" = "University Degree")

# Hausman test for fixed versus random effects model
screenreg(market_models_fe)
```

```{r}
market_mobility<- lmer(market~diversityclass+isei+income+educ+isei_avg+n_total+age + (1|id),data = paneldata137)
market_mobility2<- lmer(market~nw_mobility + (1|id),data = paneldata137)
market_mobility3<- lmer(market~diversityclass+isei+age + nw_mobility+ (1|id),data = paneldata137)

frq(paneldata137$nw_mobility)
screenreg(list(market_mobility,market_mobility2,market_mobility3))

plot_predictions(market_mobility,condition = "nw_mobility")
```

