---
title: "Supplementary material"
# date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
editor_options: 
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
options(scipen=9999) # desactivar notacion cientifica
```

```{r dfreg}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
rm(list=ls())
# load(here::here("input/data/proc/study2.RData"))
load(here::here("input/data/proc/study2.RData")); elsoc_long<- elsoc_long
pacman::p_load(correlation,lme4,plm,panelr,texreg,dplyr,estimatr,marginaleffects,ggplot2,sjmisc,MLMusingR,ordinal)  
dfreg <-
elsoc_long %>%
  group_by(idencuesta) %>%
  mutate(just_educ = if_else(ola == 5 & is.na(just_educ), last(just_educ[ola == 6]), just_educ),
         just_salud = if_else(ola == 5 & is.na(just_salud), last(just_salud[ola == 6]), just_salud),
         just_pension = if_else(ola == 5 & is.na(just_pension), last(just_pension[ola == 6]), just_pension)
         ) %>%
  ungroup()

dfreg$market<- rowMeans(dfreg[,c("just_educ","just_salud","just_pension")],na.rm = T)
dfreg$market <- ((dfreg$market-min(dfreg$market,na.rm = T))/(max(dfreg$market,na.rm = T)-min(dfreg$market,na.rm = T)))*100
sjlabelled::set_label(dfreg$market) <- "Market-based distribution of social services (3 items)"

dfreg$just_educ <- ((dfreg$just_educ-min(dfreg$just_educ,na.rm = T))/(max(dfreg$just_educ,na.rm = T)-min(dfreg$just_educ,na.rm = T)))*100
dfreg$just_salud <- ((dfreg$just_salud-min(dfreg$just_salud,na.rm = T))/(max(dfreg$just_salud,na.rm = T)-min(dfreg$just_salud,na.rm = T)))*100
dfreg$just_pension <- ((dfreg$just_pension-min(dfreg$just_pension,na.rm = T))/(max(dfreg$just_pension,na.rm = T)-min(dfreg$just_pension,na.rm = T)))*100

# Deflator
# For 2021: CPI = 100 (base year)
# For 2019: IPC = 3.0%
# For 2018: IPC = 2.6%
# For 2017: IPC = 2,3#
# For 2016: IPC = 2.7%

# The CPI values relative to 2021 are:
# 2019 CPI: 97.09
# 2018 CPI: 97.47
# 2017 CPI: 97.75
# 2016 CPI: 97.37

dfreg$cpi <- dfreg$ola
dfreg$cpi <- car::recode(dfreg$cpi,"1=97.37;2=97.75;3=97.47;4=97.09;5=100")
dfreg$real_income <- as.numeric((dfreg$ing_pc/dfreg$cpi)* 100)
dfreg$real_income_eq <- as.numeric((dfreg$ing_pc_eq/dfreg$cpi)* 100)
summary(dfreg$real_income)
summary(dfreg$real_income_eq)

dfreg$ing_pc_100 <- (dfreg$real_income_eq) # each unit is 100.000 CLP
dfreg$percentile <- ntile(dfreg$ing_pc_100,100)

df1 <-  
dfreg %>%
  filter(muestra==1) %>%
  filter(ola %in% c(1,2,3,4,6,7)) %>%
  # filter(m0_edad %in% c(15:64)) %>%
  filter(ing_pc>0) %>%
  select(id="idencuesta",ola,
         # diversityclass=iqvclass,know_total,
         # crossclass,isei_sd,
         # strong_tie_t1,
         empst,
         just_educ,
         just_salud,
         just_pension,
         market,
         income=ing_pc_100,
         educ=educyear,
         # class=isei08res,
         age=m0_edad,
         sex=sexo_fx,
         weights1=ponderador_long_total,
         ponderador01,ponderador02
         ) %>%
  mutate(income=log(income)) %>%
  arrange(ola)
table(df1$ola)


df1 <-   na.omit(df1)

# # fix to complete cases
# idfreq<- frq(df1$id) %>% data.frame() %>% select(val,frq);filter<- idfreq %>% filter(frq>=2);df1 <- df1 %>% filter(id %in% filter$val)
# 
# dim(df1)
# 
df1$time <- as.numeric(df1$ola)
# table(df1$time)
# # Model w/o isei range
# model_wo_range <- 'diversitycfa_norange =~ diversityclass+crossclass + isei_sd+know_total'
# fit_range<- lavaan::cfa(model = model_wo_range,data = df1,cluster = "id",
#                         sampling.weights = "weights1"
#                         )
# lavaan::summary(fit_range,standardized=T,fit.measures=T)
# # Model using blau, sd, extensivity and number of different "social classes" known (cross-class) is the best
# 
# factorscores<- lavaan::lavPredict(fit_range,newdata = df1)
# idx <- lavaan::lavInspect(fit_range, "case.idx")
# fscores <- lavaan::lavPredict(fit_range)
# ## loop over factors
# for (fs in colnames(fscores)) {
#   df1[idx, fs] <- fscores[ , fs]
# }
# 
# df1 <- df1 %>% rename(diversitycfa=diversitycfa_norange);df1$diversityclass <- df1$diversitycfa 
paneldata <- panelr::panel_data(df1, id = id, wave = time)
```

```{r mean-center}
df1 <-
df1 %>% 
  mutate(
    # diversity_gc=MLMusingR::group_center(x = as.numeric(diversityclass),grp = id),
    # diversity_gm=MLMusingR::group_mean(x = as.numeric(diversityclass),grp = id),
    age_gc=MLMusingR::group_center(x = as.numeric(age),grp = id),
    age_gm=MLMusingR::group_mean(x = as.numeric(age),grp = id),
    income_gm=MLMusingR::group_mean(x = as.numeric(income),grp = id),
    income_gc=MLMusingR::group_center(x = as.numeric(income),grp = id),
    educ_gm=MLMusingR::group_mean(x = as.numeric(educ),grp = id),
    educ_gc=MLMusingR::group_center(x = as.numeric(educ),grp = id),
    empst_gm=MLMusingR::group_mean(x = as.numeric(empst),grp = id),
    empst_gc=MLMusingR::group_center(x = as.numeric(empst),grp = id)
    )

df1$just_educ <- scale(df1$just_educ)
df1$just_salud <- scale(df1$just_salud)
df1$just_pension <- scale(df1$just_pension)
df1$market <- scale(df1$market)
df1$income_gc <- scale(df1$income_gc) # "those above their historical average"
df1$income_gm <- scale(df1$income_gm) # "their historical average"
df1$educ_gc <- scale(df1$educ_gc) # "those above their historical average"
df1$educ_gm <- scale(df1$educ_gm) # "their historical average"
# df1 <-
# df1 %>% 
#   mutate(
#     class_gm=MLMusingR::group_mean(x = as.numeric(class),grp = id),
#     class_gc=MLMusingR::group_center(x = as.numeric(class),grp = id)
#     )

class(df1)
```

# Multinivel 

```{r}
mobility <- lmer(market~factor(time)+mobility +sex+age+(time|id),data = df1,weights = weights1) 
mobility_re<- plm(market ~ time+age+mobility,data=paneldata, model="random",weights = weights1)
screenreg(list(mobility_re,mobility))

plot_predictions(mobility, condition = c("mobility"))

frq(df1$mobility)
```


```{r}
# Hypothesis___________________________________________________________________
divtimeL <-"factor(time)"
divgm    <-"factor(time)+income_gm+educ_gm+age_gm+empst_gm+sex"
divcwc   <-"factor(time)+income_gc+educ_gc+age_gc+empst_gc+sex"
divwbfull<-paste0(divgm,"+",divcwc)
# divwbb_int4<-paste0(divwbfull,"+","income_gm*percgaplog+income_gc*percgaplog")
# divwbb_int3<-paste0(divwbfull,"+","class*diversity_gc")

hipotesis <- c(divtimeL,divgm,divcwc,divwbfull)
# Set the independent variables (IVs)

# df1$just_educ <- as.factor(df1$just_educ)
# df1$just_salud <- as.factor(df1$just_salud)
# df1$just_pension <- as.factor(df1$just_pension)

ivs<- as.data.frame(df1) %>% select(just_educ,just_salud,just_pension,market) %>%  names()

# Create the object for each model
models <- list()
for (i in ivs) {
models[[i]] <- paste0(i,"~",hipotesis,"+(1|id)")  
}

# Estimate the multilevel models
fits <- list()
for (i in ivs) {
  for (z in models[[i]][1:length(hipotesis)]) {
    fits[[z]] <- lme4::lmer(formula = z, data = df1,weights = weights1)
    # fits[[z]] <- ordinal::clmm(formula = z, data = df1,weights = weights1)
  }
}
# change model names within list
names(fits) <- paste0(rep(ivs,each=length(hipotesis)),1:length(hipotesis))

# Tables_______________________________________________________________________
omit <- "(empst_gm)|(empst_gc)|(sex)|(age_gm)|(age_gc)|(Intercept)"
coef_names <- c("Time 2 ","Time 3", 
                "Diversity (BE)","Income (BE)","Education (BE)",
                "Diversity (WE)","Income (WE)","Education (WE)",
                "Diversity (WE) x Income (BE)","Diversity (WE) x Income (WE)",
                "Diversity (WE) x Education (BE)","Diversity (WE) x Education (WE)"
                # "Diversity (WE) x ISEI (Medium)","Diversity (WE) x ISEI (High)"
                )
var_groups  <- list(
    "Time (ref: Time 1)" = 1:2,
    "Between-person estimates" = 4:6,
    "Within-person estimates" = 7:9,
    "Interactions" = 10:13
  )


screenreg(l = fits[names(fits)[grepl("just_educ", names(fits),"\n")]],single.row = F,
        omit.coef = omit,
        # groups = var_groups,
        # custom.coef.names = coef_names,
        caption = "Longitudinal multilevel models for market justice in education, network diversity and socioeconomic status",
        caption.above = T,
        # file = "output/tables/justeduc_mixed.html",
          )
screenreg(l = fits[names(fits)[grepl("just_salud", names(fits),"\n")]],single.row = F,
          omit.coef = omit,
          # groups = var_groups,
          # custom.coef.names = coef_names,
        caption = "Longitudinal multilevel models for market justice in health, network diversity and socioeconomic status",
        caption.above = T,
        # file = "output/tables/justsalud_mixed.html",
          )
screenreg(l = fits[names(fits)[grepl("just_pension", names(fits),"\n")]],single.row = F,
          omit.coef = omit,
          # groups = var_groups,
          # custom.coef.names = coef_names,
        caption = "Longitudinal multilevel models for market justice in pensions, network diversity and socioeconomic status",
        caption.above = T,
        # file = "output/tables/justpensions_mixed.html",
          )

screenreg(l = fits[names(fits)[grepl("market", names(fits),"\n")]],single.row = F,
          omit.coef = omit,
          # groups = var_groups,
          # custom.coef.names = coef_names,
        caption = "Longitudinal multilevel models for market justice preferences, network diversity and socioeconomic status",
        caption.above = T,
        # file = "output/tables/market_mixed.html",
          )
```


# Fixed effects regression

```{r}
library(plm) 
library(panelr)
# paneldata <- panelr::panel_data(df1, id = id, wave = time)
# paneldata <- paneldata %>% filter(time %in% c(1,3,5))

#test tge haussman indica que es mejor usar FE con two-way 
mkt_educ <- plm(just_educ ~ time+age+income+educ+sex,data=paneldata,weights = weights1,model = "within")
mkt_salu <- plm(just_salud ~ time+age+income+educ+sex ,data=paneldata,weights = weights1, model="within")
mkt_pens <- plm(just_pension ~ time+age +income +educ+sex ,data=paneldata,weights = weights1, model="within")
mkt_just <- plm(market ~ time+age +income +educ+sex ,data=paneldata,weights = weights1, model="within")

market_models_fe <- list(mkt_educ,mkt_salu,mkt_pens,mkt_just)
screenreg(market_models_fe,stars = c(0.001,0.01,0.05,0.1))
```

# Alternative operationalization 

# _Income_

```{r}
dfreg <- 
dfreg %>% 
  # group_by(ola) %>% 
  mutate(percentile_wave=ntile(ing_pc_100,100),
         bot_mid_top_wave=car::recode(percentile_wave,"1:20=1;21:79=2;80:100=3"))

elsoc_wide <- widen_panel(panel_data(dfreg %>% select(idencuesta,ola,percentile_wave,bot_mid_top_wave), id = idencuesta, wave = ola), separator = "_")
elsoc_wide$income_prof <- paste0(elsoc_wide$bot_mid_top_wave_1,elsoc_wide$bot_mid_top_wave_5)
frq(elsoc_wide$income_prof)
# a. Stable low income: In the lowest tertile in all three periods 
# b. Stable middle income: In the middle tertile in all three periods 
# c. Stable high income: In the highest tertile in all three periods 
# d. Upward mobility: In the lowest tertile in the first period and either in tertile 2 or 3 in the last period
# e. Downward mobility: In the highest tertile in the first period and either in tertile 1 or 2 in the last period
# f. Other: All other trajectories

elsoc_wide$ind_inc_prof <- car::recode(elsoc_wide$income_prof,"'11'='1stablelow';'33'='2stablemid';'22'='3stablehig';c('12','13')='4upwardmob';c('31','21')='5downwardmob';else = '99other'")
frq(elsoc_wide$ind_inc_prof)
# • Stable low income: Start and end at the 20th percentile in income (P20). 
# • Stable middle income: Start and end at the 50th percentile in income (P50). 
# • Stable high income: Start and end at the 80th percentile in income (P80). 
# • Upward mobility: Start at 20th percentile, end at 80th percentile (P20 → P80). 
# • Downward mobility: Start at 80th percentile, end at 20th percentile (P80 → P20).

df_profiles<- select(elsoc_wide,"idencuesta","ind_inc_prof",percentile_wave_1,percentile_wave_5)
df_profiles$idencuesta <- as.numeric(as.character(df_profiles$idencuesta))

dfreg <- 
  dfreg %>% 
  left_join(select(df_profiles,"idencuesta","ind_inc_prof",percentile_wave_1,percentile_wave_5),by="idencuesta")

```

# _Occupation_

```{r}
frq(is.na(dfreg$isei08res))
frq(is.na(dfreg$isei08))

dfreg$isei08res_hh <- ifelse(is.na(dfreg$isei08),yes = dfreg$isei08res, no=dfreg$isei08)

frq(is.na(dfreg$isei08res_hh))

```

# _Impute ISEI scores_
```{r}
load(file = here::here("input/data/proc/study2_to-impute.RData"))

library(mice)
library(dplyr)
df_imp_2016_2023 <- df1 

dim(df_imp_2016_2023)
summary(df_imp_2016_2023)
ini <- mice(df_imp_2016_2023, maxit = 0,method = "cart")
meth <- ini$meth
# meth["market"] <- ""
pred <- ini$pred
pred

pred[, "id"] <- 0
# pred[, "market"] <- 1


output_mice_2016_2023_cart_cluster <- mice::mice(data = df_imp_2016_2023,
             m = 5,seed = 1241,method = meth,predictorMatrix = pred,cluster = "id")

df1_imputed <- complete(output_mice_2016_2023_cart_cluster)
summary(df1_imputed)

save(df1_imputed,
     file = here::here("input/data/proc/study2_imputed.RData"))

df_imp_2016_2023_2 <- df_imp_2016_2023 
ini <- mice(df_imp_2016_2023_2, maxit = 0,method = "cart")
meth <- ini$meth
meth["market"] <- ""
meth["just_educ"] <- ""
meth["just_salud"] <- ""
meth["just_pension"] <- ""
pred <- ini$pred
pred

# pred[, "id"] <- 0
pred["market", ] <- 1
pred["just_educ", ] <- 1
pred["just_salud", ] <- 1
pred["just_pension", ] <- 1

output_mice_2016_2023_2_cart_cluster <- mice::mice(data = df_imp_2016_2023_2,
             m = 5,seed = 1241,method = meth,predictorMatrix = pred,cluster = "id")
df1_imputed_v2 <- complete(output_mice_2016_2023_2_cart_cluster)
summary(df1_imputed_v2)


save(df1_imputed_v2,
     file = here::here("input/data/proc/study2_v2_imputed.RData"))

```

```{r}
load(file = here::here("input/data/proc/study2_v3_to-impute.RData"))
paneldata$isei[paneldata$isei==99] <- NA

summary(paneldata$isei)
df_imp_2016_2023 <- paneldata 
dim(df_imp_2016_2023)
summary(df_imp_2016_2023)
ini <- mice(df_imp_2016_2023, maxit = 0,method = "cart")
meth <- ini$meth
# meth["market"] <- ""
pred <- ini$pred
pred

pred[, "id"] <- 0
# pred[, "market"] <- 1
output_mice_2016_2023_cart_cluster <- mice::mice(data = df_imp_2016_2023,
             m = 5,seed = 1241,method = meth,predictorMatrix = pred,cluster = "id")

df1_imputed <- complete(output_mice_2016_2023_cart_cluster)
save(df1_imputed,
     file = here::here("input/data/proc/study2_v3_imputed.RData"))
```



# _Market preferences based on Party Identification_ 
```{r}



# Value |                                            Label |     N | Raw % | Valid % | Cum. %
# -------------------------------------------------------------------------------------------
#     1 |                           Partido Comunista (PC) |   454 |  2.52 |    3.02 |   3.02
#     2 |                           Partido Humanista (PH) |   232 |  1.29 |    1.54 |   4.57
#     3 |                      Revolucion Democratica (RD) |   209 |  1.16 |    1.39 |   5.96
#     4 |                        Partido Progresista (PRO) |    49 |  0.27 |    0.33 |   6.28
#     5 |                     Evolucion Politica (Evopoli) |   148 |  0.82 |    0.99 |   7.27  *
#     6 |                  Partido por la Democracia (PPD) |   458 |  2.54 |    3.05 |  10.32
#     7 |                                         Amplitud |    23 |  0.13 |    0.15 |  10.47
#     8 |                Partido Democrata Cristiano (PDC) |   582 |  3.23 |    3.87 |  14.35
#     9 | Partido Regionalista de los Independientes (PRI) |    48 |  0.27 |    0.32 |  14.67
#    10 |                         Renovacion Nacional (RN) |   670 |  3.71 |    4.46 |  19.13 *
#    11 |              Union Democrata Independiente (UDI) |   448 |  2.48 |    2.98 |  22.11 *
#    12 |                           Partido Socialista(PS) |   589 |  3.27 |    3.92 |  26.03
#    13 |          Partido Radical Social Democrata (PRSD) |    83 |  0.46 |    0.55 |  26.58
#    14 |                           Otro. Especifique cual |   145 |  0.80 |    0.97 |  27.55
#    15 |                                          Ninguno | 10595 | 58.75 |   70.54 |  98.09
#    16 |                         Convergencia Social (CS) |    99 |  0.55 |    0.66 |  98.75
#    17 |                        Partido de la Gente (PDG) |    60 |  0.33 |    0.40 |  99.15
#    18 |                        Partido Republicano (PLR) |   111 |  0.62 |    0.74 |  99.89 *
#    19 |                                  Partido Comunes |    17 |  0.09 |    0.11 | 100.00
#  <NA> |                                             <NA> |  3015 | 16.72 |    <NA> |   <NA>

# Crear la variable binaria donde 1 es derecha y 0 es izquierda u otros
dfreg$votederech<- car::recode(dfreg$c16,recodes = "c(5,10,11,18)=1;else=0")
frq(dfreg$votederech)
df1 <-  
dfreg %>%
  filter(ola %in% c(1,3,5,7)) %>%
  filter(muestra==1) %>% 
  select(id="idencuesta",ola,muestra,tipo_atricion,
         # diversityclass=diversitycfa,
         iqvclass,know_total,crossclass,isei_sd,
         isei_avg,
         n_total,         votederech,         
         income=real_income_eq,
         isei=isei3res_na,
         # isei=isei08res,
         educ=univ,
         age=m0_edad,
         sex=sexo_fx,
         weights1=ponderador_long_total
         ) %>%
  mutate(income=log(income)) %>%
  arrange(ola) %>% 
  filter(!is.infinite(income))
table(df1$ola)


# df1_atrition <- df1
df1 <-  df1 %>% filter(!is.infinite(income)) %>% na.omit(df1)
# # fix to complete cases
# idfreq<- frq(df1$id) %>% data.frame() %>% select(val,frq);filter<- idfreq %>% filter(frq>=1);df1 <- df1 %>% filter(id %in% filter$val)

dim(df1)

df1$time <- as.numeric(df1$ola)
table(df1$time)
# # Model w/o isei range
model_wo_range <- 'diversitycfa_norange =~ iqvclass+crossclass + isei_sd+know_total'
fit_range<- lavaan::cfa(model = model_wo_range,data = df1,
                        cluster = "id",
                        sampling.weights = "weights1"
                        )
lavaan::summary(fit_range,standardized=T,fit.measures=T)
# Model using blau, sd, extensivity and number of different "social classes" known (cross-class) is the best

factorscores<- lavaan::lavPredict(fit_range,newdata = df1)
idx <- lavaan::lavInspect(fit_range, "case.idx")
fscores <- lavaan::lavPredict(fit_range)
# loop over factors
for (fs in colnames(fscores)) {
  df1[idx, fs] <- fscores[ , fs]
}

df1 <- df1 %>% rename(diversitycfa=diversitycfa_norange);df1$diversityclass <- df1$diversitycfa
paneldata <- panelr::panel_data(df1, id = id, wave = time)
mean(df1$diversityclass);sd(df1$diversityclass)
summary(df1$diversityclass)


mkt_just2.6 <- plm(votederech ~ diversityclass+isei_avg+n_total+isei+age,data=paneldata,weights = weights1, model="within",effect = "twoways")

summary(mkt_just2.6)
```

# _Social class and ISEI categorical_
```{r}
# df1$isei <- car::recode(as.numeric(df1$isei),"1:2='1Service Class';3:4='2Routine nonmanual';5='3Self-employed';6:9='4Working Class';10:11='5Unemployed and Retired'",as.factor = T)
# df1 <- df1 %>% filter(isei != '5Unemployed and Retired')

# df1$isei <- forcats::fct_rev(df1$isei)
# df1$isei <- relevel(df1$isei,ref = '3Self-employed')
# frq(df1$isei)

class_w1 <- df1 %>% filter(ola ==1) %>% select(id,class1=isei)
class_w3 <- df1 %>% filter(ola ==3) %>% select(id,class3=isei)
class_w5 <- df1 %>% filter(ola ==5) %>% select(id,class5=isei)
class_w1w5<- left_join(class_w1,class_w3,by ="id") %>% left_join(class_w5)

class_w1w5$trajectory <- paste0(class_w1w5$class1,class_w1w5$class3,class_w1w5$class5) 
class_w1w5$class1 <- as.numeric(class_w1w5$class1)
class_w1w5$class3 <- as.numeric(class_w1w5$class3)
class_w1w5$class5 <- as.numeric(class_w1w5$class5)

class_w1w5$upward<- ifelse(class_w1w5$class5>class_w1w5$class1 | class_w1w5$class5>class_w1w5$class3 | 
  class_w1w5$class3>class_w1w5$class1,yes = 1,no = 0)
frq(class_w1w5$upward)
class_w1w5$downward<- ifelse(class_w1w5$class5<class_w1w5$class1 | class_w1w5$class5<class_w1w5$class3 | 
  class_w1w5$class3<class_w1w5$class1,yes = 1,no = 0)
frq(class_w1w5$downward)

class_w1w5$stable <- ifelse(class_w1w5$downward==0 & class_w1w5$upward==0 | 
                              class_w1w5$trajectory %in%  c("1NA1","2NA2","3NA3",
                                                            "11NA","22NA","33NA",
                                                            "NA11","NA22","NA33"),yes = 1,no = 0) 

class_w1w5$stablelow <- ifelse(class_w1w5$stable==1 & 
                              class_w1w5$trajectory %in%  c("111","1NA1","11NA","NA11"),yes = 1,no = 0)

frq(class_w1w5$stablelow)
class_w1w5$stablemid <- ifelse(class_w1w5$stable==1 & 
                              class_w1w5$trajectory %in%  c("222","2NA2","22NA","NA22"),yes = 1,no = 0)
frq(class_w1w5$stablemid)
class_w1w5$stablehig <- ifelse(class_w1w5$stable==1 & 
                              class_w1w5$trajectory %in%  c("333","3NA3","33NA","NA33"),yes = 1,no = 0)
frq(class_w1w5$stablemid)

df1 <- df1 %>% left_join(class_w1w5 %>% select(id,upward,downward,stable))

# df1$isei <- car::recode(var = df1$isei,recode="c('IIIa Routine Nonmanual','IIIb Lower Sales-Service')='III Routine Nonmanual';c('V Manual Supervisors','VI Skilled Worker')='V+VI Skilled Worker'")
# df1$isei <- factor(df1$isei,c("I Higher Controllers","II Lower Controllers","III Routine Nonmanual","IV Self-employed","V+VI Skilled Worker","VII Unskilled Workers","Never worked and long-term unemployed","Retired"))
```



```{r}
# class_t1 <- dfreg %>% filter(ola ==1) %>% select(idencuesta,class1=isei3_imputed) %>% mutate(class1=as.numeric(class1))
# class_t2 <- dfreg %>% filter(ola ==3) %>% select(idencuesta,class2=isei3_imputed) %>% mutate(class2=as.numeric(class2))
# class_t3 <- dfreg %>% filter(ola ==5) %>% select(idencuesta,class3=isei3_imputed) %>% mutate(class3=as.numeric(class3))
# class_t4 <- dfreg %>% filter(ola ==7) %>% select(idencuesta,class7=isei3_imputed) %>% mutate(class7=as.numeric(class7))
#
# class_w1w5 <-
#   left_join(class_t1,class_t2,by ="idencuesta") %>%
#   left_join(class_t3,by ="idencuesta") %>% left_join(class_t4,by ="idencuesta")
#
# sjPlot::tab_xtab(class_w1w5$class1,class_w1w5$class7,
#                  title = "Table AX: Mobility Matrix",show.obs = T,show.cell.prc = T,show.summary = F,)
#
# table(class_w1w5$class1,class_w1w5$class7)
#
# class_w1w5$stable<- ifelse(class_w1w5$class1==class_w1w5$class7,1,no = 0)
#
#
# class_w1w5$upward<- ifelse(class_w1w5$class1<class_w1w5$class7,1,no = NA)
# class_w1w5$downward<- ifelse(class_w1w5$class1>class_w1w5$class7,2,no = NA)
# class_w1w5$stable_hig <- ifelse((class_w1w5$class7==3 & class_w1w5$stable == 1),3,no = NA)
# class_w1w5$stable_mid <- ifelse((class_w1w5$class7==2 & class_w1w5$stable == 1),4,no = NA)
# class_w1w5$stable_low <- ifelse((class_w1w5$class7==1 & class_w1w5$stable == 1),5,no = NA)
#
# class_w1w5$mobility <- NA
# class_w1w5$mobility <-ifelse(is.na(class_w1w5$mobility),yes = class_w1w5$upward,no = class_w1w5$mobility)
# class_w1w5$mobility <-ifelse(is.na(class_w1w5$mobility),yes = class_w1w5$downward,no = class_w1w5$mobility)
# class_w1w5$mobility <-ifelse(is.na(class_w1w5$mobility),yes = class_w1w5$stable_hig,no = class_w1w5$mobility)
# class_w1w5$mobility <-ifelse(is.na(class_w1w5$mobility),yes = class_w1w5$stable_mid,no = class_w1w5$mobility)
# class_w1w5$mobility <-ifelse(is.na(class_w1w5$mobility),yes = class_w1w5$stable_low,no = class_w1w5$mobility)
# frq(class_w1w5$mobility)
#
# Recover cases with short mobility trajectories
class_w1w5$mobility <- ifelse(class_w1w5$class1<class_w1w5$class2 & is.na(class_w1w5$mobility) ,yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)
class_w1w5$mobility <- ifelse(class_w1w5$class1<class_w1w5$class3 & is.na(class_w1w5$mobility),yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)
class_w1w5$mobility <- ifelse(class_w1w5$class2<class_w1w5$class3 & is.na(class_w1w5$mobility),yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)
class_w1w5$mobility <- ifelse(class_w1w5$class3<class_w1w5$class7 & is.na(class_w1w5$mobility),yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)


# Recover cases with short mobility trajectories
class_w1w5$mobility <- ifelse(class_w1w5$class1>class_w1w5$class2 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)
class_w1w5$mobility <- ifelse(class_w1w5$class1>class_w1w5$class3 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)
class_w1w5$mobility <- ifelse(class_w1w5$class2>class_w1w5$class3 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)
class_w1w5$mobility <- ifelse(class_w1w5$class3>class_w1w5$class7 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)

# # Stable high
# class_w1w5$mobility <- ifelse(class_w1w5$class1 == 3 & class_w1w5$class2 ==3 & is.na(class_w1w5$mobility),yes = 3,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class1 == 3 & class_w1w5$class3 ==3 & is.na(class_w1w5$mobility),yes = 3,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class2 == 3 & class_w1w5$class3 ==3 & is.na(class_w1w5$mobility),yes = 3,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class3 == 3 & class_w1w5$class7 ==3 & is.na(class_w1w5$mobility),yes = 3,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# # Stable middle
# class_w1w5$mobility <- ifelse(class_w1w5$class1 == 2 & class_w1w5$class2 ==2 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class1 == 2 & class_w1w5$class3 ==2 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class2 == 2 & class_w1w5$class3 ==2 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class3 == 2 & class_w1w5$class7 ==2 & is.na(class_w1w5$mobility),yes = 2,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# # Stable low
# # Stable middle
# class_w1w5$mobility <- ifelse(class_w1w5$class1 == 1 & class_w1w5$class2 ==1 & is.na(class_w1w5$mobility),yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class1 == 1 & class_w1w5$class3 ==1 & is.na(class_w1w5$mobility),yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class2 == 1 & class_w1w5$class3 ==1 & is.na(class_w1w5$mobility),yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)
# class_w1w5$mobility <- ifelse(class_w1w5$class3 == 1 & class_w1w5$class7 ==1 & is.na(class_w1w5$mobility),yes = 1,no = class_w1w5$mobility);frq(class_w1w5$mobility)
#
# class_w1w5$mobility <- ifelse(is.na(class_w1w5$mobility),yes = 99,no = class_w1w5$mobility)
# class_w1w5$mobility <- factor(class_w1w5$mobility,labels = c("1Upward","2Downward",
#                                                              "3StableHigh","4StableMid","5StableLow",
#                                                              "6Mixed"))
#
# class_w1w5$mobility <- relevel(class_w1w5$mobility,ref = "3StableHigh")

dfreg <- dfreg %>%  left_join(class_w1w5[,c("idencuesta","mobility")],by = "idencuesta")
```

