---
title: "Data preparation - micro"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: hide
    number_sections: yes
editor_options:
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
options(scipen=9999) # desactivar notacion cientifica
```

## Individual data

```{r}
remove(list = ls()) # clean workspace
if (!require("pacman")) install.packages("pacman") # install pacman
# install.packages("devtools")
# devtools::install_git("https://code.europa.eu/digclass/digclass.git",force = TRUE)

pacman::p_load(dplyr,readxl,sjmisc, sjlabelled, questionr, car,here,ggplot2,DIGCLASS,spatstat)# load libraries
load(here::here("input/data/original/ELSOC_Long_2016_2022_v1.00.RData"))

elsoc_long_2016_2022.2[elsoc_long_2016_2022.2 ==-999] <- NA
elsoc_long_2016_2022.2[elsoc_long_2016_2022.2 ==-888] <- NA
elsoc_long_2016_2022.2[elsoc_long_2016_2022.2 ==-777] <- NA
elsoc_long_2016_2022.2[elsoc_long_2016_2022.2 ==-666] <- NA

# Attitudes____________________________________________________________________
elsoc_long_2016_2022.2 <- 
elsoc_long_2016_2022.2 %>% 
  #create new variables
  mutate(just_educ=d02_02,
         just_pension=d02_01,
         just_salud=d02_03,
         perineq=c18_11,
         des_perc=c18_11,
         effort=c18_09,
         talent=c18_10,
         gensocialtrust=c02,
         genaltruism=c03,
         genjust=c04,
         ps_veci=c07_01,
         ps_comu=c07_02,
         ps_amig=c07_03,
         ps_volu=c07_04,
         ps_dona=c07_05,
         ps_mone=c07_06,
         ps_conv=c07_07,
         ps_job=c07_08,
         mem_jjvv=c12_01,
         mem_reli = c12_02,
         mem_poli = c12_03,
         mem_unio = c12_04,
         mem_grem = c12_05,
         mem_char = c12_06,
         mem_spor = c12_07,
         mem_stud = c12_08,
         mem_othe = c12_09,
         mem_othet = c12_09_otro,
         isco08=ciuo08_m22,
         isco88=ciuo88_m22,
         emprel=m26,
         nsup=m25,
         isco08res=ciuo08_m03,
         isco88res=ciuo88_m03,
         emprelres=m07,
         nsupres=m06,
         sexo=m0_sexo) %>% 
  sjlabelled::drop_labels(., drop.na = FALSE)
```

<!-- https://webapps.ilo.org/public/spanish/bureau/stat/isco/docs/resol08.pdf -->

```{r social-class-hh}
# Head household Social Class----------------------------------------------------
elsoc_long_2016_2022.2 <- 
elsoc_long_2016_2022.2 %>%
  mutate(
    is_supervisor = ifelse(nsup == 0, 0, 1),
    self_employed = case_when(
      emprel %in% c(1, 2) ~ 0,
      emprel %in% c(4, 5) ~ 1,
      TRUE ~ NA
    ),
    n_employees = ifelse(is_supervisor == 0, 0, nsup)
  ) 

# elsoc_long_2016_2022.2$n_employees[is.na(elsoc_long_2016_2022.2$n_employees)] <- 0 # set num employees NA to 0
# Repair isco 
elsoc_long_2016_2022.2$isco08 <- repair_isco(x = elsoc_long_2016_2022.2$isco08,digits = 4);frq(elsoc_long_2016_2022.2$isco08)
# transform ISCO-08 to ISCO-88 
elsoc_long_2016_2022.2$isco88_2 <-  isco08_to_isco88(elsoc_long_2016_2022.2$isco08);frq(elsoc_long_2016_2022.2$isco88_2)

# put all the ISCO 88 codes in one variable
elsoc_long_2016_2022.2$isco88_3 <- 
  ifelse(is.na(elsoc_long_2016_2022.2$isco88_2),
         yes = elsoc_long_2016_2022.2$isco88,
         no = elsoc_long_2016_2022.2$isco88_2)

elsoc_long_2016_2022.2$isco88_3[elsoc_long_2016_2022.2$isco88_3==9999] <- NA # set all ISCO 9999 to NA
table(elsoc_long_2016_2022.2$isco88_3)

# Generate head of household class position 
elsoc_long_2016_2022.2 <-
  elsoc_long_2016_2022.2 %>% mutate(
    isco88,
    egp11_label = isco88_to_egp(isco88_3, self_employed, n_employees,label = T,to_factor = T),
    egp11 = isco88_to_egp(isco88_3, self_employed, n_employees,to_factor = T),
    oesch16_label = isco88_to_oesch(isco88_3,self_employed, n_employees,label = T,to_factor = T),
    oesch16 = isco88_to_oesch(isco88_3,self_employed, n_employees,label = F,to_factor = T),
    oesch8_label = isco88_to_oesch(isco88_3,self_employed, n_employees,label = T,to_factor = T,n_classes=8),
    oesch8 = isco88_to_oesch(isco88_3,self_employed, n_employees,label = F,to_factor = T,n_classes=8),
    oesch5_label = isco88_to_oesch(isco88_3,self_employed, n_employees,label = T,to_factor = T,n_classes=5),
    oesch5 = isco88_to_oesch(isco88_3,self_employed, n_employees,label = F,to_factor = T,n_classes=5)    
  )

frq(elsoc_long_2016_2022.2$egp11_label)# N=2377 without repair 
frq(elsoc_long_2016_2022.2$egp11)
frq(elsoc_long_2016_2022.2$oesch16_label);frq(elsoc_long_2016_2022.2$oesch16)
frq(elsoc_long_2016_2022.2$oesch8_label);frq(elsoc_long_2016_2022.2$oesch8)

levels(elsoc_long_2016_2022.2$egp11_label) <- 
  stringi::stri_replace_all(str = levels(elsoc_long_2016_2022.2$egp11_label),
                            replacement = "",regex = "'");
levels(elsoc_long_2016_2022.2$egp11_label) <- 
  stringi::stri_replace_all(str = levels(elsoc_long_2016_2022.2$egp11_label),
                            replacement = "",regex = ":")
frq(elsoc_long_2016_2022.2$egp11_label)
```


```{r social-class-respondent}
# Respondent Social Class-------------------------------------------------------
elsoc_long_2016_2022.2$isco88res_2 = isco08_to_isco88(elsoc_long_2016_2022.2$isco08res)
table(elsoc_long_2016_2022.2$isco88res_2)
table(elsoc_long_2016_2022.2$isco88res)

elsoc_long_2016_2022.2$isco88res_3<- 
  ifelse(is.na(elsoc_long_2016_2022.2$isco88res_2),
         yes = elsoc_long_2016_2022.2$isco88res,
         no = elsoc_long_2016_2022.2$isco88res_2)

table(elsoc_long_2016_2022.2$isco88res_3)

elsoc_long_2016_2022.2 <- 
elsoc_long_2016_2022.2 %>%
  mutate(
    is_supervisor_r = ifelse(nsupres == 0, 0, 1),
    self_employed_r = case_when(
      emprelres %in% c(1, 2) ~ 0,
      emprelres %in% c(4, 5) ~ 1,
      TRUE ~ NA
    ),
    n_employees_r = ifelse(is_supervisor_r == 0, 0, nsupres)
  ) 

elsoc_long_2016_2022.2 <-
  elsoc_long_2016_2022.2 %>% 
  mutate(
    egp11_r_label = isco88_to_egp(x = isco88res_3, self_employed = self_employed_r,n_employees= n_employees_r,label = T,to_factor = T),
    oesch16_r_label = isco88_to_oesch(isco88res_3,self_employed_r, n_employees_r,label = T,to_factor = T),
    oesch8_r_label = isco88_to_oesch(isco88res_3,self_employed_r, n_employees_r,label = T,to_factor = T,n_classes=8),
    oesch5_r_label = isco88_to_oesch(isco88res_3,self_employed_r, n_employees_r,label = T,to_factor = T,n_classes=5),
  )

levels(elsoc_long_2016_2022.2$egp11_r_label) <- stringi::stri_replace_all(str = levels(elsoc_long_2016_2022.2$egp11_r_label),replacement = "",regex = "'")

levels(elsoc_long_2016_2022.2$egp11_r_label) <- stringi::stri_replace_all(str = levels(elsoc_long_2016_2022.2$egp11_r_label),replacement = "",regex = ":")

frq(elsoc_long_2016_2022.2$egp11_r_label)
frq(elsoc_long_2016_2022.2$oesch16_r_label)
frq(elsoc_long_2016_2022.2$oesch8_r_label)
frq(elsoc_long_2016_2022.2$oesch5_r_label)

table(elsoc_long_2016_2022.2$oesch8_r_label,elsoc_long_2016_2022.2$oesch5_r_label)

# Generate EGP 8 for respondents-----------------------------------------------
elsoc_long_2016_2022.2$egp8_r_label <- 
  car::recode(var = elsoc_long_2016_2022.2$egp11_r_label,
  recodes = "c('IVa Self-employed with employees','IVb Self-employed with no employees','IVc Self-employed Farmer') = 'IV Self-employed';
  c('VIIa Unskilled Worker','VIIb Farm Labor') = 'VII Unskilled Workers'")

frq(elsoc_long_2016_2022.2$egp8_r_label)

# Include the residual "underclass" category in the EGP-8
elsoc_long_2016_2022.2$egp8_r_label_na <- 
  elsoc_long_2016_2022.2$egp8_r_label # clone EGP-8 respondent 
egp8lab <- levels(elsoc_long_2016_2022.2$egp8_r_label_na)
frq(elsoc_long_2016_2022.2$m02)
# Generate the residual category 
elsoc_long_2016_2022.2$egp8_r_label_na <- 
  ifelse(elsoc_long_2016_2022.2$m02 %in% c(4,6,7,8,9),yes = 9,no= elsoc_long_2016_2022.2$egp8_r_label_na)
elsoc_long_2016_2022.2$egp8_r_label_na <- ifelse(elsoc_long_2016_2022.2$m02 %in% c(5),yes = 10,no= elsoc_long_2016_2022.2$egp8_r_label_na) # 5 pasa a retired
frq(elsoc_long_2016_2022.2$egp8_r_label_na)

# label the residual categories
elsoc_long_2016_2022.2$egp8_r_label_na <- 
  factor(elsoc_long_2016_2022.2$egp8_r_label_na,
         labels = c(egp8lab,"Never worked and long-term unemployed","Retired"))
frq(elsoc_long_2016_2022.2$egp8_r_label_na)
```


```{r status}
# Education_______________________________________
elsoc_long_2016_2022.2$educ <- 
  car::recode(elsoc_long_2016_2022.2$m01,
              "1=0;c(2,3)=1;c(4,5)=2;c(6,7)=3;c(8,9,10)=4; c(-888,-999)=NA")
elsoc_long_2016_2022.2$educ <-
  factor(elsoc_long_2016_2022.2$educ,
         labels = c("No formal education","Primary Education","High school Education","Technical Education ","Universitary and postgraduate Education"))

#reverse education, reference level is the highest level
#elsoc_long_2016_2022.2$educ <- forcats::fct_rev(elsoc_long_2016_2022.2$educ)

elsoc_long_2016_2022.2$educ <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$educ,
                      label = "Education")
sjmisc::frq(elsoc_long_2016_2022.2$educ)

#Recoding of education to years based on casen 2017.
elsoc_long_2016_2022.2$educyear<- as.numeric(
  car::recode(elsoc_long_2016_2022.2$m01, 
              "1=0;2=4.3;3=7.5;4=9.8;5=12.02;6=13.9;
               7=14.8;8=14.9;9=16.9;10=19.07;c(-888,-999)=NA", 
              as.numeric = T))

elsoc_long_2016_2022.2$educyear <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$educyear,
                      label = "Education in years")

class(elsoc_long_2016_2022.2$educyear)
sjmisc::frq(elsoc_long_2016_2022.2$educyear)

# Household income_________________________________________

#Impute midpoint of income ranges
elsoc_long_2016_2022.2$m30_rec <-
as.numeric(car::recode(elsoc_long_2016_2022.2$m30,
           "1=110000;2=251000;3=305000;4=355000;5=400000;
            6=445000;7=490000;8=535000;9=585000;10=640000;11=700000;12=765000;
            13=845000;14=935000;15=1040000;16=1180000;17=1375000;18=1670000;
            19=2275000;20=2700000;NA=NA;c(-888,-999)=NA"))

summary(elsoc_long_2016_2022.2$m30_rec)
#Impute midpoint of income ranges (2021)
elsoc_long_2016_2022.2$m30b_rec <-
as.numeric(car::recode(elsoc_long_2016_2022.2$m30b,
           "1=125000;2=300000;3=400000;4=575000;5=70000;NA=NA;c(-888,-999)=NA"))
summary(elsoc_long_2016_2022.2$m30b_rec)

# Combine m30_rec with m30b_rec
elsoc_long_2016_2022.2$m30_rec <- 
  ifelse(is.na(elsoc_long_2016_2022.2$m30_rec),
         yes = elsoc_long_2016_2022.2$m30b_rec,
         no = elsoc_long_2016_2022.2$m30_rec)
summary(elsoc_long_2016_2022.2$m30_rec)

#Recode DK/DA of Income to NA
elsoc_long_2016_2022.2$m29_rec <-
  as.numeric(car::recode(elsoc_long_2016_2022.2$m29,"c(-888,-999)=NA"))

#replace NA of income with new imputed variable
elsoc_long_2016_2022.2$m29_imp <- 
  ifelse(test = !is.na(elsoc_long_2016_2022.2$m29_rec),
         yes =  elsoc_long_2016_2022.2$m29_rec,
         no =  elsoc_long_2016_2022.2$m30_rec)
summary(elsoc_long_2016_2022.2$m29_imp)

# elsoc_long_2016_2022.2$m29_imp <- 
#   ifelse(test = is.na(elsoc_long_2016_2022.2$m29_imp),
#          yes =  elsoc_long_2016_2022.2$m30b_rec,
#          no =  elsoc_long_2016_2022.2$m29_imp)

summary(elsoc_long_2016_2022.2$m29_imp)

# N Household:
elsoc_long_2016_2022.2 <-
  elsoc_long_2016_2022.2 %>%
  mutate(n_hogar =
           dplyr::case_when(ola == 1 ~ nhogar1,
                            ola == 2 ~ m46_nhogar,
                            ola == 3 ~ m54,
                            ola == 4 ~ m54,
                            ola == 5 ~ m54))

summary(elsoc_long_2016_2022.2$n_hogar)
#imputar tamanio del hogar de ola 5 a ola 6
elsoc_long_2016_2022.2 <- 
elsoc_long_2016_2022.2 %>%  
  group_by(idencuesta) %>%
  mutate(n_hogar = if_else(ola == 6 & is.na(n_hogar), last(n_hogar[ola == 5]), n_hogar)) %>% 
  ungroup() 

sjmisc::frq(elsoc_long_2016_2022.2$n_hogar)
table(elsoc_long_2016_2022.2$n_hogar,elsoc_long_2016_2022.2$ola)

#Recode DK/DA to NA
elsoc_long_2016_2022.2$n_hogar_r<-
  car::recode(elsoc_long_2016_2022.2$n_hogar,"c(-888,-999)=NA")


table(elsoc_long_2016_2022.2$m13,elsoc_long_2016_2022.2$n_hogar_r)

#ingresos individuales para hogares de 1 persona
elsoc_long_2016_2022.2 %>% sjmisc::find_var('Ingreso')
elsoc_long_2016_2022.2$inc_ind <- ifelse(elsoc_long_2016_2022.2$n_hogar_r==1,elsoc_long_2016_2022.2$m13,NA)
summary(elsoc_long_2016_2022.2$inc_ind)
# 
# c(40000,
# (40001 + 85000) / 2,
# (85001 + 125000) / 2,
# (125001 + 170000) / 2,
# (170001 + 210000) / 2,
# (210001 + 230000) / 2,
# (230001 + 280000) / 2,
# (280001 + 320000) / 2,
# (320001 + 360000) / 2,
# (360001 + 400000) / 2,
# (400001 + 465000) / 2,
# (465001 + 540000) / 2,
# (540001 + 665000) / 2,
# (665001 + 850000) / 2,
# (850001 + 1300000) / 2,
# 1300001)    
elsoc_long_2016_2022.2$m14_rec<- 
  car::recode(elsoc_long_2016_2022.2$m14,
              "1=40000.0;2=62500.5;3=105000.5;4=147500.5;5=190000.5;6=220000.5;
              7=255000.5;8=300000.5;9=340000.5;10=380000.5;11=432500.5;12=502500.5;
              13=602500.5;14=757500.5;15=1075000.5;16=1300001.0"
) 

elsoc_long_2016_2022.2$inc_ind <- ifelse(elsoc_long_2016_2022.2$n_hogar_r==1 & is.na(elsoc_long_2016_2022.2$inc_ind),elsoc_long_2016_2022.2$m14_rec,elsoc_long_2016_2022.2$inc_ind)
summary(elsoc_long_2016_2022.2$inc_ind)


# Ingreso del hogar pegarle ingreso del hogar unipersonal
summary(elsoc_long_2016_2022.2$m29_imp)
elsoc_long_2016_2022.2$m29_imp <- 
  ifelse(is.na(elsoc_long_2016_2022.2$m29_imp) & elsoc_long_2016_2022.2$n_hogar_r==1,
         elsoc_long_2016_2022.2$inc_ind,
         elsoc_long_2016_2022.2$m29_imp) #recupero 14 casos
summary(elsoc_long_2016_2022.2$m29_imp)


# Household Equivalent income 
# 1.0 to the first adult;
# 0.5 to the second and each subsequent person aged 14 and over;
# 0.3 to each child aged under 14.

elsoc_long_2016_2022.2$n_hogar_r_eq <- (elsoc_long_2016_2022.2$n_hogar_r + 1) /2
table(elsoc_long_2016_2022.2$n_hogar_r_eq)

frq(elsoc_long_2016_2022.2$n_hogar_r_eq)

# Per capita household income:
elsoc_long_2016_2022.2$ing_pc <- 
  (elsoc_long_2016_2022.2$m29_imp/elsoc_long_2016_2022.2$n_hogar_r)

# Per capita household income equivalized (OECD):
elsoc_long_2016_2022.2$ing_pc_eq <- 
  (elsoc_long_2016_2022.2$m29_imp/elsoc_long_2016_2022.2$n_hogar_r_eq)

descr(elsoc_long_2016_2022.2$ing_pc_eq)
descr(elsoc_long_2016_2022.2$ing_pc)
elsoc_long_2016_2022.2$ing_pc <-
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ing_pc,
                      label = "Household income per capita")  

sjmisc::descr(elsoc_long_2016_2022.2$ing_pc)

# Compute income quintiles
elsoc_long_2016_2022.2 <- elsoc_long_2016_2022.2 %>% 
  group_by(ola) %>% 
  mutate(quintil = ntile(-desc(ing_pc), 5)) %>% 
  ungroup()

elsoc_long_2016_2022.2$quintil <- 
  factor(elsoc_long_2016_2022.2$quintil,
         levels = c(1, 2, 3, 4, 5),
         labels = c('Q1', 'Q2', 'Q3', 'Q4', 'Q5')) # Quintiles as factors


# Income group as percentage of median

# poverty (<50 per cent of median income), below average (>¼50 per cent and <100 per cent), above average (>¼100 per cent and <200 per cent), and affluence (>¼200 per cent).

elsoc_long_2016_2022.2<- 
  elsoc_long_2016_2022.2 %>% 
  group_by(ola) %>% 
  #compute median household pc income
  mutate(inc_pcmed=weighted.median(ing_pc,ponderador02,na.rm = T)) %>% 
  mutate(ratioincome=(ing_pc/inc_pcmed)*100) %>% 
  ungroup()

# elsoc_long_2016_2022.2[,c('idencuesta',"ola", 'm29_imp',"n_hogar","ing_pc","inc_pcmed")] %>% View()

elsoc_long_2016_2022.2$incomegrp=
  car::recode(elsoc_long_2016_2022.2$ratioincome,
              "0:49.9='Low';50:99.9='Below average';100:200='Above average';200.1:999999999999='Affluence'",
              levels =c("Low","Below average","Above average","Affluence"),as.factor = T)

frq(elsoc_long_2016_2022.2$incomegrp)
#reverse quintile, reference level is the highest quintile
#elsoc_long_2016_2022.2$quintil <- forcats::fct_rev(elsoc_long_2016_2022.2$quintil)

elsoc_long_2016_2022.2$quintil <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$quintil,
                      label = "Household income quintile per capita")  

sjmisc::frq(elsoc_long_2016_2022.2$quintil)

#include new quintile category with missing cases
elsoc_long_2016_2022.2$quintil1<-
  car::recode(elsoc_long_2016_2022.2$quintil, 
              "'Q1'='Q1';'Q2'= 'Q2';'Q3'='Q3';'Q4'='Q4';'Q5'='Q5'; NA='QNA'")

#elsoc_long_2016_2022.2$quintil1 <- factor(elsoc_long_2016_2022.2$quintil1, c("Q1","Q2","Q3","Q4","Q5","QNA"))

elsoc_long_2016_2022.2$quintil1 <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$quintil1,
                      label = "Household income quintile per capita (NA)") 
sjmisc::frq(elsoc_long_2016_2022.2$quintil1)

table(elsoc_long_2016_2022.2$incomegrp,elsoc_long_2016_2022.2$quintil1)

#Age Ranges
elsoc_long_2016_2022.2$edad <- 
  factor(car::recode(elsoc_long_2016_2022.2$m0_edad, 
                     "18:29=1;30:49=2;50:64=3;65:150=4"),
         labels = c('18-29', '30-49', '50-64', '65 or more'))
elsoc_long_2016_2022.2$edad <-
  sjlabelled::set_label(elsoc_long_2016_2022.2$edad, 
                        label = c("Age groups")) 
# Other controls______________________________________________________________
# Subjective social status: individual ____________________________

elsoc_long_2016_2022.2$ess <- 
as.numeric(elsoc_long_2016_2022.2$d01_01)
sjmisc::frq(elsoc_long_2016_2022.2$ess)
#elsoc_long_2016_2022.2$ess <- sjmisc::rec(elsoc_long_2016_2022.2$ess,rec = "rev")
#sjmisc::frq(elsoc_long_2016_2022.2$ess)

elsoc_long_2016_2022.2$ess <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ess,
                      label = "Subjective Social Status: individual")

sjmisc::frq(elsoc_long_2016_2022.2$ess)
# sjPlot::plot_frq(elsoc_long_2016_2022.2$ess)

# Subjective Social Class
elsoc_long_2016_2022.2$subclass <- elsoc_long_2016_2022.2$c33
```

```{r empst}
sjmisc::frq(elsoc_long_2016_2022.2$m02) 
elsoc_long_2016_2022.2$empst <- (car::recode(elsoc_long_2016_2022.2$m02,"1:3=1;4:9=0"))
# Ocupados:
# 
# Trabaja de manera remunerada con jornada completa
# Trabaja de manera remunerada a tiempo parcial o hace trabajos ocasionales
# Estudia y trabaja

# No Ocupados:
# 
# Solo estudia
# Jubilado o pensionado
# Desempleado, buscando trabajo
# Realiza tareas no remuneradas (quehaceres del hogar, cuidando niños u otras personas)
# Está enfermo o tiene una discapacidad
# No estudia, no trabaja y no busca trabajo

```

# Class Espinoza (2022)

```{r}
table(elsoc_long_2016_2022.2$empst)
frq(elsoc_long_2016_2022.2$m02)
frq(elsoc_long_2016_2022.2$egp11_r_label)
frq(elsoc_long_2016_2022.2$egp11_label)

elsoc_long_2016_2022.2$egp11_espinoza <- elsoc_long_2016_2022.2$egp11_r_label
# If person has Na in class and is inactive in the labor market, then impute the class of the head of household
elsoc_long_2016_2022.2$egp11_espinoza <- 
  ifelse(is.na(elsoc_long_2016_2022.2$egp11_r_label) & elsoc_long_2016_2022.2$empst==0,
         yes = elsoc_long_2016_2022.2$egp11_label,no = elsoc_long_2016_2022.2$egp11_r_label)

frq(
set_labels(x = elsoc_long_2016_2022.2$egp11_espinoza,labels = get_labels(elsoc_long_2016_2022.2$egp11_r_label))
  )

   #  1 |                I Higher Controllers |  1
   #  2 |                II Lower Controllers |  2
   #  3 |              IIIa Routine Nonmanual |  3
   #  4 |            IIIb Lower Sales-Service |  3
   #  5 |    IVa Self-employed with employees |  4
   #  6 | IVb Self-employed with no employees |  4
   #  7 |                V Manual Supervisors |  5
   #  8 |                   VI Skilled Worker |  6
   #  9 |               VIIa Unskilled Worker |  7
   # 10 |                     VIIb Farm Labor |  7
   # 11 |            IVc Self-employed Farmer |  7


elsoc_long_2016_2022.2$egp7_espinoza  <- 
  car::recode(elsoc_long_2016_2022.2$egp11_espinoza,
              recodes = "3:4=3;5:6=4;7=5;8=6;9:11=7") 

frq(elsoc_long_2016_2022.2$egp7_espinoza)

elsoc_long_2016_2022.2$egp7_espinoza <- 
  factor(elsoc_long_2016_2022.2$egp7_espinoza,
         levels = 1:7,
         labels = c("Service high","Service low","Rountine nonmanuals",
                    "Smallholders and self-employed",
                    "Technicians and supervisors","Skilled workers","Unskilled workers"))
frq(elsoc_long_2016_2022.2$egp7_espinoza)

elsoc_long_2016_2022.2 %>% filter(ola_w01==1,muestra==1) %>% sjPlot::plot_frq(egp7_espinoza)
elsoc_long_2016_2022.2 %>% filter(ola_w03==1,muestra==1) %>% sjPlot::plot_frq(egp7_espinoza)
elsoc_long_2016_2022.2 %>% filter(ola_w06==1,muestra==1) %>% sjPlot::plot_frq(egp7_espinoza)
```



```{r just-dist}
sjmisc::frq(elsoc_long_2016_2022.2$just_educ)
elsoc_long_2016_2022.2$just_educ <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$just_educ, 
                      label = "Market-based access to Education")

elsoc_long_2016_2022.2$just_educ_bi <- car::recode(elsoc_long_2016_2022.2$just_educ,"4:5=1;1:3=0",as.factor = T)

#
elsoc_long_2016_2022.2$just_pension <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$just_pension, 
                      label = "Market-based access to Pensions")

elsoc_long_2016_2022.2$just_pension_bi <- car::recode(elsoc_long_2016_2022.2$just_pension,"4:5=1;1:3=0",as.factor = T)

#
elsoc_long_2016_2022.2$just_salud <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$just_salud, 
                      label = "Market-based access to Health")

elsoc_long_2016_2022.2$just_salud_bi <- car::recode(elsoc_long_2016_2022.2$just_salud,"4:5=1;1:3=0",as.factor = T)


elsoc_long_2016_2022.2$perineq <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$perineq, 
                      label = "Concerns about economic inequality")

elsoc_long_2016_2022.2$effort <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$effort, 
                      label = "People are rewarded for their effort")

elsoc_long_2016_2022.2$talent <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$talent, 
                      label = "People are rewarded for their intelligence")



for (i in c("just_educ", "just_pension", "just_salud","perineq","effort","talent")) {
elsoc_long_2016_2022.2[[i]] <-
sjlabelled::set_labels(x = elsoc_long_2016_2022.2[[i]],
                       labels = c("Strongly disagree","Disagree",
                                  "Neither disagree nor agree",
                                  "Agree", "Strongly agree"))
}

elsoc_long_2016_2022.2$percger <-  elsoc_long_2016_2022.2$d03_01+1
elsoc_long_2016_2022.2$percger <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$percger, label = "Perceived Salary: Manager")
elsoc_long_2016_2022.2$percgerlog <- log(elsoc_long_2016_2022.2$percger)
elsoc_long_2016_2022.2$percgerlog <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$percgerlog, label = "Perceived Salary: Manager (log)")
elsoc_long_2016_2022.2$percgerptile <- ntile(elsoc_long_2016_2022.2$percger,100)
elsoc_long_2016_2022.2$percgerptile <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$percgerptile, label = "Perceived Salary: Manager (ptiles)")

elsoc_long_2016_2022.2 %>% select(percgerlog,percgerptile,percger) %>% sjPlot::tab_corr(triangle = "lower")

elsoc_long_2016_2022.2$justger <-  elsoc_long_2016_2022.2$d04_01+1
elsoc_long_2016_2022.2$justger <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$justger, label = "Just Salary: Manager")
elsoc_long_2016_2022.2$justgerlog <- log(elsoc_long_2016_2022.2$justger)
elsoc_long_2016_2022.2$justgerlog <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$justgerlog, label = "Just Salary: Manager (log)")
elsoc_long_2016_2022.2$justgerptile <- ntile(elsoc_long_2016_2022.2$justger,100)
elsoc_long_2016_2022.2$justgerptile <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$justgerptile, label = "Just Salary: Manager (ptiles)")


elsoc_long_2016_2022.2$percobr <-  elsoc_long_2016_2022.2$d03_02+1
elsoc_long_2016_2022.2$percobr <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$percobr, label = "Perceived Salary: Worker")
elsoc_long_2016_2022.2$percobrlog <- log(elsoc_long_2016_2022.2$percobr)
elsoc_long_2016_2022.2$percobrlog <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$percobrlog, label = "Perceived Salary: Worker (log)")
elsoc_long_2016_2022.2$percobrptile <- ntile(elsoc_long_2016_2022.2$percobr,100)
elsoc_long_2016_2022.2$percobrptile <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$percobrptile, label = "Perceived Salary: Worker (ptiles)")


elsoc_long_2016_2022.2 %>% select(percobr,percobrlog,percobrptile) %>% sjPlot::tab_corr(triangle = "lower")

elsoc_long_2016_2022.2$justobr <-  elsoc_long_2016_2022.2$d04_02+1
elsoc_long_2016_2022.2$justobr <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$justobr, label = "Just Salary: Worker")
elsoc_long_2016_2022.2$justobrlog <- sjlabelled::set_label(log(elsoc_long_2016_2022.2$justobr),"Just Salary: Worker (log)")
elsoc_long_2016_2022.2$justobrptile <- sjlabelled::set_label(ntile(elsoc_long_2016_2022.2$justobr,100),"Just Salary: Worker (ptiles)")

elsoc_long_2016_2022.2 %>% select(justobr,justobrlog,justobrptile) %>% sjPlot::tab_corr(triangle = "lower")

elsoc_long_2016_2022.2$percgap <-  elsoc_long_2016_2022.2$percger/elsoc_long_2016_2022.2$percobr
elsoc_long_2016_2022.2$percgap <-sjlabelled::set_label(x = elsoc_long_2016_2022.2$percgap, label = "Perceived Salary Gap")
elsoc_long_2016_2022.2$percgaplog <- sjlabelled::set_label(x = log(elsoc_long_2016_2022.2$percgap), label = "Perceived Salary Gap (log)")
elsoc_long_2016_2022.2$percgapptile <- sjlabelled::set_label(x = ntile(elsoc_long_2016_2022.2$percgap,100), label = "Perceived Salary Gap (ptiles)")

elsoc_long_2016_2022.2 %>% select(percgap,percgaplog,percgapptile) %>% sjPlot::tab_corr(triangle = "lower")

elsoc_long_2016_2022.2$justgap <-  elsoc_long_2016_2022.2$justger/elsoc_long_2016_2022.2$justobr
elsoc_long_2016_2022.2$justgap <- sjlabelled::set_label(x = elsoc_long_2016_2022.2$justgap, label = "Just Salary Gap")

elsoc_long_2016_2022.2$justgaplog <-  sjlabelled::set_label(x = log(elsoc_long_2016_2022.2$justgap), label = "Just Salary Gap (log)")
elsoc_long_2016_2022.2$justgapptile <-  sjlabelled::set_label(x = ntile(elsoc_long_2016_2022.2$justgap,100), label = "Just Salary Gap (ptiles)")
elsoc_long_2016_2022.2 %>% select(justgap,justgaplog,justgapptile) %>% sjPlot::tab_corr(triangle = "lower")
```


```{r prosocial}
elsoc_long_2016_2022.2$mem_jjvv <-to_factor(elsoc_long_2016_2022.2$mem_jjvv)
elsoc_long_2016_2022.2$mem_reli <-to_factor(elsoc_long_2016_2022.2$mem_reli)
elsoc_long_2016_2022.2$mem_poli <-to_factor(elsoc_long_2016_2022.2$mem_poli)
elsoc_long_2016_2022.2$mem_unio <-to_factor(elsoc_long_2016_2022.2$mem_unio)
elsoc_long_2016_2022.2$mem_grem <-to_factor(elsoc_long_2016_2022.2$mem_grem)
elsoc_long_2016_2022.2$mem_char <-to_factor(elsoc_long_2016_2022.2$mem_char)
elsoc_long_2016_2022.2$mem_spor <-to_factor(elsoc_long_2016_2022.2$mem_spor)
elsoc_long_2016_2022.2$mem_stud <-to_factor(elsoc_long_2016_2022.2$mem_stud)
elsoc_long_2016_2022.2$mem_othe <-to_factor(elsoc_long_2016_2022.2$mem_othe)

elsoc_long_2016_2022.2$ps_veci <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_veci, 
                      label = "I visited a neighbor's house")

elsoc_long_2016_2022.2$ps_comu <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_comu, 
                      label = "Attended a meeting on topics of public/community interest")


elsoc_long_2016_2022.2$ps_amig <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_amig, 
                      label = "Friends have visisted their home")

elsoc_long_2016_2022.2$ps_volu <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_volu, 
                      label = "Have done volunteer work")

elsoc_long_2016_2022.2$ps_dona <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_dona, 
                      label = "Has donated money to charity")

elsoc_long_2016_2022.2$ps_mone <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_mone, 
                      label = "Has lent $10,000 or more")


elsoc_long_2016_2022.2$ps_conv <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_conv, 
                      label = "Talked to a person in trouble or depressed")

elsoc_long_2016_2022.2$ps_job <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$ps_job, 
                      label = "Helped someone get a job")


for (i in c("ps_veci","ps_comu","ps_amig","ps_volu","ps_dona","ps_mone","ps_conv","ps_job")) {
elsoc_long_2016_2022.2[[i]] <-
sjlabelled::set_labels(x = elsoc_long_2016_2022.2[[i]],
                       labels = c("Never did it","Did it once or twice","Did it more than twice"))
}
```

## Networks 

```{r know}

# for the number of contacts for each occupation, the average value is used.

#"Conoce: Medico o doctor/a" 
sjmisc::frq(elsoc_long_2016_2022.2$r01_08)
elsoc_long_2016_2022.2$know_doctor <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_08,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_doctor)

#"Conoce: Gerente o director de gran empresa" (70)
sjmisc::frq(elsoc_long_2016_2022.2$r01_01)
elsoc_long_2016_2022.2$know_ceo <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_01,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_ceo)

elsoc_long_2016_2022.2$r01_06 #"Conoce: Abogado/a" (85)
sjmisc::frq(elsoc_long_2016_2022.2$r01_06)
elsoc_long_2016_2022.2$know_lawyer <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_06,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_lawyer)

#"Conoce: Profesor/a de universidad" (77)
sjmisc::frq(elsoc_long_2016_2022.2$r01_13)
elsoc_long_2016_2022.2$know_univprof <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_13,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_univprof)

# Middle status occupations-----------------------------------------------------

#"Conoce: Contador/a" (60)
sjmisc::frq(elsoc_long_2016_2022.2$r01_12)
elsoc_long_2016_2022.2$know_account <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_12,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_account)

#"Conoce: Secretario/a" (53)
sjmisc::frq(elsoc_long_2016_2022.2$r01_03)
elsoc_long_2016_2022.2$know_secret <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_03,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_secret)

#"Conoce: Vendedor de tienda o almacen" (43)
sjmisc::frq(elsoc_long_2016_2022.2$r01_05)
elsoc_long_2016_2022.2$know_shopassi <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_05,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_shopassi)

#"Conoce: Parvularia" (43)
sjmisc::frq(elsoc_long_2016_2022.2$r01_09)
elsoc_long_2016_2022.2$know_kinder <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_09,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_kinder)

# Lower status occupations-----------------------------------------------------
#"Conoce: Camarero o mozo" (34)
sjmisc::frq(elsoc_long_2016_2022.2$r01_11)
elsoc_long_2016_2022.2$know_waiter <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_11,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_waiter)

#"Conoce: Mecanico de autos" (34)
sjmisc::frq(elsoc_long_2016_2022.2$r01_04)
elsoc_long_2016_2022.2$know_carmech <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_04,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_carmech)

#"Conoce: Chofer de taxi o colectivo" (30)
sjmisc::frq(elsoc_long_2016_2022.2$r01_10)
elsoc_long_2016_2022.2$know_taxi <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_10,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_taxi)

#"Conoce: Vendedor ambulante" (29)
sjmisc::frq(elsoc_long_2016_2022.2$r01_02)
elsoc_long_2016_2022.2$know_stvend <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_02,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_stvend)

#"Conoce: Aseador/a de oficina" (16)
sjmisc::frq(elsoc_long_2016_2022.2$r01_07)
elsoc_long_2016_2022.2$know_cleaner <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_07,"1=0;2:7=1"))
sjmisc::frq(elsoc_long_2016_2022.2$know_cleaner)

elsoc_long_2016_2022.2 %>% 
  select(starts_with("know_")) %>% 
  names()

# Total of known occupations
n_ocupnames<- names(select(elsoc_long_2016_2022.2,starts_with("know_")))
elsoc_long_2016_2022.2$know_total <- rowSums(x = select(elsoc_long_2016_2022.2,n_ocupnames),na.rm = T)
summary(elsoc_long_2016_2022.2$know_total)
sjlabelled::set_label(elsoc_long_2016_2022.2$know_total) <- 'Total of known occupations'
sjPlot::plot_frq(elsoc_long_2016_2022.2$know_total,type = 'density')

# assing labels
professions <- c("Medical doctor", "Manager of a large firm", "Lawyer",
                "University Professor", "Accountant", "Secretary", "Shop assistant",
                "Preschool teacher", "Waiter", "Car mechanic", "Taxi driver",
                "Street vendor", "Office cleaner","Total")
labels <- paste0("Know: ",professions)
vars_tolabel <- names(select(elsoc_long_2016_2022.2 ,starts_with("know_")))
elsoc_long_2016_2022.2[,c(vars_tolabel)] <- set_label(x = elsoc_long_2016_2022.2[,c(vars_tolabel)],label = labels)
# elsoc_long_2016_2022.2[,c(vars_tolabel)] %>% View
```

```{r weak-strong}
find_var(data = elsoc_long_2016_2022.2,pattern = "r02_")
elsoc_long_2016_2022.2$tie_ceo<- car::recode(elsoc_long_2016_2022.2$r02_01,"1=1;2=0")	#Conocido es familiar: Gerente o director de gran empresa		
elsoc_long_2016_2022.2$tie_stv<- car::recode(elsoc_long_2016_2022.2$r02_02,"1=1;2=0")	#Conocido es familiar: Vendedor ambulante		
elsoc_long_2016_2022.2$tie_sec<- car::recode(elsoc_long_2016_2022.2$r02_03,"1=1;2=0")	#Conocido es familiar: Secretario/a		
elsoc_long_2016_2022.2$tie_mec<- car::recode(elsoc_long_2016_2022.2$r02_04,"1=1;2=0")	#Conocido es familiar: Mecanico de autos		
elsoc_long_2016_2022.2$tie_ven<- car::recode(elsoc_long_2016_2022.2$r02_05,"1=1;2=0")	#Conocido es familiar: Vendedor de tienda o almacen		
elsoc_long_2016_2022.2$tie_law<- car::recode(elsoc_long_2016_2022.2$r02_06,"1=1;2=0")	#Conocido es familiar: Abogado/a		
elsoc_long_2016_2022.2$tie_cle<- car::recode(elsoc_long_2016_2022.2$r02_07,"1=1;2=0")	#Conocido es familiar: Aseador/a de oficina		
elsoc_long_2016_2022.2$tie_doc<- car::recode(elsoc_long_2016_2022.2$r02_08,"1=1;2=0")	#Conocido es familiar: Medico o doctor/a		
elsoc_long_2016_2022.2$tie_par<- car::recode(elsoc_long_2016_2022.2$r02_09,"1=1;2=0")	#Conocido es familiar: Parvularia		
elsoc_long_2016_2022.2$tie_tax<- car::recode(elsoc_long_2016_2022.2$r02_10,"1=1;2=0")	#Conocido es familiar: Chofer de taxi o colectivo
elsoc_long_2016_2022.2$tie_wai<- car::recode(elsoc_long_2016_2022.2$r02_11,"1=1;2=0")	#Conocido es familiar: Camarero o mozo		
elsoc_long_2016_2022.2$tie_con<- car::recode(elsoc_long_2016_2022.2$r02_12,"1=1;2=0")	#Conocido es familiar: Contador/a		
elsoc_long_2016_2022.2$tie_pro<- car::recode(elsoc_long_2016_2022.2$r02_13,"1=1;2=0")	#Conocido es familiar: Profesor/a de universidad

frq(elsoc_long_2016_2022.2$tie_ceo)
frq(elsoc_long_2016_2022.2$tie_stv)
frq(elsoc_long_2016_2022.2$tie_sec)
frq(elsoc_long_2016_2022.2$tie_mec)
frq(elsoc_long_2016_2022.2$tie_ven)
frq(elsoc_long_2016_2022.2$tie_law)
frq(elsoc_long_2016_2022.2$tie_cle)
frq(elsoc_long_2016_2022.2$tie_doc)
frq(elsoc_long_2016_2022.2$tie_par)
frq(elsoc_long_2016_2022.2$tie_tax)
frq(elsoc_long_2016_2022.2$tie_wai)
frq(elsoc_long_2016_2022.2$tie_con)
has_stie<- rowSums(x = elsoc_long_2016_2022.2[,c("tie_ceo","tie_stv","tie_sec","tie_mec","tie_ven","tie_law","tie_cle","tie_doc","tie_par","tie_tax","tie_wai","tie_con","tie_pro")],na.rm = T)
sjPlot::plot_frq(has_stie)
strong_tie <- car::recode(has_stie,"1:13=1;0=0") 
table(strong_tie)
elsoc_long_2016_2022.2$strong_tie <- strong_tie #1 = "at least one or more is strong tie"
```


```{r status}
# Higher status occupations-----------------------------------------------------
sjmisc::frq(elsoc_long_2016_2022.2$know_doctor)#"Num. Conocidos: Medico o doctor/a" (88)
elsoc_long_2016_2022.2$isei_doctor <- ifelse(elsoc_long_2016_2022.2$know_doctor==1,88,NA)
sjmisc::frq(elsoc_long_2016_2022.2$isei_doctor)

sjmisc::frq(elsoc_long_2016_2022.2$know_ceo) #"Num. Conocidos: Gerente o director de gran empresa" (70)
elsoc_long_2016_2022.2$isei_ceo<- ifelse(elsoc_long_2016_2022.2$know_ceo==1,70,NA) #
sjmisc::frq(elsoc_long_2016_2022.2$isei_ceo)

sjmisc::frq(elsoc_long_2016_2022.2$know_lawyer) #"Num. Conocidos: Abogado/a" (85)
elsoc_long_2016_2022.2$isei_lawyer<- ifelse(elsoc_long_2016_2022.2$know_lawyer==1,85,NA) # #if know, impute 85
sjmisc::frq(elsoc_long_2016_2022.2$isei_lawyer)

sjmisc::frq(elsoc_long_2016_2022.2$know_univprof) #"Num. Conocidos: Profesor/a de universidad" (77)
elsoc_long_2016_2022.2$isei_univprof<- ifelse(elsoc_long_2016_2022.2$know_univprof==1,77,NA) #  #if know, impute 77
sjmisc::frq(elsoc_long_2016_2022.2$isei_univprof)

sjmisc::frq(elsoc_long_2016_2022.2$know_account) #"Num. Conocidos: Contador/a" (69)
elsoc_long_2016_2022.2$isei_account<- ifelse(elsoc_long_2016_2022.2$know_account==1,69,NA) # #if know, impute 60
sjmisc::frq(elsoc_long_2016_2022.2$isei_account)

# Middle status occupations-----------------------------------------------------

sjmisc::frq(elsoc_long_2016_2022.2$know_secret) #"Num. Conocidos: Secretario/a" (53)
elsoc_long_2016_2022.2$isei_secret<- ifelse(elsoc_long_2016_2022.2$know_secret==1,54,NA) # #if know, impute 53
sjmisc::frq(elsoc_long_2016_2022.2$isei_secret)

sjmisc::frq(elsoc_long_2016_2022.2$know_shopassi) #"Num. Conocidos: Vendedor de tienda o almacen" (43)
elsoc_long_2016_2022.2$isei_shopassi<- ifelse(elsoc_long_2016_2022.2$know_shopassi==1,43,NA) # #if know, impute 43
sjmisc::frq(elsoc_long_2016_2022.2$isei_shopassi)

sjmisc::frq(elsoc_long_2016_2022.2$know_kinder) #"Num. Conocidos: Parvularia" (43)
elsoc_long_2016_2022.2$isei_kinder<- ifelse(elsoc_long_2016_2022.2$know_kinder==1,43,NA) # #if know, impute 43
sjmisc::frq(elsoc_long_2016_2022.2$isei_kinder)

# Lower status occupations-----------------------------------------------------
sjmisc::frq(elsoc_long_2016_2022.2$know_waiter) #"Num. Conocidos: Camarero o mozo" (34)
elsoc_long_2016_2022.2$isei_waiter<- ifelse(elsoc_long_2016_2022.2$know_waiter==1,34,NA) #  #if know, impute 34
sjmisc::frq(elsoc_long_2016_2022.2$isei_waiter)

sjmisc::frq(elsoc_long_2016_2022.2$know_carmech)#"Num. Conocidos: Mecanico de autos" (34)
elsoc_long_2016_2022.2$isei_carmech<- ifelse(elsoc_long_2016_2022.2$know_carmech==1,34,NA) # #if know, impute 34
sjmisc::frq(elsoc_long_2016_2022.2$isei_carmech)

sjmisc::frq(elsoc_long_2016_2022.2$know_taxi) #"Num. Conocidos: Chofer de taxi o colectivo" (30)
elsoc_long_2016_2022.2$isei_taxi<- ifelse(elsoc_long_2016_2022.2$know_taxi==1,30,NA) #  #if know, impute 30
sjmisc::frq(elsoc_long_2016_2022.2$isei_taxi)

sjmisc::frq(elsoc_long_2016_2022.2$know_stvend)#"Num. Conocidos: Vendedor ambulante" (29)
elsoc_long_2016_2022.2$isei_stvend<- ifelse(elsoc_long_2016_2022.2$know_stvend==1,29,NA) # #if know, impute 29
sjmisc::frq(elsoc_long_2016_2022.2$isei_stvend)

sjmisc::frq(elsoc_long_2016_2022.2$know_cleaner) #"Num. Conocidos: Aseador/a de oficina" (16)
elsoc_long_2016_2022.2$isei_cleaner<- ifelse(elsoc_long_2016_2022.2$know_cleaner==1,16,NA) # #if know, impute 16
sjmisc::frq(elsoc_long_2016_2022.2$isei_cleaner)

# elsoc %>%
#   select(idencuesta,starts_with("isei_")) %>%
#   View
```

```{r risk}
unemrate2016<- c(0.011877027,0.088813421,0.125247476,0.13239874,0.163580309,0.00815314,0.135728506,0.073136997,0.260545028)
isco <- 1:9

cbind(isco,unemrate2016)

# Higher status occupations-----------------------------------------------------
elsoc_long_2016_2022.2$risk_doctor <- ifelse(elsoc_long_2016_2022.2$know_doctor==1,0.08881342,NA) #2000

elsoc_long_2016_2022.2$risk_ceo<- ifelse(elsoc_long_2016_2022.2$know_ceo==1,0.01187703,NA) # 1000

elsoc_long_2016_2022.2$risk_lawyer<- ifelse(elsoc_long_2016_2022.2$know_lawyer==1,0.08881342,NA) # 2000

elsoc_long_2016_2022.2$risk_univprof<- ifelse(elsoc_long_2016_2022.2$know_univprof==1,0.08881342,NA) # 2000

elsoc_long_2016_2022.2$risk_account<- ifelse(elsoc_long_2016_2022.2$know_account==1,0.08881342,NA) #2000

# Middle status occupations-----------------------------------------------------

elsoc_long_2016_2022.2$risk_secret<- ifelse(elsoc_long_2016_2022.2$know_secret==1,0.12524748,NA) # 3000

elsoc_long_2016_2022.2$risk_shopassi<- ifelse(elsoc_long_2016_2022.2$know_shopassi==1,0.16358031,NA) #5000

elsoc_long_2016_2022.2$risk_kinder<- ifelse(elsoc_long_2016_2022.2$know_kinder==1,0.08881342,NA) # 2000

# Lower status occupations-----------------------------------------------------
elsoc_long_2016_2022.2$risk_waiter<- ifelse(elsoc_long_2016_2022.2$know_waiter==1,0.16358031,NA) #  #5000
elsoc_long_2016_2022.2$risk_carmech<- ifelse(elsoc_long_2016_2022.2$know_carmech==1,0.13572851,NA) # 7000
elsoc_long_2016_2022.2$risk_taxi<- ifelse(elsoc_long_2016_2022.2$know_taxi==1,0.07313700,NA) #  #8000
elsoc_long_2016_2022.2$risk_stvend<- ifelse(elsoc_long_2016_2022.2$know_stvend==1,0.26054503,NA) # 9000
elsoc_long_2016_2022.2$risk_cleaner<- ifelse(elsoc_long_2016_2022.2$know_cleaner==1,0.26054503,NA) # 9000
```


```{r number}
# for the number of contacts for each occupation, the average value is used.

sjmisc::frq(elsoc_long_2016_2022.2$r01_08) #"Num. Conocidos: Medico o doctor/a" 
elsoc_long_2016_2022.2$n_doctor <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_08,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_doctor)
table(elsoc_long_2016_2022.2$n_doctor,elsoc_long_2016_2022.2$ola)


sjmisc::frq(elsoc_long_2016_2022.2$r01_01) #"Num. Conocidos: Gerente o director de gran empresa" (70)
elsoc_long_2016_2022.2$n_ceo <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_01,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_ceo)
table(elsoc_long_2016_2022.2$n_ceo,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_06) #"Num. Conocidos: Abogado/a" (85)
elsoc_long_2016_2022.2$n_lawyer <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_06,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_lawyer)
table(elsoc_long_2016_2022.2$n_lawyer,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_13) #"Num. Conocidos: Profesor/a de universidad" (77)
elsoc_long_2016_2022.2$n_univprof <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_13,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_univprof)
table(elsoc_long_2016_2022.2$n_univprof,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_12)#"Num. Conocidos: Contador/a" (60)
elsoc_long_2016_2022.2$n_account <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_12,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_account)
table(elsoc_long_2016_2022.2$n_account,elsoc_long_2016_2022.2$ola)


# Middle status occupations-----------------------------------------------------
sjmisc::frq(elsoc_long_2016_2022.2$r01_03) #"Num. Conocidos: Secretario/a" (53)
elsoc_long_2016_2022.2$n_secret <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_03,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_secret)
table(elsoc_long_2016_2022.2$n_secret,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_05) #"Num. Conocidos: Vendedor de tienda o almacen" (43)
elsoc_long_2016_2022.2$n_shopassi <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_05,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_shopassi)
table(elsoc_long_2016_2022.2$n_shopassi,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_09) #"Num. Conocidos: Parvularia" (43)
elsoc_long_2016_2022.2$n_kinder <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_09,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_kinder)
table(elsoc_long_2016_2022.2$n_kinder,elsoc_long_2016_2022.2$ola)

# Lower status occupations-----------------------------------------------------
sjmisc::frq(elsoc_long_2016_2022.2$r01_11) #"Num. Conocidos: Camarero o mozo" (34)
elsoc_long_2016_2022.2$n_waiter <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_11,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_waiter)
table(elsoc_long_2016_2022.2$n_waiter,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_04)#"Num. Conocidos: Mecanico de autos" (34)
elsoc_long_2016_2022.2$n_carmech <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_04,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_carmech)
table(elsoc_long_2016_2022.2$n_carmech,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_10) #"Num. Conocidos: Chofer de taxi o colectivo" (30)
elsoc_long_2016_2022.2$n_taxi <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_10,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_taxi)
table(elsoc_long_2016_2022.2$n_taxi,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_02) #"Num. Conocidos: Vendedor ambulante" (29)
elsoc_long_2016_2022.2$n_stvend <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_02,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_stvend)
table(elsoc_long_2016_2022.2$n_stvend,elsoc_long_2016_2022.2$ola)

sjmisc::frq(elsoc_long_2016_2022.2$r01_07) #"Num. Conocidos: Aseador/a de oficina" (17)
elsoc_long_2016_2022.2$n_cleaner <- as.numeric(car::recode(elsoc_long_2016_2022.2$r01_07,"1=0;2=1;3=3;4=6;5=9;6=13;7=17"))
sjmisc::frq(elsoc_long_2016_2022.2$n_cleaner)

table(elsoc_long_2016_2022.2$n_cleaner,elsoc_long_2016_2022.2$ola)

elsoc_long_2016_2022.2 %>% 
  select(starts_with("n_")) %>% 
  names()




# total number of contacts
n_ocupnames<- c("n_doctor","n_ceo","n_lawyer","n_univprof","n_account","n_secret","n_shopassi","n_kinder","n_waiter","n_carmech","n_taxi","n_stvend","n_cleaner")
elsoc_long_2016_2022.2$n_total <- rowSums(x = select(elsoc_long_2016_2022.2,n_ocupnames),na.rm = T)
summary(elsoc_long_2016_2022.2$n_total)
# # Function to check if all specified columns are NA
# all_na <- function(row) {
#   all(is.na(row))
# }
# 
# # Apply the function to the specified columns
# elsoc_long_2016_2022.2$all_na <- apply(elsoc_long_2016_2022.2[, c("n_doctor", "n_ceo", "n_lawyer", "n_univprof", "n_account", "n_secret", 
#                               "n_shopassi", "n_kinder", "n_waiter", "n_carmech", "n_taxi", "n_stvend", "n_cleaner")], 
#                      1, all_na)
# 
# select(elsoc_long_2016_2022.2,n_ocupnames,n_total,all_na) %>% View()
# # Print the data with the new column
# elsoc_long_2016_2022.2$n_total[elsoc_long_2016_2022.2$all_na==TRUE] <- NA
# summary(elsoc_long_2016_2022.2$n_total)


sjlabelled::set_label(elsoc_long_2016_2022.2$n_total) <- 'Total number of contacts'
sjPlot::plot_frq(elsoc_long_2016_2022.2$n_total,type = 'density')
elsoc_long_2016_2022.2 %>%  select(starts_with("n_")) %>% skimr::skim()
# elsoc_long_2016_2022.2 %>%  select(starts_with("n_")) %>% View
# List of variables to divide
variables <- elsoc_long_2016_2022.2 %>% 
  select("n_doctor","n_ceo","n_lawyer" ,"n_univprof","n_account","n_secret",
         "n_shopassi" ,"n_kinder","n_waiter","n_carmech","n_taxi",
         "n_stvend","n_cleaner") %>% 
  names()

# Divide each variable by the divisor and create new variables
for (i in variables) {
  z <- paste0("pct_",i)
  z <- gsub("n_", "", z)
  elsoc_long_2016_2022.2[[z]] <- as.numeric(elsoc_long_2016_2022.2[[i]]/elsoc_long_2016_2022.2$n_total)
}

# assing labels
professions <- c("Medical doctor", "Manager of a large firm", "Lawyer",
                "University Professor", "Accountant", "Secretary", "Shop assistant",
                "Preschool teacher", "Waiter", "Car mechanic", "Taxi driver",
                "Street vendor", "Office cleaner")
labels <- paste0("Percentage of contacts: ",professions)

vars_tolabel <- names(select(elsoc_long_2016_2022.2, 
                             "pct_doctor","pct_ceo","pct_lawyer","pct_univprof",
                             "pct_account","pct_secret","pct_shopassi","pct_kinder",
                             "pct_waiter","pct_carmech","pct_taxi","pct_stvend","pct_cleaner"))

elsoc_long_2016_2022.2[,c(vars_tolabel)] <- set_label(x = elsoc_long_2016_2022.2[,c(vars_tolabel)],label = labels)
# elsoc[,c(vars_tolabel)] %>% View
```

```{r social-capital}
# Social capital measures
isei_ocupnames<- names(select(elsoc_long_2016_2022.2,starts_with("isei_")))
n_ocupnames <- names(select(elsoc_long_2016_2022.2,starts_with("n_"),-n_total,-"n_visitas_entr"))

# number of high status contacts
elsoc_long_2016_2022.2$num_high <-
  rowSums(x = select(elsoc_long_2016_2022.2,c("n_doctor","n_ceo","n_lawyer", "n_univprof","n_account")),na.rm = T)

elsoc_long_2016_2022.2$n_high <- 
  rowSums(x = select(elsoc_long_2016_2022.2,c("know_doctor","know_ceo","know_lawyer", "know_univprof","know_account")),na.rm = T)
sjlabelled::set_label(elsoc_long_2016_2022.2$n_high) <- 'Number of high status contacts'
sjPlot::plot_frq(elsoc_long_2016_2022.2$n_high,type = 'density')

# percentage of high status contacts
# elsoc_long_2016_2022.2$pct_high <- (elsoc_long_2016_2022.2$n_high/elsoc_long_2016_2022.2$n_total)*100
elsoc_long_2016_2022.2$pct_high <- (elsoc_long_2016_2022.2$n_high/elsoc_long_2016_2022.2$know_total)*100
elsoc_long_2016_2022.2$porc_high <- (elsoc_long_2016_2022.2$num_high/elsoc_long_2016_2022.2$n_total)*100
sjlabelled::set_label(elsoc_long_2016_2022.2$pct_high ) <- 'Percentage of high status contacts'
sjlabelled::set_label(elsoc_long_2016_2022.2$porc_high) <- 'Percentage of high status contacts'
sjPlot::plot_frq(elsoc_long_2016_2022.2$pct_high,type = 'density')

# number of middle status contacts
elsoc_long_2016_2022.2$num_middle <-
  rowSums(x = select(elsoc_long_2016_2022.2,c("n_secret","n_shopassi","n_kinder")),na.rm = T)
elsoc_long_2016_2022.2$n_middle <-
  rowSums(x = select(elsoc_long_2016_2022.2,c("know_secret","know_shopassi","know_kinder")),na.rm = T)
sjlabelled::set_label(elsoc_long_2016_2022.2$n_middle) <- 'Number of middle status contacts'
sjPlot::plot_frq(elsoc_long_2016_2022.2$n_middle,type = 'density')

# percentage of middle status contacts
elsoc_long_2016_2022.2$pct_middle <- (elsoc_long_2016_2022.2$n_middle/elsoc_long_2016_2022.2$know_total)*100
elsoc_long_2016_2022.2$porc_middle <- (elsoc_long_2016_2022.2$num_middle/elsoc_long_2016_2022.2$n_total)*100
sjlabelled::set_label(elsoc_long_2016_2022.2$porc_middle) <- 'Percentage of middle status contacts'
sjlabelled::set_label(elsoc_long_2016_2022.2$pct_middle) <- 'Percentage of middle status contacts'
sjPlot::plot_frq(elsoc_long_2016_2022.2$pct_middle,type = 'density')

# number of low status contacts
elsoc_long_2016_2022.2$num_low <-
  rowSums(x = select(elsoc_long_2016_2022.2,c("n_waiter","n_carmech","n_taxi","n_stvend","n_cleaner")),na.rm = T)
elsoc_long_2016_2022.2$n_low <- 
  rowSums(x = select(elsoc_long_2016_2022.2,c("know_waiter","know_carmech","know_taxi","know_stvend","know_cleaner")),na.rm = T)
sjlabelled::set_label(elsoc_long_2016_2022.2$n_low) <- 'Number of low status contacts'
sjPlot::plot_frq(elsoc_long_2016_2022.2$n_low,type = 'density')
sjPlot::plot_frq(elsoc_long_2016_2022.2$num_low,type = 'density')

# percentage of low status contacts
elsoc_long_2016_2022.2$porc_low <- (elsoc_long_2016_2022.2$num_low/elsoc_long_2016_2022.2$n_total)*100
sjlabelled::set_label(elsoc_long_2016_2022.2$porc_low) <- 'Percentage of low status contacts'

elsoc_long_2016_2022.2$pct_low <- (elsoc_long_2016_2022.2$n_low/elsoc_long_2016_2022.2$know_total)*100
sjlabelled::set_label(elsoc_long_2016_2022.2$pct_low) <- 'Percentage of low status contacts'
sjPlot::plot_frq(elsoc_long_2016_2022.2$pct_low,type = 'density')
sjPlot::plot_frq(elsoc_long_2016_2022.2$porc_low,type = 'density')

# Average ISEI 
elsoc_long_2016_2022.2$isei_avg <- rowMeans(x = select(elsoc_long_2016_2022.2,isei_ocupnames),na.rm = T)
sjlabelled::set_label(elsoc_long_2016_2022.2$isei_avg) <- 'Average contact prestige'
skimr::skim(elsoc_long_2016_2022.2$isei_avg)
sjPlot::plot_frq(elsoc_long_2016_2022.2$isei_avg,type = 'density')

# Total ISEI 
elsoc_long_2016_2022.2$isei_tot <- rowSums(x = select(elsoc_long_2016_2022.2,isei_ocupnames),na.rm = T)
sjlabelled::set_label(elsoc_long_2016_2022.2$isei_tot) <- 'Total contact prestige'
sjmisc::frq(elsoc_long_2016_2022.2$isei_avg)
sjPlot::plot_frq(elsoc_long_2016_2022.2$isei_avg,type = 'density')


elsoc_long_2016_2022.2$isei_sd<- transform(elsoc_long_2016_2022.2[c(isei_ocupnames)], isei_sd=apply(elsoc_long_2016_2022.2[c(isei_ocupnames)],1, sd, na.rm = TRUE))$isei_sd
sjlabelled::set_label(elsoc_long_2016_2022.2$isei_sd) <- 'Standard deviation contact prestige'
skimr::skim(elsoc_long_2016_2022.2$isei_sd)
sjPlot::plot_frq(elsoc_long_2016_2022.2$isei_sd,type = 'density')

# skimr::skim(elsoc_long_2016_2022.2$isei_tot/elsoc_long_2016_2022.2$n_total)
# skimr::skim(elsoc_long_2016_2022.2$isei_tot/elsoc_long_2016_2022.2$know_total)
# skimr::skim(elsoc_long_2016_2022.2$isei_avg)


# max ISEI 
elsoc_long_2016_2022.2 <- elsoc_long_2016_2022.2 %>% 
mutate(isei_max = do.call(pmax, c(select(., isei_ocupnames), na.rm = TRUE)))
sjlabelled::set_label(elsoc_long_2016_2022.2$isei_max) <- 'Maximum contact prestige'
sjmisc::frq(elsoc_long_2016_2022.2$isei_max)
sjPlot::plot_frq(elsoc_long_2016_2022.2$isei_max)

# min ISEI
elsoc_long_2016_2022.2 <- elsoc_long_2016_2022.2 %>% 
mutate(isei_min = do.call(pmin, c(select(., isei_ocupnames), na.rm = TRUE)))
sjlabelled::set_label(elsoc_long_2016_2022.2$isei_min) <- 'Minimum contact prestige'
sjmisc::frq(elsoc_long_2016_2022.2$isei_min)
sjPlot::plot_frq(elsoc_long_2016_2022.2$isei_min)

# range ISEI
table(elsoc_long_2016_2022.2$know_total>=2)
elsoc_long_2016_2022.2$isei_range <- ifelse(elsoc_long_2016_2022.2$know_total>=2,(elsoc_long_2016_2022.2$isei_max - elsoc_long_2016_2022.2$isei_min),no = NA)

sjlabelled::set_label(elsoc_long_2016_2022.2$isei_range) <- 'Range contact prestige'
sjmisc::frq(elsoc_long_2016_2022.2$isei_range)
# sjPlot::plot_frq(elsoc_long_2016_2022.2$isei_range)
# elsoc_long_2016_2022.2 %>% select(starts_with("isei_")) %>% View

# GGally::ggpairs(elsoc_long_2016_2022.2[,c("isei_avg","isei_max","isei_range",
#                  "n_total","n_high","n_middle","n_low",
#                  "pct_high","pct_middle","pct_low")],
#         title="Social capital measures")



# Average RISK 
names(select(elsoc_long_2016_2022.2,starts_with("risk_")))
elsoc_long_2016_2022.2$risk_avg <- rowMeans(x = select(elsoc_long_2016_2022.2, names(select(elsoc_long_2016_2022.2,starts_with("risk_")))),na.rm = T)
sjlabelled::set_label(elsoc_long_2016_2022.2$risk_avg) <- 'Average contact unemployment risk'
skimr::skim(elsoc_long_2016_2022.2$risk_avg)
hist(elsoc_long_2016_2022.2$risk_avg)
```

```{r heterogeneity}
## Heterogeneidad de la RED ------------------------------------------------
##Ocupaciones
# calculate the proportion for each occupation and then apply a cuadratic term
elsoc_long_2016_2022.2$prop_doctor<-((elsoc_long_2016_2022.2$n_doctor/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_ceo<-((elsoc_long_2016_2022.2$n_ceo/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_lawyer<-((elsoc_long_2016_2022.2$n_lawyer/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_univprof<-((elsoc_long_2016_2022.2$n_univprof/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_account<-((elsoc_long_2016_2022.2$n_account/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_secret<-((elsoc_long_2016_2022.2$n_secret/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_shopassi<-((elsoc_long_2016_2022.2$n_shopassi/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_kinder<-((elsoc_long_2016_2022.2$n_kinder/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_waiter<-((elsoc_long_2016_2022.2$n_waiter/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_carmech<-((elsoc_long_2016_2022.2$n_carmech/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_taxi<-((elsoc_long_2016_2022.2$n_taxi/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_stvend<-((elsoc_long_2016_2022.2$n_stvend/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_cleaner<-((elsoc_long_2016_2022.2$n_cleaner/elsoc_long_2016_2022.2$n_total))^2

prop_ocup <- 
c("prop_doctor","prop_ceo","prop_lawyer","prop_univprof","prop_account",
"prop_secret","prop_shopassi","prop_kinder","prop_waiter","prop_carmech",
"prop_taxi","prop_stvend","prop_cleaner")
# 1 - sum of square probabilities of knowing occupation
elsoc_long_2016_2022.2$diversity=1-rowSums(elsoc_long_2016_2022.2[,prop_ocup])
sjlabelled::set_label(elsoc_long_2016_2022.2$diversity) <- "Network diversity (D-Simpson)"


# https://www.omnicalculator.com/statistics/index-of-qualitative-variation#how-to-use-our-iqv-calculator
k <- 13
sq100<- 100^2
sum2<- rowSums(elsoc_long_2016_2022.2[,prop_ocup])
elsoc_long_2016_2022.2$iqv <- (k*(sq100-sum2)) / (sq100*(k-1))

# https://www.cienciasinseso.com/en/measures-of-dispersion-of-qualitative-variables/

elsoc_long_2016_2022.2$homogeneity=rowSums(elsoc_long_2016_2022.2[,prop_ocup])
sjlabelled::set_label(elsoc_long_2016_2022.2$homogeneity) <- "Network Homogeneity (D-Simpson)"

elsoc_long_2016_2022.2$prop_upper<-((elsoc_long_2016_2022.2$num_high/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_interm<-((elsoc_long_2016_2022.2$num_middle/elsoc_long_2016_2022.2$n_total))^2
elsoc_long_2016_2022.2$prop_working<-((elsoc_long_2016_2022.2$num_low/elsoc_long_2016_2022.2$n_total))^2

elsoc_long_2016_2022.2$diversityclass=1-rowSums(elsoc_long_2016_2022.2[,c("prop_upper","prop_interm","prop_working")])
elsoc_long_2016_2022.2$iqvclass <- elsoc_long_2016_2022.2$diversityclass/(1-(1/3))
cor(elsoc_long_2016_2022.2[,c("diversity","iqv","diversityclass","iqvclass")],use = "complete.obs")
```

```{r cross-class}
summary(elsoc_long_2016_2022.2$num_high)
summary(elsoc_long_2016_2022.2$num_middle)
summary(elsoc_long_2016_2022.2$num_low)


elsoc_long_2016_2022.2$know_low <- car::recode(elsoc_long_2016_2022.2$num_low,recodes = "0=0;else=1")
elsoc_long_2016_2022.2$know_mid <- car::recode(elsoc_long_2016_2022.2$num_middle,recodes = "0=0;else=1")
elsoc_long_2016_2022.2$know_hig <- car::recode(elsoc_long_2016_2022.2$num_high,recodes = "0=0;else=1")
elsoc_long_2016_2022.2$crossclass<- rowSums(elsoc_long_2016_2022.2[,c("know_low","know_mid","know_hig")])
table(elsoc_long_2016_2022.2$crossclass)
```


# Diversity Otero & Mendoza 2023 

```{r}
elsoc_long_2016_2022.2 %>% 
  # filter(ola==3) %>%
  select(diversityclass,isei_range,isei_sd,know_total,crossclass) %>% 
  sjPlot::tab_corr()


df_cfa<- 
elsoc_long_2016_2022.2 %>% 
  # filter(ola==1) %>%
  select(idencuesta,diversity,diversityclass,isei_range,isei_sd,know_total,crossclass,ponderador_long_total,ponderador02)

# Model original
model_original <- 'diversitycfa =~ diversityclass+isei_range+isei_sd+know_total+crossclass'
fitoriginal<- lavaan::cfa(model = model_original,data = df_cfa,cluster = "idencuesta",sampling.weights = "ponderador_long_total")
lavaan::summary(fitoriginal,standardized=T,fit.measures=T)

# Model w/o isei range
model_wo_range <- 'diversitycfa_norange =~ diversityclass+crossclass + isei_sd+know_total'
fit_range<- lavaan::cfa(model = model_wo_range,data = df_cfa,cluster = "idencuesta",
                        sampling.weights = "ponderador_long_total"
                        )
lavaan::summary(fit_range,standardized=T,fit.measures=T)

# Model w/o isei sd
model_wo_sd <- 'diversitycfa_nosde =~ diversityclass+isei_range+know_total+crossclass'
fit_sd<- lavaan::cfa(model = model_wo_sd,data = df_cfa,cluster = "idencuesta",sampling.weights = "ponderador_long_total")
lavaan::summary(fit_sd,standardized=T,fit.measures=T)

models<- list(fitoriginal,fit_range,fit_sd)
texreg::knitreg(models)

# Model using blau, sd, extensivity and number of different "social classes" known (cross-class) is the best

factorscores<- lavaan::lavPredict(fit_range,newdata = elsoc_long_2016_2022.2)
idx <- lavaan::lavInspect(fit_range, "case.idx")
fscores <- lavaan::lavPredict(fit_range)
## loop over factors
for (fs in colnames(fscores)) {
  elsoc_long_2016_2022.2[idx, fs] <- fscores[ , fs]
}
names(elsoc_long_2016_2022.2)
elsoc_long_2016_2022.2 <- elsoc_long_2016_2022.2 %>% rename(diversitycfa=diversitycfa_norange)

df_pca<- 
elsoc_long_2016_2022.2 %>% 
  # filter(ola==1) %>%
  select(diversityclass,isei_range,isei_sd,know_total,crossclass) 
pca_fit<- psych::pca(r = df_pca,nfactors = 1,rotate = "varimax",scores = T)
elsoc_long_2016_2022.2$diversitypca <- pca_fit$scores

plot(pca_fit,labels = c(names(df_pca)))
#                 PC1   h2    u2 com
# diversityclass 0.86 0.73 0.267   1
# isei_range     0.92 0.85 0.150   1
# isei_sd        0.78 0.61 0.390   1
# know_total     0.87 0.75 0.248   1
# crossclass     0.96 0.93 0.074   1
# 
#                 PC1
# SS loadings    3.87
# Proportion Var 0.77
# 
# Mean item complexity =  1
# Test of the hypothesis that 1 component is sufficient.Here is the information converted into a table:

#This table format organizes each measure with a description placeholder, making it easy to fill in additional details as needed.
# 
# The root mean square of the residuals (RMSR) is  0.12 
#  with the empirical chi square  5532.43  with prob <  0 
```

# Homogeneity ISEI

```{r}
elsoc_long_2016_2022.2$isei08 <- as.numeric(DIGCLASS::isco88_to_isei(x = elsoc_long_2016_2022.2$isco88_3))
summary(elsoc_long_2016_2022.2$isei08)

elsoc_long_2016_2022.2$isei08res <- as.numeric(DIGCLASS::isco88_to_isei(x = elsoc_long_2016_2022.2$isco88res_3))
summary(elsoc_long_2016_2022.2$isei08res)


View(elsoc_long_2016_2022.2[,c("isei08res","isei_avg","absolute_values")])

elsoc_long_2016_2022.2$isei08res - elsoc_long_2016_2022.2$isei_avg


# Step 1: Calculate absolute values
elsoc_long_2016_2022.2$absolute_values <- (elsoc_long_2016_2022.2$isei08res/elsoc_long_2016_2022.2$isei_avg)
# elsoc_long_2016_2022.2$absolute_values <- (elsoc_long_2016_2022.2$isei08res-elsoc_long_2016_2022.2$isei_avg) 
# elsoc_long_2016_2022.2$absolute_values[elsoc_long_2016_2022.2$absolute_values==0] <- NA
hist(elsoc_long_2016_2022.2$absolute_values);summary(elsoc_long_2016_2022.2$absolute_values)

# Step 2: Add 1 to all values to eliminate zeros
elsoc_long_2016_2022.2$modified_values <- elsoc_long_2016_2022.2$absolute_values 
hist(elsoc_long_2016_2022.2$modified_values);summary(elsoc_long_2016_2022.2$modified_values)

# Step 3: Reverse the order of the scale
elsoc_long_2016_2022.2$reversed_values <-
  max(elsoc_long_2016_2022.2$modified_values,na.rm = T) - elsoc_long_2016_2022.2$modified_values
hist(elsoc_long_2016_2022.2$reversed_values);summary(elsoc_long_2016_2022.2$reversed_values)
elsoc_long_2016_2022.2$homisei <- elsoc_long_2016_2022.2$reversed_values
sjlabelled::set_label(x = elsoc_long_2016_2022.2$homisei) <- "Network homogeneity (ISEI respondent)"
hist(elsoc_long_2016_2022.2$homisei);summary(elsoc_long_2016_2022.2$homisei)
```

```{r}
elsoc_long_2016_2022.2 %>% 
  select(isei08,isei08res, diversity,diversityclass,diversitypca,diversitycfa,homisei) %>% correlation::correlation() %>% summary()
```


```{r control}
# Political position ____________________________
elsoc_long_2016_2022.2$pos_id <-
factor(
  car::recode(
    elsoc_long_2016_2022.2$c15,
    "c(11,12,-888,-999)='Does not identify';c(0,1,2,3,4)='Left';c(5)='Center';c(6,7,8,9,10)='Right'"
  ),  levels = c('Left', 'Center', 'Right', 'Does not identify')
)

elsoc_long_2016_2022.2$pos_id <- factor(elsoc_long_2016_2022.2$pos_id,
                                      levels = levels(elsoc_long_2016_2022.2$pos_id))

elsoc_long_2016_2022.2$pos_id <- 
sjlabelled::set_label(x = elsoc_long_2016_2022.2$pos_id, 
                      label = "Political identification") 

sjmisc::frq(elsoc_long_2016_2022.2$pos_id)
```

# Network - migrants

```{r}
sjPlot::tab_xtab(elsoc_long_2016_2022.2$r03_04,elsoc_long_2016_2022.2$ola)

frq(elsoc_long_2016_2022.2$r03_04)

elsoc_long_2016_2022.2$num_mig <- 
  car::recode(elsoc_long_2016_2022.2$r03_04,recodes = "1=0;2=1;3=3;4=6;5=9;6=13;7=17",as.numeric = T)

sjPlot::tab_xtab(elsoc_long_2016_2022.2$r05_02,elsoc_long_2016_2022.2$ola)
frq(elsoc_long_2016_2022.2$r05_02)
elsoc_long_2016_2022.2$friend_mig <- 
  as.numeric(car::recode(elsoc_long_2016_2022.2$r05_02,recodes = "1=0;c(2,3,4,5)=1",as.numeric = T))
sjPlot::tab_xtab(elsoc_long_2016_2022.2$friend_mig,elsoc_long_2016_2022.2$ola)

sjPlot::tab_xtab(elsoc_long_2016_2022.2$r05_01,elsoc_long_2016_2022.2$ola)
frq(elsoc_long_2016_2022.2$r05_01)
elsoc_long_2016_2022.2$know_mig <- 
  as.numeric(car::recode(elsoc_long_2016_2022.2$r05_01,recodes = "1=0;c(2,3,4,5)=1",as.numeric = T))
sjPlot::tab_xtab(elsoc_long_2016_2022.2$know_mig,elsoc_long_2016_2022.2$ola)
```

# Variables fixed to wave 1

```{r fix-vars-t1}
library(panelr)
elsoc_long <-
elsoc_long_2016_2022.2 %>% 
  # filter(muestra==1) %>% 
  select(idencuesta,ola,muestra,sexo,edad,educ,educyear,ing_pc,ing_pc_eq,
         quintil,quintil1,incomegrp,egp11_label,egp11_r_label,egp7_espinoza,
         subclass,ess,
         egp8_r_label,egp8_r_label_na,m02,isei08res,comuna,
         oesch8_label,oesch5_label,oesch8_r_label,oesch5_r_label, strong_tie)  

elsoc <- panel_data(elsoc_long, id = idencuesta, wave = ola)
elsoc_wide <- widen_panel(elsoc, separator = "_")

elsoc_wide$inc_pc_eq_diff<- as.numeric(elsoc_wide$quintil_1)-as.numeric(elsoc_wide$quintil_5)
elsoc_wide$inc_mob<-elsoc_wide$inc_pc_eq_diff

elsoc_wide$inc_mob <- car::recode(elsoc_wide$inc_mob,
                                  "c(-4,-3,-2,-1)='down';0='stable';c(4,3,2,1)='up'")
frq(elsoc_wide$inc_mob)

names(elsoc_wide)
elsoc_fix_t1 <- elsoc_wide %>% select(idencuesta,
                                      sexo_fx=sexo_1,
                                      edad_fx=edad_1,
                                      educ_fx=educ_1,
                                      educyear_fx=educyear_1,
                                      quintil_fx=quintil_1,
                                      quintil1_fx=quintil1_1,
                                      incomegrp_fx=incomegrp_1,
                                      egp11_label="egp11_label_1",
                                      egp11_r_label="egp11_r_label_1",
                                      egp8_r_label="egp8_r_label_1",
                                      egp8_r_label_na="egp8_r_label_na_1",
                                      isei08res_fx=isei08res_1,
                                      egp7_espinoza_fx=egp7_espinoza_1,
                                      subclass_fx=subclass_1,
                                      ess_fx=ess_1,
                                      m02=m02_1,
                                      oesch8_fx=oesch8_label_1,
                                      oesch5_fx=oesch5_label_1,
                                      oesch8_r_fx=oesch8_r_label_1, 
                                      inc_mob,
                                      oesch5_r_fx=oesch5_r_label_1,
                                      strong_tie_t1=strong_tie_1
                                      )

elsoc_fix_t1$isei08res_ter_fx <- as.factor(ntile(elsoc_fix_t1$isei08res_fx,3));frq(elsoc_fix_t1$isei08res_ter_fx)

skimr::skim(elsoc_fix_t1)
# Check how respondent's class cross with head of household's class
sjPlot::tab_xtab(elsoc_fix_t1$egp11_r_label,elsoc_fix_t1$egp11_label,show.na = T)
# create a variable based on respondent's class
elsoc_fix_t1$egp11_hh_label <- elsoc_fix_t1$egp11_r_label 

frq(elsoc_fix_t1$egp11_hh_label)

# Create Class variable replacing by head of household--------------------------

## EGP CLASS SCHEME ------------------------------------------------------------
# If respondent's class is missing, replace with head of household's class
elsoc_fix_t1$egp11_hh_label <- ifelse(is.na(elsoc_fix_t1$egp11_hh_label),
                                       yes =  elsoc_fix_t1$egp11_label,
                                       no = elsoc_fix_t1$egp11_hh_label)

elsoc_fix_t1$egp11_hh_label <- factor(elsoc_fix_t1$egp11_hh_label,
                                      labels = levels(elsoc_fix_t1$egp11_r_label))
frq(elsoc_fix_t1$egp11_hh_label) # this is the base for the EGP 11 class Scheme for the household 

# EGP 8 household
elsoc_fix_t1$egp8_hh_label <- 
  car::recode(var = elsoc_fix_t1$egp11_hh_label,
  recodes = 
  "c('IVa Self-employed with employees','IVb Self-employed with no employees','IVc Self-employed Farmer') = 'IV Self-employed';
  c('VIIa Unskilled Worker','VIIb Farm Labor') = 'VII Unskilled Workers'")

# EGP 8 household including residual class or "underclass"
elsoc_fix_t1$egp8_hh_label_na <- elsoc_fix_t1$egp8_hh_label
egp8lab <- levels(elsoc_fix_t1$egp8_hh_label_na)

elsoc_fix_t1$flag <- ifelse(is.na(elsoc_fix_t1$egp8_hh_label),yes = 1,no = 0)  # dummy is missing in respondents social class
frq(elsoc_fix_t1$flag)
frq(elsoc_long_2016_2022.2$m02) # check employment status
# Ocupados:
 # Trabaja de manera remunerada con jornada completa
# Trabaja de manera remunerada a tiempo parcial o hace trabajos ocasionales
# Estudia y trabaja

# No Ocupados:
# Solo estudia
# Jubilado o pensionado
# Desempleado, buscando trabajo
# Realiza tareas no remuneradas (quehaceres del hogar, cuidando niños u otras personas)
# Está enfermo o tiene una discapacidad
# No estudia, no trabaja y no busca trabajo

elsoc_fix_t1$egp8_hh_label_na <- 
  ifelse(elsoc_fix_t1$m02 %in% c(4,6,7,8,9) & elsoc_fix_t1$flag ==1,
         yes = 9,no= elsoc_fix_t1$egp8_hh_label_na) # Never worked and long-term unemployed
elsoc_fix_t1$egp8_hh_label_na <- 
  ifelse(elsoc_fix_t1$m02 %in% c(5) & elsoc_fix_t1$flag ==1,
         yes = 10,no= elsoc_fix_t1$egp8_hh_label_na) # retired
frq(elsoc_fix_t1$egp8_hh_label_na)

elsoc_fix_t1$egp8_hh_label_na <- 
  factor(elsoc_fix_t1$egp8_hh_label_na,
         labels = c(egp8lab,"Never worked and long-term unemployed","Retired"))
frq(elsoc_fix_t1$egp8_hh_label_na)

elsoc_fix_t1$m02 <-NULL
elsoc_fix_t1$flag <- NULL


## OESCH CLASS SCHEME ------------------------------------------------------------
# If respondent's class is missing, replace with head of household's class
elsoc_fix_t1$oesch8_hh_label <-
  ifelse(
    is.na(elsoc_fix_t1$oesch8_r_fx),
    yes =  elsoc_fix_t1$oesch8_fx,
    no = elsoc_fix_t1$oesch8_r_fx
  )
frq(elsoc_fix_t1$oesch8_hh_label)
elsoc_fix_t1$oesch8_hh_label <- 
  factor(
    elsoc_fix_t1$oesch8_hh_label,
    labels = c(
      "Self-employed professionals and large employers",
      "Small business owners",
      "Technical professionals",
      "Production workers",
      "Associate managers",
      "Clerks",
      "Socio-cultural professionals",
      "Service workers"
    )
  )

elsoc_fix_t1$oesch8_hh_label <-
  factor(
    elsoc_fix_t1$oesch8_hh_label,
    levels = c(
      "Small business owners",
      "Self-employed professionals and large employers",
      "Associate managers",
      "Technical professionals",
      "Socio-cultural professionals",
      "Clerks",
      "Production workers",
      "Service workers"
    )
  )

frq(elsoc_fix_t1$oesch8_hh_label) # 8 Oesch

# (1) the upper-middle class of managers, professionals and large employers; 
# (2) the lower-middle class of associate managers, semiprofessionals and technicians;
# (3) small business owners including selfemployed artisans, shop owners and farmers; 
# (4) the skilled working class of craftsmen, office clerks, sales and service workers and 
# (5) the unskilled working class of operatives, farmhands and unskilled service workers.

elsoc_fix_t1$oesch5_hh_label <-
  ifelse(
    is.na(elsoc_fix_t1$oesch5_r_fx),
    yes =  elsoc_fix_t1$oesch5_fx,
    no = elsoc_fix_t1$oesch5_r_fx
  )

elsoc_fix_t1$oesch5_hh_label <- 
  factor(
    elsoc_fix_t1$oesch5_hh_label,
    labels = levels(elsoc_fix_t1$oesch5_r_fx)
  )
frq(elsoc_fix_t1$oesch5_hh_label)
# Join time-invariant variables to data ---------------------------------------
elsoc_fix_t1$idencuesta <- as.numeric(as.character(elsoc_fix_t1$idencuesta))
elsoc_long <-
left_join(x= elsoc_long_2016_2022.2, y = elsoc_fix_t1,by="idencuesta") %>% 
  select(-ends_with(".y"))
```


```{r egp-to-NS-ESEC}
# EGP Similar to NS-ESEC
levels(elsoc_long$egp8_hh_label_na)
elsoc_long$esec8_hh_label_na <-
  car::recode(
    elsoc_long$egp8_hh_label_na,
    recodes = "'I Higher Controllers'='Higher managers/professionals';
    'II Lower Controllers'='Lower managers/professionals';
    'IIIa Routine Nonmanual'='Intermediate occupations';
    'IV Self-employed'='Small employers/self-employed';
    'V Manual Supervisors'='Lower supervisory/technical occupations';
    'VI Skilled Worker'='Semiroutine occupations';
    c('IIIb Lower Sales-Service','VII Unskilled Workers')='Routine occupations'",
as.factor = T,
levels = c(
  "Higher managers/professionals",
  "Lower managers/professionals",
  "Intermediate occupations",
  "Small employers/self-employed",
  "Lower supervisory/technical occupations",
  "Semiroutine occupations",
  "Routine occupations",
  "Never worked and long-term unemployed",
  "Retired"
)
  )

elsoc_long$esec6_hh_label_na <-
  car::recode(
    as.numeric(elsoc_long$esec8_hh_label_na),
    "1='Service high';2='Service low';3='Routine nonmanual';4='Self-employed';5='Lower supervisory/technical occupations'; 6:7='Working class';8:9='Never worked, long-term unemployed or retired'",
    levels = c(
      "Service high",
      "Service low",
      "Routine nonmanual",
      "Self-employed",
      "Lower supervisory/technical occupations",
      "Working class",
      "Never worked, long-term unemployed or retired"
    ),
    as.factor = T
  )
frq(elsoc_long$esec6_hh_label_na)
```


# Homogeneity Class

```{r}
frq(elsoc_long$esec8_hh_label_na)

elsoc_long %>% group_by(esec8_hh_label_na) %>% summarise(isei08=mean(isei08res,na.rm=T)) 
elsoc_long %>% group_by(esec8_hh_label_na) %>% summarise(educyear=mean(educyear,na.rm=T)) 
elsoc_long %>% group_by(esec8_hh_label_na) %>% summarise(ing_pc=median(ing_pc,na.rm=T)) 

levels(elsoc_long$esec8_hh_label_na)

class_low<- c("Semiroutine occupations","Routine occupations","Never worked and long-term unemployed","Retired")
class_mid<- c("Intermediate occupations","Small employers/self-employed","Lower supervisory/technical occupations")
class_hig<- c("Higher managers/professionals","Lower managers/professionals")

elsoc_long$ingroup <- NA 
elsoc_long %>% select(esec8_hh_label_na,num_high,num_middle,num_low,ingroup)
elsoc_long$ingroup <- ifelse(elsoc_long$esec8_hh_label_na %in% class_hig,elsoc_long$num_high,elsoc_long$ingroup)
elsoc_long$ingroup <- ifelse(elsoc_long$esec8_hh_label_na %in% class_mid,elsoc_long$num_middle,elsoc_long$ingroup)
elsoc_long$ingroup <- ifelse(elsoc_long$esec8_hh_label_na %in% class_low,elsoc_long$num_low,elsoc_long$ingroup)
frq(elsoc_long$ingroup);hist(elsoc_long$ingroup)

elsoc_long$outgroup <- NA 
elsoc_long %>% select(esec8_hh_label_na,num_high,num_middle,num_low,ingroup,outgroup) %>% View
elsoc_long$outgroup <- ifelse(elsoc_long$esec8_hh_label_na %in% class_hig,rowSums(elsoc_long[,c("num_low","num_middle")],na.rm = T),elsoc_long$outgroup)
elsoc_long$outgroup <- ifelse(elsoc_long$esec8_hh_label_na %in% class_mid,rowSums(elsoc_long[,c("num_low","num_high")],na.rm = T),elsoc_long$outgroup)
elsoc_long$outgroup <- ifelse(elsoc_long$esec8_hh_label_na %in% class_low,rowSums(elsoc_long[,c("num_middle","num_high")],na.rm=T),elsoc_long$outgroup)
frq(elsoc_long$outgroup);hist(elsoc_long$outgroup)

summary(elsoc_long$n_total)
elsoc_long$homclass <- as.numeric(elsoc_long$ingroup/elsoc_long$n_total)
summary(elsoc_long$homclass);hist(elsoc_long$homclass)
```

# Homogeneity ISEI

```{r}
elsoc_long <- 
elsoc_long %>% mutate(isei08grp=ntile(isei08res_fx,3)) 

elsoc_long %>% group_by(isei08grp) %>% summarise(mean=mean(isei08res_fx,na.rm=T),
                                                 median=median(isei08res_fx,na.rm=T),
                                                 min=min(isei08res_fx,na.rm=T),
                                                 max=max(isei08res_fx,na.rm=T)) 


elsoc_long$ingroup <- NA 
elsoc_long %>% select(isei08grp,num_high,num_middle,num_low,ingroup)
elsoc_long$ingroup <- ifelse(elsoc_long$isei08grp %in% 3,elsoc_long$num_high,elsoc_long$ingroup)
elsoc_long$ingroup <- ifelse(elsoc_long$isei08grp %in% 2,elsoc_long$num_middle,elsoc_long$ingroup)
elsoc_long$ingroup <- ifelse(elsoc_long$isei08grp %in% c(1),elsoc_long$num_low,elsoc_long$ingroup)
frq(elsoc_long$ingroup);hist(elsoc_long$ingroup)

elsoc_long$outgroup <- NA 
elsoc_long %>% select(isei08grp,num_high,num_middle,num_low,ingroup,outgroup) %>% View
elsoc_long$outgroup <- ifelse(elsoc_long$isei08grp %in% 3,rowSums(elsoc_long[,c("num_low","num_middle")],na.rm = T),elsoc_long$outgroup)
elsoc_long$outgroup <- ifelse(elsoc_long$isei08grp %in% 2,rowSums(elsoc_long[,c("num_low","num_high")],na.rm = T),elsoc_long$outgroup)
elsoc_long$outgroup <- ifelse(elsoc_long$isei08grp %in% c(1),rowSums(elsoc_long[,c("num_middle","num_high")],na.rm=T),elsoc_long$outgroup)
frq(elsoc_long$outgroup);hist(elsoc_long$outgroup)

elsoc_long$homstatus <- as.numeric(elsoc_long$ingroup/elsoc_long$n_total)
summary(elsoc_long$homstatus);hist(elsoc_long$homstatus)
```

```{r}

# https://www.cambridge.org/core/books/egocentric-network-analysis/analyzing-ego-networks/DA5B39714F842C764DE3F4F2B27C887F

sqrt((88-15)^2 +(88-15)^2 + (88-15)^2) / 3
sqrt(((88-15)^2)*3)/3

elsoc_long$sq_doctor<- ((elsoc_long$isei_doctor - elsoc_long$isei08res_fx)^2)*elsoc_long$n_doctor #square distance doctor 
elsoc_long$sq_ceo<- ((elsoc_long$isei_ceo - elsoc_long$isei08res_fx)^2)*elsoc_long$n_ceo #square distance account 
elsoc_long$sq_lawyer<- ((elsoc_long$isei_lawyer - elsoc_long$isei08res_fx)^2)*elsoc_long$n_lawyer #square distance account 
elsoc_long$sq_univprof<- ((elsoc_long$isei_univprof - elsoc_long$isei08res_fx)^2)*elsoc_long$n_univprof #square distance account 

elsoc_long$sq_account<- ((elsoc_long$isei_account - elsoc_long$isei08res_fx)^2)*elsoc_long$n_account #square distance account 
elsoc_long$sq_secret <- ((elsoc_long$isei_secret - elsoc_long$isei08res_fx)^2)*elsoc_long$n_secret #square distance account 
elsoc_long$sq_shopassi <- ((elsoc_long$isei_shopassi - elsoc_long$isei08res_fx)^2)*elsoc_long$n_shopassi #square distance account 
elsoc_long$sq_kinder <- ((elsoc_long$isei_kinder - elsoc_long$isei08res_fx)^2)*elsoc_long$n_kinder #square distance account 

elsoc_long$sq_waiter  <- ((elsoc_long$isei_waiter - elsoc_long$isei08res_fx)^2)*elsoc_long$n_waiter #square distance account 
elsoc_long$sq_carmech <- ((elsoc_long$isei_carmech - elsoc_long$isei08res_fx)^2)*elsoc_long$n_carmech #square distance account 
elsoc_long$sq_taxi    <- ((elsoc_long$isei_taxi - elsoc_long$isei08res_fx)^2)*elsoc_long$n_taxi #square distance account 
elsoc_long$sq_stvend  <- ((elsoc_long$isei_stvend - elsoc_long$isei08res_fx)^2)*elsoc_long$n_stvend #square distance account 
elsoc_long$sq_cleaner <- ((elsoc_long$isei_cleaner - elsoc_long$isei08res_fx)^2)*elsoc_long$n_cleaner #square distance account 

sq_names<- elsoc_long %>% select(starts_with("sq_")) %>% names()
a<- rowSums(elsoc_long[,c(sq_names)],na.rm = T)

b<- sqrt(a)/elsoc_long$n_total
elsoc_long$homsqt <- as.numeric(b)
summary(elsoc_long$homsqt)
elsoc_long[,c("diversitypca",
              "diversitycfa","homclass","homstatus","homisei","homogeneity","homsqt","just_educ","just_salud","just_pension")] %>% sjPlot::tab_corr()


elsoc_long[,c("diversitypca",
              "diversitycfa","homclass","homstatus","homisei","homogeneity","homsqt",
              "just_educ","just_salud","just_pension")] %>% 
  sjPlot::tab_corr()

elsoc_long[,c("diversitypca",
              "diversitycfa","strong_tie_t1")] %>% 
  sjPlot::tab_corr()
```


# Save data

```{r}
save(elsoc_long,file = here::here("input/data/proc/study2.RData"))
# sjPlot::view_df(elsoc_long,file = here::here("input/data/proc/study2-codebook.html"),show.frq = T)
```



```{r just-class-status, eval=FALSE, include=FALSE}
bind_rows(
elsoc_long %>%
  filter(ola==1) %>% 
  group_by(egp8_hh_label_na) %>% 
  summarise(perc=weighted.mean(just_educ,na.rm = T,w=ponderador01),Status="1. Education"),
elsoc_long %>%
  filter(ola==1) %>%   
  group_by(egp8_hh_label_na) %>% 
  summarise(perc=weighted.mean(just_salud,na.rm = T,w=ponderador01),Status="2. Health"),
elsoc_long %>%
  filter(ola==1) %>%   
  group_by(egp8_hh_label_na) %>% 
  summarise(perc=weighted.mean(just_pension,na.rm = T,w=ponderador01),Status="3. Pensions")
) %>% 
  na.omit() %>% 
  ggplot(aes(x=factor(egp8_hh_label_na),y = perc, group=Status, color=Status)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(1,5)) +
  # scale_x_discrete(labels=c("2016","2018","2021")) +
  labs(title = "Market-based distribution of social services by Class (Wave 1)",x="Class",y=NULL) +
  theme()
```

```{r eval=FALSE, include=FALSE}
bind_rows(
elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(isei_avg=mean(isei_avg,na.rm = T),
         field="Network average ISEI"),
) %>% na.omit() %>% 
  ggplot(aes(x=factor(ola),y = isei_avg, group=field, color=field,label=round(isei_avg,2))) +
  geom_point()+
  geom_line() +
  geom_label()+
  scale_y_continuous(limits = c(16,88)) +
  scale_x_discrete(labels=c("2016","2017","2021")) +
  labs(title = "Network average ISEI by year",x="Year",y=NULL)

elsoc_long_2016_2022.2 %>% 
  ggplot(aes(x=factor(ola),y = isei_avg)) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0,100)) +
  scale_x_discrete(labels=c("2016","2017","2018","2019","2021","2022")) +
  labs(title = "Network average ISEI by year",x="Year",y=NULL)


elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(n_total=mean(n_total,na.rm = T),
         field="Total number of contacts") %>%
  filter(n_total>0) %>% 
  na.omit() %>% 
  ggplot(aes(x=factor(ola),y = n_total, group=field,label=round(n_total,2))) +
  geom_point()+
  geom_line() +
  geom_label()+
  scale_y_continuous(limits = c(0,221)) +
  scale_x_discrete(labels=c("2016","2017","2021")) +
  labs(title = "Network total contacts by year",x="Year",y=NULL)

elsoc_long_2016_2022.2 %>% 
  ggplot(aes(x=factor(ola),y = n_total)) +
  geom_boxplot() +
  # scale_y_continuous(limits = c(0,100)) +
  scale_x_discrete(labels=c("2016","2017","2018","2019","2021","2022")) +
  labs(title = "Network total contacts by year",x="Year",y=NULL)


elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(isei_range=mean(isei_range,na.rm = T),field="Network ISEI range") %>% 
    na.omit() %>% 
  ggplot(aes(x=factor(ola),y = isei_range, group=field, color=field)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(0,72)) +
  scale_x_discrete(labels=c("2016","2017","2021")) +
  labs(title = "Network ISEI range by year",x="Year",y=NULL)

elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(diversity=mean(diversity,na.rm = T),field="Network ISEI range") %>% 
    na.omit() %>% 
  ggplot(aes(x=factor(ola),y = diversity, group=field, color=field)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(0,1)) +
  scale_x_discrete(labels=c("2016","2017","2021")) +
  labs(title = "Network diversity (occupations) by year",x="Year",y=NULL)


elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(diversityclass=mean(diversityclass,na.rm = T),field="Network diversity") %>% 
    na.omit() %>% 
  ggplot(aes(x=factor(ola),y = diversityclass, group=field, color=field)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(0,1)) +
  scale_x_discrete(labels=c("2016","2017","2021")) +
  labs(title = "Network diversity (status groups) by year",x="Year",y=NULL)

elsoc_long_2016_2022.2 %>%
  filter(ola==1) %>%
  group_by(egp8_r_label) %>% 
  summarise(diversityclass=weighted.mean(diversityclass,na.rm = T,w=NULL),field="Network diversity") %>% 
    na.omit() %>% 
  ggplot(aes(x=factor(egp8_r_label),y = diversityclass, group=field, color=field)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(0.5,1)) +
  # scale_x_discrete(labels=c("2016","2017","2021")) +
  labs(title = "Network diversity (status groups) by Class (Wave 1)",x="Year",y=NULL)


elsoc_long_2016_2022.2 %>%
  filter(ola==1) %>%
  group_by(egp8_r_label) %>% 
  summarise(diversity=weighted.mean(diversity,na.rm = T,w=ponderador_long_total),field="Network diversity") %>% 
    na.omit() %>% 
  ggplot(aes(x=factor(egp8_r_label),y = diversity, group=field, color=field)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(0.5,1)) +
  # scale_x_discrete(labels=c("2016","2017","2021")) +
  labs(title = "Network diversity (occupations) by Class (Wave 1)",x="Year",y=NULL)


bind_rows(
elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(perc=weighted.mean(porc_high,na.rm = T,w = ponderador_long_total),Status="1. high-status"),
elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(perc=weighted.mean(porc_middle,na.rm = T,w=ponderador_long_total),Status="2. middle-status"),
elsoc_long_2016_2022.2 %>%
  group_by(ola) %>% 
  summarise(perc=weighted.mean(porc_low,na.rm = T,w=ponderador_long_total),Status="3. low-status")
) %>% 
  na.omit() %>% 
  ggplot(aes(x=factor(ola),y = perc, group=Status, color=Status)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(10,90),n.breaks = 20) +
  scale_x_discrete(labels=c("2016","2018","2021")) +
  labs(title = "Network percentage of high, middle and low occupations by year",x="Year",y=NULL) +
  theme()

bind_rows(
elsoc_long_2016_2022.2 %>%
  filter(ola==1) %>% 
  group_by(egp8_r_label) %>% 
  summarise(perc=weighted.mean(porc_high,na.rm = T,w=ponderador_long_total),Status="1. high-status"),
elsoc_long_2016_2022.2 %>%
  filter(ola==1) %>%   
  group_by(egp8_r_label) %>% 
  summarise(perc=weighted.mean(porc_middle,na.rm = T,w=ponderador_long_total),Status="2. middle-status"),
elsoc_long_2016_2022.2 %>%
  filter(ola==1) %>%   
  group_by(egp8_r_label) %>% 
  summarise(perc=weighted.mean(porc_low,na.rm = T,w=ponderador_long_total),Status="3. low-status")
) %>% 
  na.omit() %>% 
  ggplot(aes(x=factor(egp8_r_label),y = perc, group=Status, color=Status)) +
  geom_point()+
  geom_line() +
  scale_y_continuous(limits = c(10,90),n.breaks = 20) +
  # scale_x_discrete(labels=c("2016","2018","2021")) +
  labs(title = "Network percentage of high, middle and low occupations by Class (Wave 1)",x="Class",y=NULL) +
  theme()
```



